### ISSUE TITLE
Python build error

### ISSUE THREAD

**Issue by rm-9-hue** [FEniCS/dolfinx#1000]
I've managed to successfully build the C++ dolfin libraries. When I cd into the python directory and try to install using "pip3 install ." , I get an error 

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/fenics-ffcx/

Looks like the URL does not exist. Is there a way to update so it can pull from bitbucket instead?

**Comment by michalhabera** [comment]
FFCx is a requirement to install dolfinx. Please follow the steps here, https://github.com/FEniCS/dolfinx/blob/master/.circleci/config.yml

You are missing
```
pip3 install git+https://github.com/FEniCS/fiat.git --upgrade
pip3 install git+https://github.com/FEniCS/ufl.git --upgrade
pip3 install git+https://github.com/FEniCS/ffcx.git --upgrade
```
