### ISSUE TITLE
SpecialFunctions no longer required

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#1008]
As far as I can tell, there is no need for using any of the [special functions](https://github.com/FEniCS/dolfinx/blob/14a63a50c99bd28f17247ecb16a0e4195fae4492/python/dolfinx/specialfunctions.py)
as `x = ufl.SpatialCoordinate(mesh)` is used throughout tests and demos.
The documentation of these functions are also out of date.

@garth-wells do you have any objections, or should I just remove this file and fix all imports?

**Comment by garth-wells** [comment]
Can a user pass a `dolfin.Mesh` directly to the UFL functions in question?

**Comment by jorgensd** [comment]
We have been doing this for `SpatialCoordinate for a while in multiple tests, see for instance: https://github.com/FEniCS/dolfinx/blob/e55ebfc587482fc74f6b444a723cce7f6c0c89e5/python/test/unit/fem/test_fem_pipeline.py#L50
I can test if it holds for all special functions if we are not certain that is always the case.

**Comment by garth-wells** [comment]
If that works they should all work, so I'm happy to see SpecialFunctions deleted.

**Comment by jorgensd** [comment]
Fixed in 1f11e98
