### ISSUE TITLE
Evaluation of function on quads and hexes fails for non-parallelograms and non-parallelepipes

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#1038]
As there is no affine transformation for the non-parallel quads and hexes, function evaluation with physical coordinates fails (Note that the evaluation does not throw an error, but the returned value is incorrect).
MWE.
```
from dolfinx.io import XDMFFile
from dolfinx.mesh import create_mesh
import numpy as np
from mpi4py import MPI
import ufl
from dolfinx import Function, FunctionSpace, geometry

points = np.array([[0, 0], [1, 0], [1.1, 1], [0.2, 1]])
cells = np.array([[0, 3, 1, 2]])
cell = ufl.Cell("quadrilateral", geometric_dimension=2)
domain = ufl.Mesh(ufl.VectorElement("Lagrange", cell, 1))
mesh = create_mesh(MPI.COMM_WORLD, cells, points, domain)
V = FunctionSpace(mesh, ("CG", 1))

u = Function(V)
u.interpolate(lambda x: x[0])

# Sample points along an interior line of the domain
point = np.array([0.2, 0.2, 0])

# Create boundingboxtree
tree = geometry.BoundingBoxTree(mesh, mesh.geometry.dim)
actual_cell = geometry.compute_colliding_cells(tree, mesh,
                                                       point, 1)

# Evaluate function at points, and create the exact solution
u_eval = u.eval(point, actual_cell[0])
exact = point[0]
assert np.allclose(u_eval, exact)
```
I guess a workaround could be made with #560

**Comment by jorgensd** [comment]
This is related to the `compute_reference_geometry` in ffcX as it will default to the [affine mapping]( https://github.com/FEniCS/ffcx/blob/e492492b01e1e2788f18c40dbabd329117ab3727/ffcx/codegeneration/coordinate_mapping.py#L210)
However, using the Newton mapping does not solve the problem, as they Newton-solver diverges if one increase the [max_iteration count](https://github.com/FEniCS/ffcx/blob/e492492b01e1e2788f18c40dbabd329117ab3727/ffcx/codegeneration/coordinate_mapping.py#L452).

**Comment by jorgensd** [comment]
Issue can be fixed for first order geometries with the following ffcx branch https://github.com/FEniCS/ffcx/compare/chris/quad-hex-use-newton
Need to check compatibility with higher order geometries, after merging #1040

**Comment by michalhabera** [comment]
@jorgensd Isn't this fixed now?
