### ISSUE TITLE
jit compilation flag -march is specific to x86

### ISSUE THREAD

**Issue by RizzerOnGitHub** [FEniCS/dolfinx#1045]
jit compilation adds flag `-march=native` in [extra_compile_args](https://github.com/FEniCS/dolfinx/blob/9af7a6ec32ed8ad079f0896196048189c76f28d3/python/dolfinx/jit.py#L100)

The `-march` flag is specific to x86 processors. powerpc for instance does not support it. `-mcpu=native` is a possible alternative (there's also `-mtune`). Then again on some other architectures neither flag is supported.

Executation fails on such systems, e.g. powerpc64le and demo_poisson.py

    >               raise CalledProcessError(retcode, process.args,
                                             output=stdout, stderr=stderr)
    E               subprocess.CalledProcessError: Command '['/usr/bin/python3', 'demo_poisson.py']' returned non-zero exit status 1.
    
    /usr/lib/python3.8/subprocess.py:512: CalledProcessError
    ----------------------------- Captured stderr call -----------------------------
    powerpc64le-linux-gnu-gcc: error: unrecognized command line option ‘-march=native’; did you mean ‘-mcpu=native’?

Should some logic be added (at build-time say) to determine if the arch/cpu flag is supported for the given system?

**Comment by michalhabera** [comment]
We still haven't decided what is a default set of compiler flags. However, we should not suffer from lacking support on less common architectures. You can always control compiler flags with `export DOLFINX_JIT_CFLAGS="-O0"` etc.

For me, no need to add any logic. User of non x86 architecture should just change the flags.

**Comment by garth-wells** [comment]
My view is we should pick a conservative set of default flags, i.e. stick to `-O2` or `-O3` and avoid architecture-dependent defaults. The overall benefits of further flags are rather minor in general.

**Comment by chrisrichardson** [comment]
Probably `-O2` is safe on anything. So we could just delete `-march=native` and let users try with `DOLFIN_JIT_CFLAGS` if they want.

**Comment by RizzerOnGitHub** [comment]
Conservative defaults sounds sensible.  DOLFIN_JIT_CFLAGS gives good flexibility, just need to make sure it's well documented!

**Comment by michalhabera** [comment]
Solved in #1048
