### ISSUE TITLE
FindKaHIP fails on Fedora32 because of linker issues

### ISSUE THREAD

**Issue by mrambausek** [FEniCS/dolfinx#1058]
On Fedora32, FindKaHIP fails because the linker complains about `kaffpa` being defined twice -- once in the serial and once in the parallel version. The testing code is compiled against both. On my system the test passes when 
```set(KAHIP_LIBRARIES ${PARHIP_LIBRARY} ${MKAHIP_LIBRARY})```
is used instead of
```set(KAHIP_LIBRARIES ${KAHIP_LIBRARY} ${PARHIP_LIBRARY} ${MKAHIP_LIBRARY})```

This issue most likely trickles down to the dolfinx as well - did not try yet. What surprises me is that there is no issue on Ubuntu. I guess, this is due to some different default flags for gcc. Ubuntu seems to be more "permissive" in this regard.
Also, I have no clue against which of these libs one has to link in the end...

**Comment by IgorBaratta** [comment]
You're right. Both serial and "modified_kahip" (needed for using the parallel interface) define `kaffpa`. We could just remove the serial part `${KAHIP_LIBRARY}` as you suggested, since dolfinx "uses" only the parallel interface.

But I think It would be even better if `Kahip` used namespace.

**Comment by mrambausek** [comment]
Agree. Namespaces or non-overlapping names at least (for C-style interface) would be nice. Though I would not want to take on that task -- no time in the near and not so near future...

**Comment by mrambausek** [comment]
But if it is okay for you I can play around with the cmake variables on my system to make things work and then provide a small PR...

**Comment by IgorBaratta** [comment]
> But if it is okay for you I can play around with the cmake variables on my system to make things work and then provide a small PR...

@mrambausek have you had the chance to  look for a solution?
FindKaHIP also failed on Scientific Linux 7 too.

`set(KAHIP_LIBRARIES ${PARHIP_LIBRARY} ${MKAHIP_LIBRARY})`
seems to work. But I wonder if you found a better solution.

**Comment by mrambausek** [comment]
@IgorBaratta I don't have something better. Tbh, it has not been quite high on my priority list. Did you try with their new release?

**Comment by IgorBaratta** [comment]
I'm updating it for the latest released version (v3.10), although there are no changes to the parallel interface.

**Comment by mrambausek** [comment]
@IgorBaratta is it Ubuntu required to use
`set(KAHIP_LIBRARIES ${KAHIP_LIBRARY} ${PARHIP_LIBRARY} ${MKAHIP_LIBRARY})`?
In my experience, Ubuntu is often more permissive than the RedHat family members (also regarding default compiler flags etc)....

**Comment by IgorBaratta** [comment]
> @IgorBaratta is it Ubuntu required to use
> `set(KAHIP_LIBRARIES ${KAHIP_LIBRARY} ${PARHIP_LIBRARY} ${MKAHIP_LIBRARY})`?
> In my experience, Ubuntu is often more permissive than the RedHat family members (also regarding default compiler flags etc)....

No, it's not required..  I removed `MKAHIP_LIBRARY` and simplified  `findKaHIP` to use the standard cmake installation in #1260 .
