### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by juntang-zhuang** [FEniCS/dolfinx#1066]
Hi, I wonder if FEniCS will support GPU? It seems there was an old version with GPU support, then it was removed.

**Comment by garth-wells** [comment]
The GPU space is too complicated and varied at the moment to add support, and performance portability is very challenging.

It is possible to use GPUs with DOLFIN-X and experiments are underway. Take a look at the code in https://github.com/FEniCS/dolfinx/blob/master/python/test/unit/fem/test_custom_assembler.py to see how the underlying data arrays can be extracted. The can be passed to OpenCL/SYCL/CUDA kernels. It's quite easy to experiment using `pyopencl` and `pycuda`.
