### ISSUE TITLE
FEM pipeline tests not working for vector-valued elements in parallel

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#1072]
The tests re-enabled in c48cd4f156042308cca948c8722f1436a6215baf fail in parallel.

I think we originally disabled them due to ghosting not being implemented. I need to debug why they are still failing.

This discourse question is related to this: https://fenicsproject.discourse.group/t/h-curl-elements-with-mpi-returns-incorrect-function-values/3737

**Comment by chrisrichardson** [comment]
Am I right to say that this does not affect vector Lagrange elements?
I don't think ghosting should be an issue for Nedelec or RT elements. I wonder if they are getting the correct permutations across processes?

**Comment by mscroggs** [comment]
Yes, Lagrange seems fine. I think it was using vertex numbers from the local process, not global numbers. I've fixed it for triangles, and am almost there for tetrahedra now
