### ISSUE TITLE
Add spack package manager recipe

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1087]
It would be helpful to have a Spack (https://spack.readthedocs.io/) recipe, and test it with CI.

@js947 might have some experience.

**Comment by js947** [comment]
I have a repo of spack packages for dolfinx, ffcx, etc here https://github.com/js947/spack-fenics

Haven't updated it in a few months but can do so!

**Comment by js947** [comment]
I'll clean it up and submit a PR to spack to add dolfinx (+ friends) packages.

**Comment by benzwick** [comment]
I started working on this a while back but there were some issues then (Python 2/3 compatibility) that I believe are now resolved:

https://github.com/spack/spack/pull/10240

Perhaps a FEniCS developer is in a better position to complete this PR, or take the ideas and create a new one.

**Comment by garth-wells** [comment]
See https://github.com/spack/spack/pull/17743.
