### ISSUE TITLE
Updates for vectorised SubDomain::inside/map

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#11]
Places where `SubDomain::inside` are called need updating for the new vectorised interface. Places include:

- `DirichletBC::compute_bc_pointwise`

**Comment by jon-deng** [comment]
Hi!

I want to contribute to FEniCS but I'm a bit of a c++ noob. Could you point me in a direction to work on this issue?

I did a search in the code base but wasn't able to find the spot to update.

**Comment by michalhabera** [comment]
Resolved when `SubDomain` was removed. Legacy `inside` evaluation is now fully vectorised, see#453
