### ISSUE TITLE
Automatic release process for FEniCSX

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#1116]
Making a release of FEniCS has been a tortuous and error prone process in the past, typically taking 1-2 days of person time.

By heavy use of automation, can we make a release of FEniCS as simple as pushing a button?

Discussion on all aspects of making a releases (version numbering, frequency, artefacts that need to be produced, archiving locations etc.) below.

**Comment by garth-wells** [comment]
@jhale are we happy with where we’re now at?

**Comment by garth-wells** [comment]
@jhale most recent release seemed straightforward. Can we close this issue?
