### ISSUE TITLE
Updates for STL compatible iterators on Array in Eigen 3.4

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#1119]
In Eigen 3.4 (we are currently based around whatever is in Ubuntu) the `Eigen::Array` class has support for STL compatible `.begin()` and `.end()` methods.

https://eigen.tuxfamily.org/dox-devel/group__TutorialSTL.html

Would make some algorithms look a lot clearer, e.g. https://github.com/FEniCS/dolfinx/blob/master/cpp/dolfinx/fem/assemble_matrix_impl.h#L298

**Comment by chrisrichardson** [comment]
Is 3.4 an actual release? Where do you download it from?

**Comment by IgorBaratta** [comment]
I think the latest release is still [3.3.7](http://eigen.tuxfamily.org/index.php?title=Main_Page).
But the development/master branch (which is still version 3.3.9)  has most of these features.

**Comment by jhale** [comment]
Think there will be a beta soon.

**Comment by jorgensd** [comment]
The 3.3.9 release has some nice slicing/indexing features as well:
https://eigen.tuxfamily.org/dox-devel/group__TutorialSlicingIndexing.html

**Comment by chrisrichardson** [comment]
3.3.8 is now out
http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.8

**Comment by IgorBaratta** [comment]
Eigen 3.3.9 is out.. https://gitlab.com/libeigen/eigen/-/releases/3.3.9
But it is still not the release we are waiting for, it's just a maintenance release fixing minor bugs

**Comment by garth-wells** [comment]
For 1D arrays we are now favouring `std::vector` and `span` over Eigen.
