### ISSUE TITLE
Jump integrals not correct for Hdiv and Hcurl

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#1134]
Dof permuting has not been implemented yet to cover these, as I discovered when trying to add more tests for Dof permuting:

https://github.com/FEniCS/dolfinx/blob/13fab1e29b748de77bbc8fb1def7f9ff2227e8d4/python/test/unit/fem/test_dof_permuting.py#L524-L781

**Comment by garth-wells** [comment]
@mscroggs can this issue be closed now following the merge of #1135?

**Comment by mscroggs** [comment]
No, this is a separate issue that I need to fix

**Comment by jorgensd** [comment]
Is this still relevant?

**Comment by mscroggs** [comment]
Yes, the tests are still disabled and would fail

**Comment by garth-wells** [comment]
@mscroggs could we look at this again?

**Comment by mscroggs** [comment]
Yes, should be a slightly easier fix now that the FFCx kernels are simpler
