### ISSUE TITLE
C++ tests fail on 32 bit systems

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/dolfinx#1147]
C++ tests and demos are failing on 32 bit systems (i386, armhf).  But python tests are passing, which suggests the 32 bit systems themselves are fine and the problem is in the config file for the tests.

Logs can be found at https://ci.debian.net/packages/d/dolfinx/
e.g. i386 https://ci.debian.net/data/autopkgtest/testing/i386/d/dolfinx/7272770/log.gz
armhf  https://ci.debian.net/data/autopkgtest/unstable/armhf/d/dolfinx/7268765/log.gz

Tests are run through `cmake $srcdir` and  `make tests`
see https://salsa.debian.org/science-team/fenics/dolfinx/-/blob/master/debian/tests/test-dolfinx-cpp

The error message is
```
==== running C++ tests ====
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/mpicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:5 (find_package):
  Could not find a configuration file for package "DOLFINX" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    /usr/share/dolfinx/cmake/DOLFINXConfig.cmake, version: 2019.2.9.99 (64bit)



-- Configuring incomplete, errors occurred!
```
The reference to "64 bit" in the error message suggests to me that the 32/64-bit test in `/usr/share/dolfinx/cmake/DOLFINXConfigVersion.cmake` is not correct for 32-bit systems:
```
# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
  math(EXPR installedBits "8 * 8")
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```

**Comment by RizzerOnGitHub** [comment]
Possibly the error is in the debian packaging. /usr/share/dolfinx/cmake/DOLFINXConfigVersion.cmake is provided in a common arch-independent support package, libdolfinx-dev.  I've check that arch-specific values like "arm-linux-gnueabihf" have been replaced with the common cmake variable CMAKE_LIBRARY_ARCHITECTURE.  

But I suspect this test `8 * 8` is also architecture-specific. I would need to find the corresponding cmake expression to replace it with if I want to keep libdolfinx-dev as a common arch-independent support package.

**Comment by RizzerOnGitHub** [comment]
I'll try changing `if("FALSE")` to `if("TRUE")` in DOLFINXConfigVersion.cmake.
This is a packaging issue since I made the decision to convert /usr/share/dolfinx/cmake/ to an arch-independent state so that libdolfinx-dev could be a common package for all arches.

**Comment by garth-wells** [comment]
Should this issue be closed, or is there something we can do?

**Comment by drew-parsons** [comment]
The `if("TRUE")` would be specific to the packaging, so nothing to do there.

As far using CMAKE_LIBRARY_ARCHITECTURE in DOLFINXTargets.cmake (not DOLFINXConfigVersion.cmake), that seems to be a cmake limitation in the cmake install() function which generates DOLFINXTargets.cmake. Not sure if it's simple for the dolfinx build scripts to control it to use CMAKE_LIBRARY_ARCHITECTURE instead of the specific arch triplet.

That's controlled by the install functions at ll.137,145 in cpp/dolfinx/CMakeLists.txt.  l.137 generates DOLFINXTargets.cmake. Possibly

    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT RuntimeLibraries
could be replaced with

    LIBRARY DESTINATION "lib/\${CMAKE_LIBRARY_ARCHITECTURE}" COMPONENT RuntimeLibraries
(or whatever is required to get it to write `"lib/${CMAKE_LIBRARY_ARCHITECTURE}` in the file) but I think that's too messy for the main dolfinx code. Really it's just a hack for debian making the libdolfinx-dev package arch-independent.


One change that could be considered is changing l.145 from

    install(EXPORT DOLFINXTargets DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/dolfinx/cmake)
to

    install(EXPORT DOLFINXTargets DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/dolfinx)

which would install the cmake file under /usr/lib instead of /usr/share, which would be appropriate if DOLFINXTargets.cmake contains the arch-dependent paths in the INTERFACE_LINK_LIBRARIES field.  Logically (in terms of what /usr/share should contain, i.e. not containing arch-specific references) this "should" be done. Probably the other uses of CMAKE_INSTALL_DATAROOTDIR in cpp/dolfinx/CMakeLists.txt should then be changed the same way to keep all the installed dolfinx cmake files in one place. In practice it's not so important unless some site is provide one /usr/share partition shared with multiple architectures at the same time.

If you're happy with the current installation of DOLFINXTargets under /usr/share (CMAKE_INSTALL_DATAROOTDIR), then we can close this issue.

**Comment by garth-wells** [comment]
I'd be happy with
```
install(EXPORT DOLFINXTargets DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/dolfinx)
```
Perhaps that is nowadays the more common location?

**Comment by drew-parsons** [comment]
True, and also /usr/share/dolfinx/cmake would not automatically be added to the cmake search path. /usr/share is not listed as such at https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure. (/usr/share, or /usr/share/dolfinx/cmake, would have to be set manually in CMAKE_MODULE_PATH in the CMakeLists.txt for a client project)

Installation under /usr/lib (via CMAKE_INSTALL_LIBDIR) makes sense when there are arch references in INTERFACE_LINK_LIBRARIES (such as /usr/lib/x86_64-linux-gnu/libm.so).

Thumbs up from me to switch the cmake installation to CMAKE_INSTALL_LIBDIR.

Disclaimer: for Debian I might shift them back to /usr/share, but that would be because I'm enabling simultaneous installation of complex and real builds. The libdolfinx-real-dev and libdolfinx-complex-dev packages are arch-dependent (containing  /usr/lib/x86_64-linux-gnu/ files such as .so symlinks) but I've got the include files in the common package libdolfinx-dev.  It's not so hard in the debian scripts to hack the cmake files to use CMAKE_LIBRARY_ARCHITECTURE, in which case I can make libdolfinx-dev arch-independent. But you probably don't want that kind of hackery in the original dolfinx build scripts. CMAKE_INSTALL_LIBDIR is a cleaner location for a single local build.
