### ISSUE TITLE
Add demo using vedo and/or pyvista for visualisation

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1159]
It looks like Python/Jupyter tools for 3D visualisation have come along quite a bit recently. `vedo` (https://vedo.embl.es/) and `pyvista` (https://www.pyvista.org/) look nice and work with mesh data in VTK ordering, which should make it reasonably straightforward to interface to them. There is even support for high-order geometries.  

- [x] pyvista
- [ ] vedo

The design should avoid importing vdeo or pyvista in the DOLFINX core, but add interfaces for returning the data in a suitable format.

**Comment by jorgensd** [comment]
As Vedo requires VTK<9.0.1, which is not pip installable, I suggest we test pyvista.

**Comment by jorgensd** [comment]
@garth-wells I do not think we should proceed with either of these software just yet.
*vedo*: Does not use latest VTK available with pip, which requires user installation of an older VTK version
*pyvista*: Does not support higher order Lagrangian elements yet (https://github.com/pyvista/pyvista/issues/947)

**Comment by garth-wells** [comment]
Both worked fine for me recently when I tested. Higher-order elements isn't really an issue since we don't support higher-order elements with Matplotlib.

Is there a good reason to support Matplotlib over vedo or pyvista?

**Comment by jorgensd** [comment]
Matplotlib is not dependent on VTK. This means that visualization can be done without extra configuration in docker and on HPC systems (as long as matplotlib is installed). VTK can cause issues such as https://github.com/pyvista/pyvista/issues/155 when using docker containers, which would require extra overhead from the users side. I can of course make a demo using Pyvista on first order meshes (and add some io wrappers).

**Comment by marcomusy** [comment]
> As Vedo requires VTK<9.0.0, which is not pip installable, 

vtk 8.* is pip installable.

**Comment by jorgensd** [comment]
> > As Vedo requires VTK<9.0.0, which is not pip installable,
> 
> vtk 8.* is pip installable.

You are absolutely right. For some strange reason my pip installation didn’t want to find any of the other versions.

**Comment by marcomusy** [comment]
It seems _you_ were actually right! Apparently vtk doesn't have wheels for python 3.8 - that might explain why your pip did not find the version.
I'll just remove the requirement as `vedo` can work with version 9 too (see https://github.com/marcomusy/vedo/issues/235).

**Comment by jorgensd** [comment]
Currently, there is some work required for usage of vedo, see for instance: https://github.com/marcomusy/vedo/issues/297

With some collaboration with @marcomusy we can probably get something working.

**Comment by garth-wells** [comment]
pyvista demos added in #1161.
