### ISSUE TITLE
Test KaHIP library for mesh partitioning

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#116]
Test the KaHIP (http://algo2.iti.kit.edu/kahip/) library for mesh partitioning. 

The curently supported libraries, ParMETIS and PT-SCOTCH, have the hallmarks of abandonware, and aren't not great at scale.

An issue with KaHIP is that it uses the GPL license.

**Comment by TormodLandet** [comment]
KaHIP v2.1 is now MIT licensed

**Comment by IgorBaratta** [comment]
KaHIP now provides parallel partitioning API for external packages ([ParHIPPartitionKWay](https://github.com/schulzchristian/KaHIP/blob/master/parallel/parallel_src/interface/parhip_interface.h)).
Though, the interface is not yet documented in the manual v2.10.
