### ISSUE TITLE
What is 'Complex number support' on the Fenics roadmap and how can I use it?

### ISSUE THREAD

**Issue by fleetingsucess** [FEniCS/dolfinx#1165]
I have been using Fenics in the past to solve complex valued PDE's, especially variations of Helmholtz equation for wave propagation. This means writing forms with a ridiculous number of terms for the real and imaginary parts even though the math would work out if Fenics handled the complex numbers natively. I was just browsing the fenics road map and saw that 'Complex number support' is now completed! Does that mean I can rewrite my solvers with complex numbers? Where can I find examples or documentation for this? Thanks

**Comment by garth-wells** [comment]
Yes, you can write solvers with complex numbers. To get complex support you need to build against a complex build of PETSc (this will likely change in the future). See https://github.com/FEniCS/dolfinx/blob/master/python/demo/helmholtz2D/demo_helmholtz_2d.py for an example.
