### ISSUE TITLE
Optimise XDMFFile::write_checkpoint for mesh sharing

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#117]
Old `XDMFFile::write` takes into account parameters `functions_share_mesh` and `rewrite_mesh` - but not implemented for write_checkpoint. These basically specify if the mesh is shared across functions (if multiple in file) and across timesteps.

In ParaView, if multiple functions belong to the same dataset and they have all their own mesh "(partial)" is appended to their name. Some filters and functionality is limited in such case. One cannot warp by one (partial) vector field and show other (partial) scalar field on warped surface. (It is possible with ugly filter roundabout)

Such optimisation would also significantly reduce IO time and disk use.

**Comment by marchirschvogel** [comment]
> `functions_share_mesh`

I wonder why this option is not available anymore in dolfinx. Will there be a re-implementation? Any chance of viewing multiple functions on the same mesh?

**Comment by michalhabera** [comment]
Hi @marchirschvogel ,

this is possible with current XDMF IO. Mainly because one controls explicitly the storage of mesh. So you do
```python
file.write_mesh(mesh)
file.write_function(u, 0.0)
file.write_function(p, 0.0)
```
Here `u` and `p` will both share the mesh stored at default location in XDMF file. There is more advanced use possible as well, you can `write_mesh` anywhere into XDMF file and have several meshes and refer some functions to some meshes, while other functions to some other meshes.

In Paraview you have to do:
1. open file with `Xdmf3ReaderT`
2. Apply filter `Extract block` and extract e.g. displacement field
3. Apply filter `Extract block` (on the original dataset) again and extract the quantity you want to show on the warped mesh
4. Select both extracted datasets
5. Apply filter `Append attributes` and merge extracted blocks into one
6. Now apply `Warp by vector` on the merged dataset and you can visualize your field on a warped mesh.

**Comment by garth-wells** [comment]
It would be handy to add this question and answer to https://fenicsproject.discourse.group/.

**Comment by garth-wells** [comment]
Checkpointing to XDMF has been removed for the time being - will come back later in a simpler way.
