### ISSUE TITLE
demo_poisson segfaults in serial, runs fine in parallel

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#1178]
I just noticed what the title says. The segfault happens at `SparsityPattern.cpp:338`, which is
```
MPI_Neighbor_allgatherv(ghost_data.data(), ghost_data.size(), MPI_INT64_T,
                          ghost_data_received.data(), num_rows_recv.data(),
                          disp.data(), MPI_INT64_T, comm);
```

If I exclude that line with an `if (MPI::size(comm) != 1)`, then it runs fine. I have a faint suspect it might be my MPI implementation: I'm using Ubuntu 18.04, Open MPI 2.1.1 [system default]. Did anybody else experience that?

**Comment by michalhabera** [comment]
Can you try with the containers setup? We have containers and tests which run with no issues for Ubuntu 20.04+libopenmpi-dev (should be 4.0.3.) or Ubuntu 20.04+libmpich-dev (3.3.2).

**Comment by massimiliano-leoni** [comment]
I'll trust you if you say it works with containers. Then it must be an issue with my version of Open MPI...

**Comment by massimiliano-leoni** [comment]
By the way, I just realised I wrote down the wrong number for the Open MPI version, it's actually 2.1.1 so even older...

**Comment by garth-wells** [comment]
Closing because OpenMPI version is very old. Old OpenMPI in Debian/Ubuntu has numerous bugs.
