### ISSUE TITLE
Pull rate limit enforcement DockerHub

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#1188]
In November 2020 DockerHub will be implementing a rate limit of 100 pulls every 6 hours for anonymous users. We are currently pulling images anonymously, so during busy periods we could easily be pulling > 100 every 6 hours. To increase to 200 pulls we need to login before each pull.

**Comment by garth-wells** [comment]
Doesn't seem to have caused any problems, so closing.
