### ISSUE TITLE
Boundary dofs common to two boundary conditions get the wrong value

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#1205]
I have a domain that is a cube and a MeshTags object that marks triangles on different faces to different values. I apply Dirichlet boundary conditions to the various faces like so 

```
        auto dofs = fem::locate_dofs_topological(  // Find dofs
                {*V},                              // In this space (P1)
                2,                                 // Triangles
                meshTags.find(subdomainIndex));    // These triangles

        bc.push_back(
                std::make_shared<const fem::DirichletBC<PetscScalar>>(fun,
                                                                      dofs));
```
However, nodes on the edges between two faces end up having the wrong boundary condition applied to them.
I originally thought I understood why this happened, namely that the nodes were lifted twice, but I am now second-guessing that.

I was able to workaround the issue by manually removing duplicates from the output of `fem::locate_dofs_topological`, in which case I get the correct result.

**Comment by massimiliano-leoni** [comment]
Here is a modified version of the Poisson demo that demonstrates the issue

```
// main.cpp
#include "poisson.h"
#include <cmath>
#include <dolfinx.h>
#include <dolfinx/fem/petsc.h>
#include <dolfinx/function/Constant.h>

using namespace dolfinx;

int main(int argc, char* argv[])
{
  common::SubSystemsManager::init_logging(argc, argv);
  common::SubSystemsManager::init_petsc(argc, argv);

  {
    // Create mesh and function space
    auto cmap = fem::create_coordinate_map(create_coordinate_map_poisson);

    auto mesh = std::make_shared<mesh::Mesh>(generation::BoxMesh::create(
        MPI_COMM_WORLD,
        {Eigen::Vector3d(0.0, 0.0, 0.0), Eigen::Vector3d(1.0, 1.0, 1.0)},
        {4, 4, 4}, cmap, mesh::GhostMode::none));

    // This is overkill
    mesh->topology().create_connectivity_all();

    auto V = fem::create_functionspace(create_functionspace_form_poisson_a, "u",
                                       mesh);

    auto f = std::make_shared<function::Constant<PetscScalar>>(0);

    // Define variational forms
    auto a = fem::create_form<PetscScalar>(create_form_poisson_a, {V, V}, {},
                                           {}, {});
    auto L = fem::create_form<PetscScalar>(create_form_poisson_L, {V}, {},
                                           {{"f", f}}, {});

    auto u0 = std::make_shared<function::Function<PetscScalar>>(V);

    const auto topDofs = fem::locate_dofs_geometrical({*V}, [](auto& x) {
      static const double epsilon = std::numeric_limits<double>::epsilon();
      return x.row(2) > 1 - epsilon;
    });
    auto sideDofs = fem::locate_dofs_geometrical({*V}, [](auto& x) {
      static const double epsilon = std::numeric_limits<double>::epsilon();
      return x.row(0) > 1 - epsilon;
    });

    auto topFun = std::make_shared<function::Function<PetscScalar>>(V);
    topFun->x()->array().setConstant(2);
    auto sideFun = std::make_shared<function::Function<PetscScalar>>(V);
    sideFun->x()->array().setConstant(2);

    std::vector bc{
        std::make_shared<const fem::DirichletBC<PetscScalar>>(topFun, topDofs),
        std::make_shared<const fem::DirichletBC<PetscScalar>>(sideFun,
                                                              sideDofs),
    };

    function::Function<PetscScalar> u(V);
    la::PETScMatrix A = fem::create_matrix(*a);
    la::PETScVector b(*L->function_spaces()[0]->dofmap()->index_map);

    MatZeroEntries(A.mat());
    fem::assemble_matrix(la::PETScMatrix::add_fn(A.mat()), *a, bc);
    fem::add_diagonal(la::PETScMatrix::add_fn(A.mat()), *V, bc);
    MatAssemblyBegin(A.mat(), MAT_FINAL_ASSEMBLY);
    MatAssemblyEnd(A.mat(), MAT_FINAL_ASSEMBLY);

    VecSet(b.vec(), 0.0);
    VecGhostUpdateBegin(b.vec(), INSERT_VALUES, SCATTER_FORWARD);
    VecGhostUpdateEnd(b.vec(), INSERT_VALUES, SCATTER_FORWARD);
    fem::assemble_vector_petsc(b.vec(), *L);
    fem::apply_lifting_petsc(b.vec(), {a}, {{bc}}, {}, 1.0);
    VecGhostUpdateBegin(b.vec(), ADD_VALUES, SCATTER_REVERSE);
    VecGhostUpdateEnd(b.vec(), ADD_VALUES, SCATTER_REVERSE);
    fem::set_bc_petsc(b.vec(), bc, nullptr);

    la::PETScKrylovSolver lu(MPI_COMM_WORLD);
    la::PETScOptions::set("ksp_type", "preonly");
    la::PETScOptions::set("pc_type", "lu");
    lu.set_from_options();

    lu.set_operator(A.mat());
    lu.solve(u.vector(), b.vec());

    io::VTKFile file("u.pvd");
    file.write(u);
  }

  common::SubSystemsManager::finalize_petsc();
  return 0;
}
```

```
// poisson.ufl
element = FiniteElement("Lagrange", tetrahedron, 1)

coord_element = VectorElement("Lagrange", tetrahedron, 1)
mesh = Mesh(coord_element)

V = FunctionSpace(mesh, element)

u = TrialFunction(V)
v = TestFunction(V)
f = Constant(mesh)

a = inner(grad(u), grad(v)) * dx
L = inner(f, v) * dx
```

and a visualisation of the issue.
![output](https://user-images.githubusercontent.com/12351309/99285751-3c4eaa00-2838-11eb-9191-9eb0a9c7c97f.png)

**Comment by massimiliano-leoni** [comment]
Found it!
Dofs are passed twice to `fem::add_diagonal` which adds them twice to the diagonal of the matrix. Pull request #1215 tries to address this issue.

**Comment by mrambausek** [comment]
I believe, the fundamental issue is that `locate_dofs_topological` allows for double entries. Connected to that, it probably should be forbidden that there is more than one BC per dof, i.e. an exception should be thrown since the two prescribed values might not identical. Overriding already assembled values is another story and should be explicit, if allowed at all. 
Probably, the problem at hand needs some more discussion to decide on the best approach to fix it.

**Comment by massimiliano-leoni** [comment]
What do you mean by saying that `locate_dofs_topological` allows double entries? It just finds the dofs that belong to a set of cells, and it's inevitable that dofs belong to more than one cell.
The same happens with `locate_dofs_geometrical`, and the same would happen if we specified the dofs by hand.

I understand the issue with overriding assembled dofs, but on the other hand this is a basic use case. Let's see what other people think!

**Comment by mrambausek** [comment]
My first point is that manual deduplication should not be required for a *single* call of `locate_dofs_topological` (I understand the initial description of the problem such that there was only one call and not two separate as in the long example). It should be done automatically since one asks for all dofs belonging to at least one element of a set of cells/faces... such that duplications do not really make sense to me (at least I can't think of a good use case).

In a "real" implementation of the long example, when two constraints on the same FunctionSpace have connected or overlapping domains, I would rather merge the functions for the location of the dofs as well as the functions giving the value, i.e. use a "single" domain and a "single" bc function, which has to be a "proper" function (unique f(x)) anyway . Then one can again require that all `locate_dofs_xxx` function return a deduplicated set of dofs and make double-constraining a dof an error.

But let's wait for other people, since I am also not in charge (the above is just what I would prefer as a user).

**Comment by massimiliano-leoni** [comment]
Oh wait, then I didn't explain myself. Sorry about that :_D
The snippet in the first comment is meant to be run in a loop. `locate_dofs_topological` never returns duplicates, the duplicates are in the dofs defining each boundary condition.

With the approach you describe, merging several boundary conditions into one, there would be no duplicates, but at first sight that looks a bit cumbersome to do, and I wonder whether it would be worth the gain in not overriding matrix entries. These entries, by the way, would just be a few diagonal entries [codimension 2, after all].

**Comment by garth-wells** [comment]
Should be fixed in https://github.com/FEniCS/dolfinx/pull/1417.
