### ISSUE TITLE
Non-optimal performance of repeated processing or UFL forms in assembly

### ISSUE THREAD

**Issue by mrehor** [FEniCS/dolfinx#1209]
I encountered a non-optimal performance of `dolfinx.fem.assemble_*` routines on HPC infrastructures recently. I prepared the following test with some explanatory description in the contained README file: https://github.com/mrehor/dolfinx-hpc-assembly/

The thing is that there are some redundant calls of `_create_cpp_form` in [assemble.py](https://github.com/FEniCS/dolfinx/blob/c5f975ba76d047e09298021163dfb21a93a54b0f/python/dolfinx/fem/assemble.py) (e.g. L174 and L180) which seem to cause a potential I/O overhead.  

**I understand that this is technically not a bug as it is still possible to do things efficiently with the current code.** I wanted to address this HPC-related issue with the suggestion to at least expose `dolfinx.fem.assemble._create_cpp_form` within API or to rewrite assembly-related routines on the Python side to accept only forms of `cpp.fem.Form` type. Not sure if the latter option isn't too "drastic". Any thoughts?

**Comment by garth-wells** [comment]
Proposal:
1. Lower-level free functions, e.g. `assemble_foo` functions, require a `doilfinx.fem.Form` argument and should not accept a `ufl.Form`. This avoids re-processing of forms.
2. Higher-level classes, e.g. `fem.LinearProblem` accept `ufl.Form` objects. This doesn't introduce performance issues as the form is processed only once in the class initialiser.

I think this balances simplicity, efficiency and usability. If the approach becomes intrusive, then more 'high-level' interfaces can be introduced.
