### ISSUE TITLE
Revise necessity of ghostUpdate() in demos/tests

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#1216]
The actual ghostUpdate is truly needed only in very few places, for most local operations one knows the value for ghosts without communication.

This
```python
u.vector.copy(result=u0.vector)
u0.vector.ghostUpdate(addv=PETSc.InsertMode.INSERT, mode=PETSc.ScatterMode.FORWARD)
```
could become
```python
with u0.vector.localForm() as loc0, u.vector.localForm() as loc:
    loc.copy(loc0)
```

**Comment by jorgensd** [comment]
Note that we should probably add `ghostUpdate` before initializing boundary conditions. As most of the demos has homogenous boundary conditions, it is not strictly required, but has highlighted in #1180, it can in turn cause very strange discrepancies if not treated with care  .

**Comment by jorgensd** [comment]
In the demos, we now only use `GhostUpdate` whenever we want to accumulate contributions after `apply_lifting`. We could avoid using them entirely by either:
- Wrap all RHS vectors in demos as `dolfinx.fem.Function` and use our own scatter_reverse
- Use LinearProblem in favor of directly accessing the PETSc.KSP object and assemblers.

**Comment by jorgensd** [comment]
@garth-wells  Can we close this?
