### ISSUE TITLE
dolfinx::Table not binded to python

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#1217]
Used as return type in instance in dolfinx.common.timings: https://github.com/FEniCS/dolfinx/blob/master/python/dolfinx/common.py#L20-L21.

Calling this now causes a pybind11 error:
```
----> 1 dolfinx.common.timings([dolfinx.common.TimingType.wall])

/home/shared/dolfinx/python/dolfinx/common.py in timings(timing_types)
     19 
     20 def timings(timing_types: list):
---> 21     return cpp.common.timings(timing_types)
     22 
     23 

TypeError: Unable to convert function return value to a Python type! The signature was
        (arg0: List[dolfinx.cpp.common.TimingType]) -> dolfinx::Table
```
Do we want to bind `dolfinx::Table` to python, or should we remove python functions using it?

**Comment by IgorBaratta** [comment]
I am in favor of removing it.  I think this is the only function in the python interface that returns a `dolfinx::Table`, and the most common use would be that of `list_timings`.

**Comment by IgorBaratta** [comment]
@jorgensd,  can we close this issue now?
