### ISSUE TITLE
Remove SCOTCH and ParMETIS from "public interface"

### ISSUE THREAD

**Issue by IgorBaratta** [FEniCS/dolfinx#1218]
Having both exposed publicly can cause some definition conflicts, and they are not an actual part of the public interface.

We could query the size of `idx_t` and `SCOTCH_Num` via cmake and move the includes to the respective cpp files.

**Comment by garth-wells** [comment]
Or should we just copy the graph before passing to a partitioner? We could probably do something with C++17 to only copy if the types don't match.

**Comment by IgorBaratta** [comment]
> Or should we just copy the graph before passing to a partitioner? We could probably do something with C++17 to only copy if the types don't match.

That's a good point. I think both can be done. 
Depending on how you install scotch it also defines `idx_t`, and it can clash with `parmetis` definition, and building dolfinx can fail. For example, the default mode of scotch in spack builds a parmetis wrapper, with a different index size than parmetis.
