### ISSUE TITLE
Global geometry mapping to local index mapping acessing non-existing indices

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#1220]
In the `igi_to_vertex`-mapping in https://github.com/FEniCS/dolfinx/blob/master/cpp/dolfinx/io/xdmf_utils.cpp#L544-L546, indices not existing in the map is accessed when creating the local entity map. This does not cause an error, as calling an non-initialized key returns 0. 

This causes additional entries in the local_entities sent into a MeshTag, and can cause additional entries to be tagged in the 
`MeshTag` in parallel

**Comment by michalhabera** [comment]
Thanks a lot @jorgensd . Very good spot! The fact that std::map doesn't throw when it is accessed with a non-existing key is very dangerous. I have a hot-fix for this here https://github.com/FEniCS/dolfinx/tree/michal/mt-igi-invalid-access
The fix only prepares these received entities, for which all of their nodes are local to the reader.
