### ISSUE TITLE
Improve documentation of C++ pybindings

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#1236]
Currently, very few of the C++ functions exposed to pybind has any documentation.
As we do not want code duplication by adding a python layer on top of most of these bindings, we need to either:
1. Document all the exposed functions that does not have a python wrapper manually
2. Use tools such as https://github.com/pybind/pybind11_mkdoc

**Comment by garth-wells** [comment]
The original plan was to not expose the `cpp` module, and document classes and methods in the Python files. Cross-language documentation is too hard and too fragile, and we haven't been able to make a success of it in the past.

**Comment by garth-wells** [comment]
Closing as aim it to document in .py files.
