### ISSUE TITLE
Docker: conflicting libblas and libgfortran

### ISSUE THREAD

**Issue by blechta** [FEniCS/dolfinx#126]
[`pip3 install numpy scipy matplotlib` line in the Dockerfile](https://github.com/FEniCS/dolfinx/blob/202080585f8dc84a8eafd134e094cbbc7310a8a9/Dockerfile#L147) fetches binary build including `libgfortran` and `libblas`. PETSc is built with `libopenblas` from Ubuntu package. This can easily lead to disaster.

Correct solution is one of:

1. build OpenBLAS by ourselves (possibly let PETSc build it) and build NumPy, SciPy and matplotlib from source by `pip3 install --no-binary="numpy,matplotlib,scipy" numpy matplotlib scipy`,
2. install OpenBLAS as Ubuntu package and build Numpy and friends from source as above,
3. get everything from Ubuntu.

For example of 1. see https://github.com/blechta/tuc-fenics-recipes/blob/d101a3654d2584089f15d4518dd0e361a3ca30ed/build.sh#L86.

Trick for finding conflicts
```
PYTHON_SITE="$(python3 -c"import os, sys, site; sys.stdout.write(' '.join(site.getsitepackages()+[site.getusersitepackages()]+os.environ.get('PYTHONPATH', '').split(':')))")"
find $PYTHON_SITE -iname "*.so*" | xargs ldd | sed 's/ (0x.*//' | grep -v ':$' | sort | uniq
# go through the list manually to find suspicious entries
```

**Comment by jhale** [comment]
Agreed.

We've always used Debian/Ubuntu upstream packages for `numpy` and `scipy` in old FEniCS dev-env:

https://bitbucket.org/fenics-project/docker/src/master/dockerfiles/dev-env/Dockerfile

And never had an issue.

However, newer `pip` `matplotlib` is worth having. Does `matplotlib` really link with BLAS directly? Or just indirectly via `numpy`?

**Comment by blechta** [comment]
Not sure if 2. is possible. NumPy and friends use static linking to BLAS, see [here: `OPENBLAS="${FENICS_PREFIX}/lib/libopenblas.a"`](https://github.com/blechta/tuc-fenics-recipes/blob/d101a3654d2584089f15d4518dd0e361a3ca30ed/build.sh#L86).

**Comment by blechta** [comment]
I am not sure, maybe Matplotlib only links to Numpy dynamically, which is fine. But the binary install of Matplotlib tends to bring its own `libz` version: https://bitbucket.org/fenics-project/docker/issues/68/conflicting-versions-of-libz

**Comment by blechta** [comment]
It's not difficult to build NumPy, SciPy, matplotlib stack from source:
