### ISSUE TITLE
ARMv64 testing and builds

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#1263]
Requirements:

- ARM64 containers (test-env and dolfinx multi-arch x86-64/ARM64 builds).
- ARM64 CI.

Becomes urgent once Docker is ported to ARM Mac.

**Comment by jhale** [comment]
- [x]  ARM64 containers (test-env and dolfinx multi-arch x86-64/ARM64 builds).
- [ ] ARM64 CI.

The latter should be possible once GitHub offers a wider range of builders. Not enthusiastic about rolling out more GitHub self-hosted runner functionality than we already have (used in Docker image builds).

**Comment by jhale** [comment]
The ARM64 CI could be done easily now. But is it necessary? We couldn't have it run on every commit on a branch due to the cost of the BuildJet runners.

**Comment by garth-wells** [comment]
I'm not sure it's required. Is it likely to pick up issues that we don't already pick up?

**Comment by jhale** [comment]
Unlikely, in our experience the toolchains for ARM64 are very solid.
