### ISSUE TITLE
Move dolfin.has_foo() into dolfin.config.bar

### ISSUE THREAD

**Issue by blechta** [FEniCS/dolfinx#129]
`dolfin.has_foo()` is historically copying C++ interface. To make it fit current interface design goals it is required to

1. have it in a namespace, possibly `dolfin.config`, which also allows to remove `has_` prefix,
2. make it a property rather than a getter.

There are two immediate candidates for new names:

* boolean-valued `dolfin.config.complex_mode`,
* NumPy dtype-valued `dolfin.config.scalar_[d]type`.

**Comment by garth-wells** [comment]
`has_` makes sense in some contexts, e.g. presence of an optional dependency.

**Comment by blechta** [comment]
Consider this together with #125
