### ISSUE TITLE
Bump gmsh version

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#1328]
Currently, we are not using the latest release of gmsh due to the Eigen aligment issues, #1277 .
Once we have sorted this out, we should get on to the latest version of gmsh. 
With this, we should remove the download of gmsh binaries, and rather use `pip3`, as only the following is required to make gmsh installable with pip3 (tested using ubuntu:20.04 as base):
```
apt-get update
apt-get install libglu1 libxcursor-dev libxinerama1libxft2 python3-pip
pip3 install gmsh --user
export PATH=$PATH:/root/.local/bin
python3 -c "import gmsh; print(gmsh.__version__)"
```

**Comment by garth-wells** [comment]
See #1381.
