### ISSUE TITLE
Get all cell data from basix

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#1338]
Mostly this is done, but a small amount of hard coded data remains: https://github.com/FEniCS/dolfinx/blob/ba434b16ed56e74b80cf8b2cb1f19dddf236c007/cpp/dolfinx/mesh/cell_types.cpp#L126

**Comment by mscroggs** [comment]
We should also get `is_affine` directly from basix:
https://github.com/FEniCS/dolfinx/pull/1324#discussion_r560167489

**Comment by garth-wells** [comment]
@mscroggs is there more to do still?

**Comment by mscroggs** [comment]
I believe this is all done now
