### ISSUE TITLE
Generalise FiniteElement::evaluate_reference_basis_derivatives

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#1339]
Following the Basix PR, this is only implemented for first order derivatives.
https://github.com/FEniCS/dolfinx/blob/f6c4e33170b757e06bfe3360b3aba386dfbe1041/cpp/dolfinx/fem/FiniteElement.cpp#L158

**Comment by garth-wells** [comment]
Function no longer exists, so closing.
