### ISSUE TITLE
Remove geometry::node

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1352]
This is a left over from when topology and geometry were not cleanly separated. Not clear what this function does for some cell types or for high-order geometry.

It's still used a bit in the bounding box tree code.

**Comment by jorgensd** [comment]
So you would rather that one does the following:
```
const graph::AdjacencyList<std::int32_t>& x_dofs = geometry.dofmap();
const   Eigen::Array<double, Eigen::Dynamic, 3, Eigen::RowMajor>& geom_dofs =  mesh.geometry().x();
auto coords = x.row(x_dofs[n])
```
instead of
```
const graph::AdjacencyList<std::int32_t>& x_dofs = geometry.dofmap();
auto coords = geometry.node(x_dofs[n])
```
?

**Comment by garth-wells** [comment]
I think the former is better in the interests of 'one way to do something', and it avoids getting into the business of what is a 'node'.
