### ISSUE TITLE
Sparsity pattern has inconsistent IndexMap

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#1365]
After calling `SparsityPattern::assemble` new entries are inserted in the off-diagonal block, which do not have an entry in the IndexMap for columns, i.e. they have no global->local mapping.
This makes it difficult to use the SparsityPattern with local indexing.

Proposed solution would be to rebuild a correct column IndexMap after assemble.

**Comment by chrisrichardson** [comment]
https://github.com/FEniCS/dolfinx/compare/chris/sparsity-pattern

**Comment by jorgensd** [comment]
Was this resolved with #1372 ?

**Comment by chrisrichardson** [comment]
Row map is still a bit wrong, but not too important to fix.
