### ISSUE TITLE
transform_reference_basis_derivatives is unused or untested

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#1368]
[FiniteElement->transform_reference_basis_derivatives](https://github.com/FEniCS/dolfinx/blob/d603a56a0f07904e8a3680019874498f5fc2473f/cpp/dolfinx/fem/FiniteElement.cpp#L200) is not used anywhere. We should either remove it, or add a new test that uses it.

**Comment by mscroggs** [comment]
Having looked into this more, I think it is unlikely that `transform_reference_basis_derivatives` currently works. (although there's a change I broke something while wrapping it to python so I could test it)

**Comment by garth-wells** [comment]
Removing sounds good.

**Comment by mscroggs** [comment]
I'm in favour of removing then readding later. Given that it currently doesn't seem to do as expected, we're not losing anything by removing it for now

**Comment by garth-wells** [comment]
Function has been removed.
