### ISSUE TITLE
Writing function to XDMF file doesn't work

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#1377]
Somewhere between the current `master` and revision `7928b5636c5c89d72442830efe51bd11a24d5c59` the output to XDMF file of `Function` objects stopped working for my code. Meshes are written just fine, and the function headers make it to the `.xdmf` file, but the `.h5` file only contains a mesh.

**Comment by jorgensd** [comment]
Could you check if it works with the commit prior to https://github.com/FEniCS/dolfinx/commit/c14cb0aaceff9c4427b56020824ab4953c8d4921
i.e.
https://github.com/FEniCS/dolfinx/commit/f03a747ed93bdf3ff1b795553544a1e372ae91b4

**Comment by massimiliano-leoni** [comment]
It does! And it stops working at, c14cb0a, which is then the offending commit.

**Comment by massimiliano-leoni** [comment]
Fix confirmed, thanks!
