### ISSUE TITLE
Make discreteoperators backend agnostic

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#1385]
Calculating the discrete gradient operator could be more like assembly and take a `mat_set()` argument instead of hard-wiring Petsc.
Maybe split into two functions:

`la::SparsityPattern compute_discrete_gradient sparsity(V0, V1)`
`void assemble_discrete_gradient<T>(mat_set, V0, V1)`

**Comment by chrisrichardson** [comment]
This will be useful for testing Muelu Maxwell preconditioner

**Comment by jorgensd** [comment]
Closed with #1396
