### ISSUE TITLE
Re-implement higher order geometry

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#14]
From @chrisrichardson 

`MeshGeometry` needs some way to reference quadratic, cubic, etc. geometry, accessed cell-wise. Whilst it could be represented as a `Function` this places a circular dependency on `Mesh`.

A simplified dofmap (providing cellwise dofs on a Vector Lagrange basis) may be one option.

- [x] support for Mesh constructor with Tri_6 and Tet_10 topology in parallel
- [x] attach correct CoordinateMapping object to Mesh and check it matches with Mesh
- [x] figure out the ordering for points on edges, faces, cells etc. (currently using VTK ordering as in XDMF)
   - gmsh has a complete scheme for any order Lagrange...
- [x] consider adding a mapping for vertices too.

**Comment by garth-wells** [comment]
@chrisrichardson can some of the checkboxes above be ticked off now?

**Comment by chrisrichardson** [comment]
Closing, as there is now higher-order support, and there are new issues around dof ordering/permutation, that need addressing elsewhere.
