### ISSUE TITLE
New numpy release requires Python 3.7

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#1400]
It is probably sensible to increase the minimal Python version to 3.7 and ensure that a high enough version is used in the docker image

**Comment by jorgensd** [comment]
Currently the bump to 1.20 only shows some deprecation warnings, so I guess we dont need to bump the minimum requirement yet.
However, this raises the question of if we should upgrade scipy in our docker images with pip, as we already do it with numpy, and will end up with a mismatch of versions.
