### ISSUE TITLE
Add lightweight span2d class

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1409]
It would be helpful to have a simple and lightweight `span2d` class, similar to `span`. This would avoid the need for some copies and allow 1D objects, e.g. `std::vector` to be wrapped up as 2D arrays for convenience.

**Comment by IgorBaratta** [comment]
There is a proposal for an `mdspan` but I don't think it's gonna land soon, and it's not lightweight.
https://github.com/kokkos/mdspan

I think we can have a `span2d` similar to `array2d` with a span instead of vector as the "storage".
