### ISSUE TITLE
Avoid resizing in for-loops in permutationcomptations.cpp

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#1415]
Currently, permutationcomputations.cpp contains alot of resizing inside nested for-loops, such as: https://github.com/FEniCS/dolfinx/blob/master/cpp/dolfinx/mesh/permutationcomputation.cpp#L41
This resizing will become expensive if we extend FEniCS-X to mixed meshes (currently the resizing does nothing), and should be precomputed outside for-loops, creating a vector of size (max_num_elements_in_adjacency_node) locally.

**Comment by garth-wells** [comment]
Do you mean `mesh::create_entity_permutations`? This is something of a 'meta' call in that it creates the entities if they don't exist and then computed the permutations. You need to check which step is the costly one.

**Comment by jorgensd** [comment]
I do, I'll get to that once we have found the regression issue in `assemble_vector`

**Comment by garth-wells** [comment]
I think the resize calls here involve negligible overhead - memory allocation will only be triggered when the container needs to grow.
