### ISSUE TITLE
MixedLinearVariationalSolver.cpp:240:23: error: variable ‘dolfin::PETScNestMatrix A’ has initializer but incomplete type

### ISSUE THREAD

**Issue by ArvinShaffer** [FEniCS/dolfinx#1430]
make error

MixedLinearVariationalSolver.cpp:240:23: error: variable ‘dolfin::PETScNestMatrix A’ has initializer but incomplete type
   PETScNestMatrix A(As);

**Comment by jorgensd** [comment]
Please supply a minimal code example that reproduces the error

**Comment by garth-wells** [comment]
`MixedLinearVariationalSolver.cpp` isn't a file in the DOLFINX source.

**Comment by ArvinShaffer** [comment]
> Please supply a minimal code example that reproduces the error

i have find this about it. but i try mpi4.1.1, it is also have this error

**Comment by ArvinShaffer** [comment]
> Please supply a minimal code example that reproduces the error
i just follow the step of this guide , and my system is ubuntu 20.04

https://fenics.readthedocs.io/en/latest/installation.html#from-source

## Development version
The FEniCS source code can be found on the FEniCS Bitbucket pages and the FEniCS Github pages. To download and build current development version run the following commands:
```
git clone https://github.com/FEniCS/fiat.git
git clone https://bitbucket.org/fenics-project/dijitso
git clone https://github.com/FEniCS/ufl.git
git clone https://bitbucket.org/fenics-project/ffc
git clone https://bitbucket.org/fenics-project/dolfin
git clone https://bitbucket.org/fenics-project/mshr
cd fiat    && pip3 install . && cd ..
cd dijitso && pip3 install . && cd ..
cd ufl     && pip3 install . && cd ..
cd ffc     && pip3 install . && cd ..
mkdir dolfin/build && cd dolfin/build && cmake .. && make install && cd ../..
mkdir mshr/build   && cd mshr/build   && cmake .. && make install && cd ../..
cd dolfin/python && pip3 install . && cd ../..
cd mshr/python   && pip3 install . && cd ../..
```

**Comment by jorgensd** [comment]
You are using `dolfin` (the stable release of the FEniCS project). This is the dolfin-x (development version of FEniCS), and I would suggest making a post at: https://fenicsproject.discourse.group/
Note that you need the dependencies listed at: https://fenicsproject.org/olddocs/dolfin/dev/python/installation.html
