### ISSUE TITLE
compiling create_form can't tell difference between map and vector if empty.

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#1485]
```
auto a = std::make_shared<
      dolfinx::fem::Form<PetscScalar>>(dolfinx::fem::create_form<PetscScalar>(
      *form_Poisson_a, {V, V}, {}, {}, {}));
```
currently won't compile, because the signature of create_form has either map or vector for arguments 3 and 4.

**Comment by garth-wells** [comment]
Above won't work in any case because initialiser lists can't be used with `std::make_shared`.
