### ISSUE TITLE
Failure to assemble DG on internal facets 

### ISSUE THREAD

**Issue by kumiori** [FEniCS/dolfinx#1504]
Hello all,
I am trying to solve a biharmonic equation using DG elements, as done e.g. in [fenics-shells](https://fenics-shells.readthedocs.io/en/latest/demo/kirchhoff-love-clamped/demo_kirchhoff-love-clamped.py.html).

However, I fail to correctly assemble terms on interior facets as ffcx retuns an `error: redefinition of ‘w0_r0_d01’` for terms associated to the tensor `M = grad(grad(w))` restricted to interior facets, where `w` is the primal unknown. Note that assembly of restricted `grad(w)` terms works correctly and the issue just seems to be a repeated line in the `libffcx_forms_###.c` file. 

Here's a snippet which produces the error and here is attached is the [full log](https://github.com/FEniCS/dolfinx/files/6336471/fail.log) (Ran on a dolfinx/dolfinx docker image).
 

Any thoughts for a solution?

```python
import dolfinx
import ufl
from mpi4py import MPI

from dolfinx.fem import assemble, assemble_matrix, assemble_scalar, assemble_vector
from ufl import inner, avg, jump, derivative, dot, grad, tr, diff, outer, CellDiameter
from ufl import variable

def test_assembly():
    mesh = dolfinx.generation.RectangleMesh(
        MPI.COMM_WORLD, [[0.0, 0.0, 0.0], [1, 0.1, 0.0]], [10, 2]
    )

    dS = ufl.Measure("dS", domain=mesh)

    elem = ufl.FiniteElement("Lagrange", mesh.ufl_cell(), degree=2)
    W = dolfinx.FunctionSpace(mesh, elem)
    w_ = dolfinx.Function(W)

    theta = grad(w_)

    n = ufl.FacetNormal(mesh)
    M = sym(grad(theta))
    M_nn = inner(M, outer(n, n))

    # the following are OK

    assemble_scalar(avg(dot(theta, n))*dS)
    assemble_scalar(jump(dot(theta, n))*dS)

    # these fail
    assemble_scalar(M_nn('+')*dS)
    assemble_scalar(M_nn('-')*dS)
    assemble_scalar(avg(M_nn)*dS)


if __name__ == '__main__':
    test_assembly()
```

**Comment by michalhabera** [comment]
Hi @kumiori , thanks for reporting this. Seems more like an issue in FFCx, I'll have a look.

**Comment by michalhabera** [comment]
Sorry for a delayed response, @kumiori . Can you now confirm this is resolved with `ffcx/main`?

**Comment by kumiori** [comment]
Hi @michalhabera, it indeed works now.
Thanks for the fix.
