### ISSUE TITLE
ARM64 Docker issues

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#1507]
- [x] Linking issue with ARM64/PETSc/OpenMPI: https://github.com/FEniCS/dolfinx/runs/2380975354?check_suite_focus=true#step:4:7472
- [ ] Everything is -O2. Per architecture optimisations for end-user images. amd64 -> sandybridge. arm64 -> armv8.2-a suggested.
- [x] No gmsh binaries for arm64.
- [ ] No vtk (pyvista) wheels for arm64.

**Comment by garth-wells** [comment]
@jhale can this be closed now?
