### ISSUE TITLE
Support easy switching to 64-bit indexing in Docker container?

### ISSUE THREAD

**Issue by godsic** [FEniCS/dolfinx#1508]
The `Docker` container includes `PETSc` with 64-bit indexing support, but not `dolfinx`. 

Are there any plans for providing separate container with full 64-bit indexing support?

**Comment by IgorBaratta** [comment]
Dolfinx uses 32-bit integers for local indices (local to a process) and 64-bit  for global indices.
I don't think it's possible to use 64-bit for both local and global indexing.

In any case, the maximum value for a 32-bit integer is 2,147,483,647, which is the maximum number of entities in a single process. But that does not limit the size of the problem in parallel.

**Comment by jhale** [comment]
@IgorBaratta Not sure about that, I think the global size in PETSc is limited by the indexing. Above ~2 billion you need 64-bit indices enabled.

Regarding the images, there are no plans because we consider it a niche use case for the types of systems where containers are used (laptops and workstations).

Having said that, if you are comfortable writing your own `Dockerfile` you can build your own container with 64-bit PETSc enabled.

Something like:
`
FROM fenicsproject/dev-env

ARG CMAKE_BUILD_TYPE="Release"
ARG CXXFLAGS="-march=native"
ARG PIP_EXTRA_FLAGS=""

ENV PETSC_DIR=/usr/local/petsc
ENV PETSC_ARCH=linux-gnu-real-64

WORKDIR /src
ADD basix/ /src/basix
ADD ufl/ /src/ufl
ADD ffcx/ /src/ffcx
ADD dolfinx/ /src/dolfinx

RUN cd basix && cmake -G Ninja -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -B build-dir -S . && \
    cmake --build build-dir && \
    cmake --install build-dir && \
    python3 -m pip install ./python && \
    cd ../ufl && python3 -m pip install . && \
    cd ../ffcx && python3 -m pip install .

RUN cd dolfinx && \
    mkdir build && \
    cd build && \
    cmake -G Ninja -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_CXX_FLAGS=${CXXFLAGS} ../cpp && \
    ninja install && \
    cd ../python && \
    CXXFLAGS=${CXXFLAGS} python3 -m pip -v install --global-option build ${PIP_EXTRA_FLAGS} .
`

Checkout all FEniCS sources into directory containing the above the `Dockerfile . Build with:

`
docker pull fenicsproject/dev-env
docker build .
`

**Comment by godsic** [comment]
@IgorBaratta @jhale Thanks for the clarification. I guess the 2B limit applies to DoFs indexing, so is there an idiomatic way to get number of DoFs of `FunctionSpace` in `dolfinx`?

**Comment by IgorBaratta** [comment]
> @IgorBaratta Not sure about that, I think the global size in PETSc is limited by the indexing. Above ~2 billion you need 64-bit indices enabled.

I meant that dolfinx always uses 64 bit for global indices, even when PETSc does not.  
I think I misunderstood the question.  But luckily we have your answer to help.



> @IgorBaratta @jhale Thanks for the clarification. I guess the 2B limit applies to DoFs indexing, so is there an idiomatic way to get number of DoFs of `FunctionSpace` in `dolfinx`?

Are you using C++ or python?

**Comment by godsic** [comment]
@IgorBaratta python

**Comment by IgorBaratta** [comment]
```python
print(f"Global number of dofs {V.dofmap.index_map_bs * V.dofmap.index_map.size_global}")
```

> @IgorBaratta python

**Comment by godsic** [comment]
@IgorBaratta @jhale So I am trying to solve on `VectorFunctionSpace` with `84812460` DoFs and getting:
```python
  File "/usr/local/dolfinx-real/lib/python3.8/dist-packages/dolfinx/fem/assemble.py", line 60, in create_matrix
    return cpp.fem.create_matrix(_create_cpp_form(a))
RuntimeError: Failed to successfully call PETSc function 'MatXIJSetPreallocation'. PETSc error code is: 63, Argument out of range
```
I had the same issue with `fenics`.

**Comment by jorgensd** [comment]
Please add a MWE, as this might not be related to the number of dofs, but other parts of your code.

**Comment by godsic** [comment]
@jorgensd I will do the MWE, but making coarser mesh down to `5423130` DoFs avoids the problem.

**Comment by godsic** [comment]
@jorgensd Here comes the MWE
```python
import dolfinx
import ufl
from mpi4py import MPI

mesh = dolfinx.UnitCubeMesh(MPI.COMM_WORLD, 128, 64, 64)

print(
    f"Global number of cells {mesh.topology.index_map(mesh.topology.dim).size_global}")

V = dolfinx.FunctionSpace(mesh, ("P", 2))
u = dolfinx.Function(V)

V_vec = dolfinx.VectorFunctionSpace(mesh, ("DG", 2))
print(
    f"Global number of dofs in vector space {V_vec.dofmap.index_map_bs * V_vec.dofmap.index_map.size_global}")

dx = ufl.dx(mesh)

p = ufl.TrialFunction(V_vec)
q = ufl.TestFunction(V_vec)

a = ufl.inner(p, q) * dx
L = ufl.inner(ufl.grad(u), q) * dx

projection = dolfinx.fem.LinearProblem(a, L)

grad_u = projection.solve()
```
A few notes
- mesh with `(64, 64, 64)` cells does not trigger the issue;
- running with `mpirun -np 2` does not trigger the issue, consistent with @IgorBaratta explanation.

**Comment by jorgensd** [comment]
> @jorgensd Here comes the MWE
> 
> ```python
> 
> import dolfinx
> 
> import ufl
> 
> from mpi4py import MPI
> 
> 
> 
> mesh = dolfinx.UnitCubeMesh(MPI.COMM_WORLD, 128, 64, 64)
> 
> 
> 
> print(
> 
>     f"Global number of cells {mesh.topology.index_map(mesh.topology.dim).size_global}")
> 
> 
> 
> V = dolfinx.FunctionSpace(mesh, ("P", 2))
> 
> u = dolfinx.Function(V)
> 
> 
> 
> V_vec = dolfinx.VectorFunctionSpace(mesh, ("DG", 2))
> 
> print(
> 
>     f"Global number of dofs in vector space {V_vec.dofmap.index_map_bs * V_vec.dofmap.index_map.size_global}")
> 
> 
> 
> dx = ufl.dx(mesh)
> 
> 
> 
> p = ufl.TrialFunction(V_vec)
> 
> q = ufl.TestFunction(V_vec)
> 
> 
> 
> a = ufl.inner(p, q) * dx
> 
> L = ufl.inner(ufl.grad(u), q) * dx
> 
> 
> 
> projection = dolfinx.fem.LinearProblem(a, L)
> 
> 
> 
> grad_u = projection.solve()
> 
> ```
> 
> A few notes
> 
> - mesh with `(64, 64, 64)` cells does not trigger the issue;
> 
> - running with `mpirun -np 2` does not trigger the issue, consistent with @IgorBaratta explanation.

As Igor and Jack has said, if you either run it in parallel, or build petsc with 64bit support, the error should disappear.
