### ISSUE TITLE
Is it still possible to evalute `Function` in parallel?

### ISSUE THREAD

**Issue by godsic** [FEniCS/dolfinx#1522]
I am trying to do something like
```python
pts = np.vstack(np.meshgrid(xx, yy, [z])).reshape(3, -1).T
cell_candidates = [dolfinx.geometry.compute_collisions_point(tree, p) for p in pts]
cells = dolfinx.cpp.geometry.select_colliding_cells( mesh, cell_candidates, pts, len(cell_candidates))
q_vals = Q.eval(pts, cells)
```
but current API does not seem to allow it. 

So, is parallel evaluation of `Function` still possible?

**Comment by jorgensd** [comment]
Have a look at: https://jorgensd.github.io/dolfinx-tutorial/chapter1/membrane_code.html#making-curve-plots-throughout-the-domain
