### ISSUE TITLE
AttributeError for "NewtonSolver.error_on_nonconvergence" on Python Interface

### ISSUE THREAD

**Issue by RuruX** [FEniCS/dolfinx#1541]
Hi guys,

I was following the [test_newton.py](https://github.com/FEniCS/dolfinx/blob/main/python/test/unit/nls/test_newton.py) to use the `NewtonSolver` object in the `dolfinx.cpp.nls` module as the nonlinear solver for my research problem. And there seems to be some obvious error in binding the attributes of the `NewtonSolver` to the Python interface, which resulted in an AttributeError when I tried to modify the boolean parameter [`NewtonSolver::error_on_nonconvergence`](https://github.com/FEniCS/dolfinx/blob/434dd45172ae523f47fb01d35d93220530d33ba6/cpp/dolfinx/nls/NewtonSolver.h#L122) to `False`. 

And I was able to fix it with one-line addition to the pybind11 wrapper of the NewtonSolver object on my local computer, i.e. by adding this line to the end of the [`nls(py::module& m)`](https://github.com/FEniCS/dolfinx/blob/434dd45172ae523f47fb01d35d93220530d33ba6/python/dolfinx/wrappers/nls.cpp#L21) function
```
.def_readwrite("error_on_nonconvergence",   
&dolfinx::nls::NewtonSolver::error_on_nonconvergence)
```
And the same issue for another Boolean parameter [`NewtonSolver::record`](https://github.com/FEniCS/dolfinx/blob/434dd45172ae523f47fb01d35d93220530d33ba6/cpp/dolfinx/nls/NewtonSolver.h#L119).

**Comment by jorgensd** [comment]
Feel free to add a pull request with these two options exposed in the nls module, as I see no issue with exposing them.
