### ISSUE TITLE
Support multistage solvers

### ISSUE THREAD

**Issue by Tomaubier** [FEniCS/dolfinx#1548]
Add support for multistage solvers in the same way as in this demo for dolfin:
https://bitbucket.org/fenics-project/dolfin/src/cd74a78b04333eaf66be9d43a74d58a63ffe0973/python/demo/undocumented/multistage-solver/demo_multistage-solver.py?at=master

**Comment by jorgensd** [comment]
If anyone wants to take on the task of doing this, I suggest we try to use irksome (https://github.com/firedrakeproject/Irksome), as it contains a large variety of schemes.
