### ISSUE TITLE
Force reading mesh as 2D

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#159]
Since `gmsh` produces only 3D embedded meshes, it would help if dolfin mesh io has parameter/argument to force reading mesh as if geometrical dimension == 2. It can be done by throwing last component out.

Typical problematic scenerio:
1. Create nice planar mesh in `gmsh`, convert to `.msh`
2. Convert `.msh` to `.xdmf` using `meshio`.
3. Read `.xdmf` to dolfin. At this step mesh in dolfin has always gdim == 3. Any vector/tensor computation becomes suboptimal on such mesh.

See also https://bitbucket.org/fenics-project/dolfin/issues/1023/read-2d-mesh-from-xdmffile

**Comment by chrisrichardson** [comment]
Can't this be fixed in `meshio`?

**Comment by michalhabera** [comment]
Yes, it could be fixed in any third party code thats strips z-component away.

The question is if to take the responsibility or pass it. I can make issue in `meshio` to see if they like it.

**Comment by michalhabera** [comment]
Fixed in meshio, https://github.com/nschloe/meshio/pull/301
