### ISSUE TITLE
BDM VectorElement assembly fails on current main

### ISSUE THREAD

**Issue by jmv2009** [FEniCS/dolfinx#1593]
The following code fails with the current version of dolfinx:

```
import dolfinx
import ufl
from dolfinx import FunctionSpace, UnitSquareMesh
from dolfinx.cpp.mesh import CellType
from mpi4py import MPI
from ufl import VectorElement, FiniteElement, TrialFunction,TestFunction, inner, dx

mesh=UnitSquareMesh(MPI.COMM_WORLD,4,4,CellType.triangle)
BDM=FunctionSpace(mesh,VectorElement("BDM",mesh.ufl_cell(),1))
us=TrialFunction(BDM)
vs=TestFunction(BDM)
a=inner(us,vs)*dx
A = dolfinx.fem.assemble_matrix(a, [])
print("finish")
```

```
double free or corruption (!prev)
zsh: abort      python3 tst2.py
```

What works:
replace: VectorElement -> FiniteElement
or
replace: BDM -> Lagrange

OS version: Kali rolling
Initial installation: sudo apt install python3-dolfinx
Updates: ufl, basix, tsfc, dolfinx: master
Note: This issue does not appear without updating to master.

**Comment by jorgensd** [comment]
I am not sure having a vector-[BDM element](https://defelement.com/elements/brezzi-douglas-marini.html) makes sense as it already contains integral moments. What do you think @mscroggs ?

**Comment by jmv2009** [comment]
Trying to build the equivalent of this:

```
from ufl import *
from dolfin import *
from vedo.dolfin import plot
mesh=UnitCubeMesh(4,4,4)
BDM=VectorElement("N2F",mesh.ufl_cell(),1)
DG=VectorElement("DG",mesh.ufl_cell(),0)
W=FunctionSpace(mesh,MixedElement(BDM,DG,DG))
(us,ux,ur)=TrialFunctions(W)
(vs,vx,vr)=TestFunctions(W)
young=2.
nu=0.3
mu=young/2/(1+nu)
lambd=young*nu/(1+nu)/(1-2*nu)
mu1= 0.5/mu;
lambda1 = -mu1*lambd/(3*lambd+2*mu);
perm=Constant((((0,0,0),(0,0,1),(0,-1,0)),((0,0,-1),(0,0,0),(1,0,0)),((0,1,0),(-1,0,0),(0,0,0))))
#perm=PermutationSymbol(3)  # for firedrake
a=inner(mu1*us+lambda1*tr(us)*Identity(3),vs)+dot(ux,div(vs))+dot(div(us),vx)+inner(us,dot(perm,vr))+inner(dot(perm,ur),vs)
L=dot(Constant((0.1,0.,0.5)),vx)
def boundary(x):
    return x[0]<DOLFIN_EPS or x[1]<DOLFIN_EPS or x[2]<DOLFIN_EPS or x[0]>1-DOLFIN_EPS or x[1]>1-DOLFIN_EPS
bc=DirichletBC(W.sub(0),Constant(((0.,0.,0.),(0.,0.,0.),(0.,0.,0.))), boundary)
w=Function(W)
solve(a*dx==L*dx,w,bc)
(rs,rx,rr)=w.split()
plot(rx,mode='displacement')
```

which is similar to this:
https://cpb-us-w2.wpmucdn.com/sites.baylor.edu/dist/6/32/files/2015/01/RognesKirbyEtAl2008a-11h7d4e.pdf (edited)

**Comment by jorgensd** [comment]
This seems similar to: https://fenicsproject.org/qa/13668/error-assembling-form-with-bdm-function/
I guess you can use the same workaround, i.e.:
```
BDM=FiniteElement("N2F",mesh.ufl_cell(),1)
DG=VectorElement("DG",mesh.ufl_cell(),0)
W=FunctionSpace(mesh,MixedElement(BDM, BDM, BDM, DG,DG))
```

**Comment by mscroggs** [comment]
Yes, MixedElement should be used instead of VectorElement as VectorElement assumes that its subelement is scalar. In https://github.com/FEniCS/ffcx/pull/429, I've made FFCx throw an error when trying to create this element rather than letting it reach a segfault
