### ISSUE TITLE
IndexMap computes wrong connectivity in parallel

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#1596]
I just realised something funny is happening in a piece of code that I am writing, and it seems to boil down to the issue in the title.
Consider the following example in which I just read a mesh from file and print the coordinates of the vertexes connected to cell number 12:

```
#include <dolfinx.h>
#include <dolfinx/common/log.h>
#include <dolfinx/io/XDMFFile.h>

using namespace dolfinx;

int main(int argc, char *argv[])
{
  common::subsystem::init_logging(argc, argv);
  common::subsystem::init_petsc(argc, argv);

  // Set the logging thread name to show the process rank
  int mpi_rank;
  MPI_Comm_rank(MPI_COMM_WORLD, &mpi_rank);
  std::string thread_name = "RANK " + std::to_string(mpi_rank);
  loguru::set_thread_name(thread_name.c_str());
  loguru::g_stderr_verbosity = loguru::Verbosity_INFO;

  // read mesh file
  const std::string mesh_fileL = "Left.xdmf";

  io::XDMFFile meshFileL(MPI_COMM_WORLD, mesh_fileL, "r");
  auto meshL = std::make_shared<mesh::Mesh>(
      meshFileL.read_mesh(fem::CoordinateElement(mesh::CellType::tetrahedron, 1),
                          mesh::GhostMode::shared_facet,
                          "Grid"));

  // extract connectivity from cells to vertexes
  auto connectivity = meshL->topology().connectivity(3, 0);
  // get the indexes of the vertexes connected to cell number 12
  auto v = connectivity->links(12);
  // get the mesh geometry
  auto xl = meshL->geometry().x();

  // get the coordinates of the vertexes connected to cell number 12
  auto x1 = xl[3 * v[0]];
  auto y1 = xl[3 * v[0] + 1];
  auto z1 = xl[3 * v[0] + 2];
  auto x2 = xl[3 * v[1]];
  auto y2 = xl[3 * v[1] + 1];
  auto z2 = xl[3 * v[1] + 2];
  auto x3 = xl[3 * v[2]];
  auto y3 = xl[3 * v[2] + 1];
  auto z3 = xl[3 * v[2] + 2];
  auto x4 = xl[3 * v[3]];
  auto y4 = xl[3 * v[3] + 1];
  auto z4 = xl[3 * v[3] + 2];

  // print these coordinates
  LOG(INFO) << x1 << ", " << y1 << ", " << z1;
  LOG(INFO) << x2 << ", " << y2 << ", " << z2;
  LOG(INFO) << x3 << ", " << y3 << ", " << z3;
  LOG(INFO) << x4 << ", " << y4 << ", " << z4;

  common::subsystem::finalize_petsc();

  return 0;
}
```

When I run this example with 8 processes, rank 3 prints the following output

```
2021-06-29 18:03:01.338 (   0.436s) [RANK 3          ]      interpolation.cpp:54    INFO| 1, 0.933925, 0.518063
2021-06-29 18:03:01.338 (   0.436s) [RANK 3          ]      interpolation.cpp:55    INFO| 1, 0.868231, 0.53542
2021-06-29 18:03:01.338 (   0.436s) [RANK 3          ]      interpolation.cpp:56    INFO| 1, 0.865191, 0.440768
2021-06-29 18:03:01.338 (   0.436s) [RANK 3          ]      interpolation.cpp:57    INFO| 1, 0.796291, 0.459681
```
Where you can see that the four points connected to cell 12 on rank 3 all have x = 1, which is wrong as they can't be corners of a tetrahedron.
Those four points are, in fact, actual points of the mesh, but they don't belong to the same cell.
You can get the mesh from [here](https://drive.google.com/file/d/1mveuNO0R3v3DJFgpGFHx0jBvG7rblXv6/view?usp=sharing) .

Everything seems to be correct when running in serial.

**Comment by garth-wells** [comment]
You're using the topology connectivity to access the geometry; you need to use the geometry dofmap (https://github.com/FEniCS/dolfinx/blob/0ef02881282f75a9af2a6f2fea9283a1ff862ec6/cpp/dolfinx/mesh/Geometry.h#L81). Can you test using the geometry dofmap?

**Comment by massimiliano-leoni** [comment]
It seems you hit the nail on the head, Garth :D 
Now it appears to work as expected, thanks a lot for that!

Just out of curiosity, why are there two connectivities? What is the difference between the topology connectivity and the geometry dofmap?

**Comment by garth-wells** [comment]
The topology and geometry are separated to give more flexibility in how geometry is handled, e.g. for high-order geometries.

**Comment by massimiliano-leoni** [comment]
I understand! Even then, don't they hold the same data? Or perhaps not when running in parallel?
