### ISSUE TITLE
Invalid read reported by Valgrind

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#1597]
I noticed Valgrind complains about an invalid read at `Mesh.cpp:109`, which reads

```
  xtl::span<const std::int64_t>(
    cells_extracted0.array().data(),
    cells_extracted0.offsets()[num_owned_cells + 1]),
```
reading `num_owned_cells + 1` values from `offsets`, which Valgrind reports was allocated at `AdjacencyList.h:210`, which reads

```
  std::vector<std::int32_t> offsets(data.size() / degree + 1, 0);
```

Changing `num_owned_cells + 1` to `num_owned_cells` in `Mesh.cpp` removes the error, so they seem to be connected, but the correct solution to the problem is likely something else.

**Comment by garth-wells** [comment]
Thanks - from a first look I think `num_owned_cells + 1` should be just `num_owned_cells`.
