### ISSUE TITLE
Support assembly of nested matrices

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#16]
New assembler should be simple and preserve symmetry. It should also be flexible in the ways boundary conditions can be applied.

Task list:  
- [x]  Assemble M x N matrices with m x n block, where each block is a form
- [x] Support assembling of block matrix into the PETSc monolithic and `MatNest` formats
- [x] Support cell integrals
- [x] Support exterior facet integrals
- [x] Support interior facet integrals
- [x] Support multiple domains (different integrals)
- [x] Improve efficiency of boundary condition look-ups
- [x] Avoid exposing any UFC objects - pass function pointers if necessary
- [x] Add support for assembly of scalars (functionals)

**Comment by nate-sime** [comment]
Is there a plan for assembly of scalars? Should it be included in the new Assembler class?

**Comment by garth-wells** [comment]
Scalars definitely need to be supported. Vectors only should just be a small tweak of what is already in the new assembler.

**Comment by nate-sime** [comment]
I agree.

I propose vector assembly would be through the new Assembler interface with `a = NULL` or empty.

Would a `ScalarAssembler` class be appropriate? Or should scalar assembly be included in the new `Assembler` somehow?

**Comment by garth-wells** [comment]
@nate-sime If you're up for it, I would suggest starting with a static function `fem::Assembler::assemble(M)` where `M` is a functional (`Form`). We can see later if it should be moved.

**Comment by meg-simula** [comment]
That was a quick assignment ;-)

**Comment by garth-wells** [comment]
Accidental click, but feel free to re-assign yourself!

**Comment by meg-simula** [comment]
I'll check back in 6 months to see if it is still open :-)

--
Marie

**Comment by francesco-ballarin** [comment]
Hi everybody,
as I mentioned to some of you via email I would like to point out the repository
https://github.com/mathLab/multiphenics
where a few months ago we implemented the first two items ("Assemble M x N matrices with m x n block, where each block is a form" and "Support assembling of block matrix into the PETSc monolithic") for the old dolfin interface. Feel free to let me know if you believe that some parts of that work might be useful here.

Best regards,
Francesco Ballarin

**Comment by chrisrichardson** [comment]
Is this now complete? 
Assembly over domains, and over interior facets is by now supported, I think.
