### ISSUE TITLE
PointSource command in Dolfin-X

### ISSUE THREAD

**Issue by samuelpgroth** [FEniCS/dolfinx#163]
The PointSource command appears to be removed in DOLFIN-X. Is there any plan to put it back in?

**Comment by michalhabera** [comment]
See https://github.com/FEniCS/dolfinx/issues/28 It is marked as "good first issue" which means it is a great opportunity to try implement it yourself ;)

**Comment by chrisrichardson** [comment]
Sorry @samuelpgroth - I forgot I already made this issue!
