### ISSUE TITLE
Timoshenko beam elements

### ISSUE THREAD

**Issue by j8asic** [FEniCS/dolfinx#1667]
Does dolfinx support 1D beam elements (Timoshenko, or at least Euler-Bernoulli) in 3D space? And how?

**Comment by mscroggs** [comment]
I don't believe we have these in DOLFINx yet, unless I know them under a different name (and with a very different derivation as I don't recognise what I read in https://www.sciencedirect.com/science/article/pii/0022460X72904579)

**Comment by j8asic** [comment]
Thanks for the reply @mscroggs. Please find a bending test of Timoshenko beam with some issues reported here: #1673 
What do you think, is this implementation appropriate? I am getting okay mode shapes, but wrong eigenfrequencies

**Comment by j8asic** [comment]
I've upload the validation code here: https://github.com/j8asic/jellybeam/blob/main/validation.py
This is a 2D bending problem of a free-free beam, but I will also add coupled twisting and lateral vibrations.

**Comment by IgorBaratta** [comment]
> Thanks for the reply @mscroggs. Please find a bending test of Timoshenko beam with some issues reported here: #1673
> What do you think, is this implementation appropriate? I am getting okay mode shapes, but wrong eigenfrequencies

Is this fixed? or are you still getting wrong eigenfrequencies?

**Comment by j8asic** [comment]
Fixed and validated using the above code. (This is only vertical bending. Coupled modes are still needed)
