### ISSUE TITLE
Regression in form involving both ("+") and ("-") restriction

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#1708]
I use a lot of forms like these in FEniCS-Shells and I noticed a regression on a problem that was previously working. This is my attempt at producing a MWE and finding a previous set of commits that works. 

The form involves an edge integral of the tangential component of the gradient of a P1 function and the tangential component of an N1curl function.

```
from mpi4py import MPI

import dolfinx
from dolfinx import UnitSquareMesh, Function, FunctionSpace
from dolfinx.cpp.mesh import CellType
from dolfinx.fem import assemble_matrix

import ufl
from ufl import FiniteElement, MixedElement
from ufl import grad, inner

# N = 1 # Works.
N = 2 # Doesn't work
mesh = UnitSquareMesh(MPI.COMM_WORLD, N, N, CellType.triangle,
                      dolfinx.cpp.mesh.GhostMode.shared_facet)

U_el = MixedElement([FiniteElement("Lagrange", ufl.triangle, 1),
                     FiniteElement("N1curl", ufl.triangle, 1)])
U = FunctionSpace(mesh, U_el)

u, p = ufl.TrialFunctions(U)
v, q = ufl.TestFunctions(U)

dSp = ufl.Measure('dS', metadata={'quadrature_degree': 1})
dsp = ufl.Measure('ds', metadata={'quadrature_degree': 1})

n = ufl.FacetNormal(mesh)
t = ufl.as_vector((-n[1], n[0]))

def inner_e(x, y): return (inner(x, t)*inner(y, t))("-")*dSp + (inner(x, t)*inner(y, t))("+")*dSp # Doesn't work for N = 2
#def inner_e(x, y): return (inner(x, t)*inner(y, t))("+")*dSp # Works
#def inner_e(x, y): return (inner(x, t)*inner(y, t))("-")*dSp # Works

a = inner_e(grad(u), q) + inner_e(grad(v), p)

A = dolfinx.fem.assemble_matrix(a)
A.assemble()
print(A.norm())
```

Built inside the latest dev-env container using the following commits:

```
basix: e7ff5c1d08 (early May)
dolfinx: 732ff7f953 (early May)
ffcx: 60739ccc (early May)
ufl: 94badf86983 (current main)
```

I get

```
19.595917942265423
```

On current `main` I get:

```
16.73320053068151
```

This was also the case around ~4 weeks ago prior to my holiday so the recent changes have not caused this issue. It is interesting that the forms including only the positive or negative restriction both work. Note also that the N = 1 case works for all three forms.

**Comment by jhale** [comment]
I've narrowed this down to a set of commits on 18th June 2020 @mscroggs @garth-wells 

DOLFINx:
https://github.com/FEniCS/dolfinx/tree/98b30a32e9dabfe60e43568f0ff7f29edb8e8c37
https://github.com/FEniCS/dolfinx/tree/d316ef77c58883f09d0e68486aa1caa24a10f6ec

FFCx:
https://github.com/FEniCS/ffcx/tree/df0284bff25dc53e4f12c5feaee9034718df1c07

**Comment by mscroggs** [comment]
I'm currently looking into this to see if taking the DOF transformations outside the kernel caused an issue. So far, I've turned your MWE into a test: https://github.com/FEniCS/dolfinx/blob/444da1a75a6ae0d663c40aa84e827a621ed6809b/python/test/unit/fem/test_plus_minus.py

**Comment by mscroggs** [comment]
Are you sure this was correct previously? I assembled the form using all three of these:
```python
def inner_e1(x, y): return (inner(x, t)*inner(y, t))("-")*dSp + (inner(x, t)*inner(y, t))("+")*dSp # Doesn't work for N = 2
def inner_e2(x, y): return (inner(x, t)*inner(y, t))("+")*dSp # Works
def inner_e3(x, y): return (inner(x, t)*inner(y, t))("-")*dSp # Works
```
And the resulting matrices satisfy `result1 == result2 + result3`, so if the latter two work, it looks like the first one ought to be correct.

Unless the latter two have the same norm as previously, but aren't actually equal to what they were?

**Comment by mscroggs** [comment]
It seems to be an issue with integrals of grads, as these are ok:

https://github.com/FEniCS/dolfinx/blob/e4574badc7f60ecd035726ec00534e8942a9c5cf/python/test/unit/fem/test_plus_minus.py#L73-L80

But these are not:

https://github.com/FEniCS/dolfinx/blob/e4574badc7f60ecd035726ec00534e8942a9c5cf/python/test/unit/fem/test_plus_minus.py#L105-L112

**Comment by jhale** [comment]
I also struggled to come up with a really good MWE. It may be that my "works" comments are a red herring and in fact they are broken as well. In fact, thinking about my full problem (which I can share with you if you want) it could be that all three forms are broken.

**Comment by mscroggs** [comment]
When assembling the form in your MWE with `"+"`, I'm getting a non-symmetric matrix when it should be symmetric. I made this into a test:

https://github.com/FEniCS/dolfinx/blob/8131eef25a74444b6b8d2b6ad0888977d1bbc793/python/test/unit/fem/test_plus_minus.py#L23-L53

**Comment by mscroggs** [comment]
I've found this issue: DOF transformations aren't functioning as they should for dS integrals. Fix coming on Monday
