### ISSUE TITLE
Python 3.9 specific typing constructs

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#1739]
https://github.com/FEniCS/dolfinx/blob/afbd8bd6361acdc226ef6f81b8d814e5914f504c/python/dolfinx/fem/assemble.py#L35

Causes Python 3.8 and earlier to fail.

https://docs.python.org/3/library/typing.html#abstract-base-classes

**Comment by garth-wells** [comment]
I these can just be removed.

**Comment by jhale** [comment]
Fixed as part of #PR1740
