### ISSUE TITLE
Segfault on python3 exit

### ISSUE THREAD

**Issue by gatling-nrl** [FEniCS/dolfinx#1753]
Dolfinx is running on an HPE Cray EX. gcc 9.3.0. Python 3.9.4. (I used gcc 9.3.0 because that's the compiler that was used to build the system python3.) No compiler or other build errors during the build, however I had to manually create a simlink in ~/.local/lib/ pointing to the dolfinx.so in ~/.local/lib64/. Using an interactive session, `import dolfinx` imports without error and module appears functional. But after `exit()` there is a segmentation fault. This happens even if the only command issued during the session is `import dolfinx`.

**Comment by jhale** [comment]
I haven't managed to reproduce the issue. Members of the team do use Cray supplied HPCs and we haven't had a problem. The second issue I think is unrelated to the first. Please reopen if you find more information.
