### ISSUE TITLE
Remove possibly untested test

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#1757]
As we no longer depend on eigen, I do not think the test:
https://github.com/FEniCS/dolfinx/blob/main/python/test/unit/fem/test_assemble_cppimport.py#L26
is ever checked for correctness. 

We could either:
1. Remove it
2. Add eigen to testing suite

**Comment by garth-wells** [comment]
@chrisrichardson any views? I think this test is presently broken because it's not covered by the CI.
