### ISSUE TITLE
Support pybind11 install via pip

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#176]
It would be nice to be able to use pybind11 installed via `pip install pybind11`. The issue is that this does not come with supporting CMake files.

**Comment by chrisrichardson** [comment]
An example of using pip in: https://github.com/FEniCS/dolfinx/tree/chris/pybind-pip. This dispenses with CMake for the python build.

**Comment by garth-wells** [comment]
An issue to consider is that the pybdind11 provided CMake file adds a number of compiler options that have a significant impact on the compiled code, especially in terms of binary size.

**Comment by jorgensd** [comment]
Seems like there has been some progress on this: https://github.com/pybind/pybind11/pull/2433

**Comment by chrisrichardson** [comment]
We should take a look at scikit-build for this (as is done in basix)

**Comment by garth-wells** [comment]
I think this works now (thanks to changes on the pybind11 side).
