### ISSUE TITLE
No has_petsc_complex flag in dolfinx/lab docker image

### ISSUE THREAD

**Issue by matsievskiysv** [FEniCS/dolfinx#1765]
I've updated the dolfinx/lab image to the [latest version](https://hub.docker.com/layers/dolfinx/lab/latest/images/sha256-a5263e9a7db9fceaf185c06004a36620a1090adb2262dd71b7d5e93d647d640f?context=explore) and it does not have a `dolfinx.has_petsc_complex` flag.

**Comment by francesco-ballarin** [comment]
That flag was removed last week, see e.g. [this diff](https://github.com/FEniCS/dolfinx/pull/1752/files#diff-ff705451f5572c6e8eab4b923157b7e27c4a294b055e1ff8838856d265decb4d) for an equivalent way of carrying out the same task now.
