### ISSUE TITLE
Add matrix-free solver demos

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1776]
It would be helpful to add a matrix-free solver demo. Problem should include boundary conditions.

- [x] #1959 
- [ ] Python version

**Comment by mapengfei-nwpu** [comment]
Will matrix-free methods preconditioned with multigrid method be considered in the future? Just like in Dealii https://dealii.org/developer/doxygen/deal.II/step_37.html

**Comment by jhale** [comment]
Yes, putting in the basic infrastructure to do scalable geometric multigrid is on our roadmap.

**Comment by garth-wells** [comment]
@IgorBaratta could a Python version be added?

**Comment by IgorBaratta** [comment]
> @IgorBaratta could a Python version be added?

Yes, I can do that.
And once we have the interpolation operator (different meshes) we could also do matrix free geometric mutigrid.
