### ISSUE TITLE
[CMake] out of tree configuration of dolfinx leaves garbage in current directory

### ISSUE THREAD

**Issue by matsievskiysv** [FEniCS/dolfinx#1786]
When running CMake configuration out of tree with command like `cmake -B $BUILD_DIR -S $SOURCE_DIR/cpp` files `a.out`, `cmake_hdf5_test.o` and `foo.h5` are created in the current working directory. Running `nm a.out` lists a bunch of `H5...` symbols.
Probably it's an upstream problem, but creating an issue anyway.

**Comment by jhale** [comment]
Not much we can do about this, it's caused by CMake's upstream FindHDF5 script:

https://github.com/Kitware/CMake/blob/master/Modules/FindHDF5.cmake#L220
