### ISSUE TITLE
Implement local graph reordering algorithm

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1791]
Presently we use SCOTCH to re-order graphs for data locality (per MPI rank). It would be helpful to implement our own graph ordering algorithm to provide more control and to remove SCOTCH as a required dependency.

**Comment by chrisrichardson** [comment]
Which algorithm? Is SCOTCH using the GPS algorithm? Boost has Cuthill-McKee, I think...

**Comment by garth-wells** [comment]
I would suggest GPS as a start. Cuthill-McKee is simple, no need to use Boost.
