### ISSUE TITLE
Add CentOS(-based) runner to CI

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1792]
It would be helpful to at least occasionally run the tests in a CentOS container. This could pick up subtle issues around install paths, etc. HPC systems often has CentOS-like operating systems.

**Comment by jhale** [comment]
I have a WIP Dockerfile for building binary wheels that is CentOS-based starting from the manylinux-2014 (https://github.com/pypa/manylinux) base image. This could potentially double up for this purpose, rather than having three Dockerfiles to maintain.
