### ISSUE TITLE
Validate Xdmf IO against Xdmf DTD schema in tests

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#181]
From @garth-wells: We can extend unit tests for XDMF IO to check validity against official Xdmf schema, see https://gitlab.kitware.com/xdmf/xdmf/blob/master/Xdmf.dtd

Validation of XML could be done with `lxml`,
https://emredjan.github.io/blog/2017/04/08/validating-xml/

**Comment by garth-wells** [comment]
@michalhabera do you think we could do this now?
