### ISSUE TITLE
`Discontinuous type Coefficient must be restricted` for quadrilateral cells

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#1814]
Running the following code gives `ufl.log.UFLException: Discontinuous type Coefficient must be restricted`.

```python
import ufl
from dolfinx import UnitSquareMesh, Function, FunctionSpace, fem  
from dolfinx.mesh import CellType
from mpi4py import MPI

# mesh = UnitSquareMesh(MPI.COMM_WORLD, 2, 2, CellType.triangle)
mesh = UnitSquareMesh(MPI.COMM_WORLD, 2, 2, CellType.quadrilateral)

V = FunctionSpace(mesh, ("P", 1))
w = Function(V)
w.interpolate(lambda x: x[0])

form = w * ufl.dS

value = fem.assemble_scalar(form)
```

If you use a mesh of triangles (comment out the mesh creation and uncomment the line above), then it runs fine.

**Comment by mscroggs** [comment]
As a temporary fix, I've replaced `w` with `ufl.avg(w)` but as the space should be continuous, I don't think this should be necessary

**Comment by jorgensd** [comment]
I think this issue belongs in `ffcx`, as the minimal `ufl`-file produces the same error message:
```python
cell = quadrilateral
element = FiniteElement("Lagrange", cell, 1)

coord_element = VectorElement("Lagrange", cell, 1)
mesh = Mesh(coord_element)

V = FunctionSpace(mesh, element)
u = Coefficient(V)
a = u * dS
```

**Comment by jorgensd** [comment]
The issue is due to ufl's way of checking families by string, i.e.
https://github.com/FEniCS/ufl/blob/0c934309c0ae5908c75efaf04ae5b6f4e106af5e/ufl/algorithms/apply_restrictions.py#L135
This should have an `f== "Lagrange" or f == "Q"`.

I'll add a PR later today

**Comment by mscroggs** [comment]
probably should add `or f == "S"` too, as serendipity should also be fully continuous

**Comment by jorgensd** [comment]
What is the serpendipity equivalent on non-simplices?

**Comment by mscroggs** [comment]
Lagrange

**Comment by mscroggs** [comment]
Fixed by https://github.com/FEniCS/ufl/commit/22c21bdece61d3400eadb4931eef754fbf13dd9e
