### ISSUE TITLE
Remove GenericFunction

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#183]
`GenericFunction` is too generic, covers too wide range of scenario.
This generality leads to implicit behaviour. 

Example 1: Values of BCS are GenericFunction. Inside DirichletBC call to `GenericFunction.restrict` is made, which "interpolates" values in every cell. It works for `Constant`, since constant inherits from `GenericFunction`, but leads to hidden suboptimal behaviour.

Example 2: Coefficients for tabulation kernels are GenericFunction, e.g. in Form.cpp. By call to `restrict` they are again cell-wise interpolated to target FE space. It works for Expression, since expression inherits from `GenericFunction`, but hides the interpolation to FE element. Very common pitfall for users.

I will remove GenericFunction in following steps (each one as a PR):

- [x] Make `Function` not inherit from GenericFunction.
- [x] Make `Expression` not inherit from GenericFunction.
- [x] Replace `GenericFunction`  with `Function`.

The arguments supporting this issue are also:
- We must strictly separate concepts of FE function (Function.cpp) and anything else.
- We should specialise evaluation of constant valued expr and optimise for performance.
- We must make user more aware of relation between objects in his UFL form and heavy dolfin data.
- Explicit is better than implicit.
- Simple is better than complex.

**Comment by michalhabera** [comment]
Let me motivate the proposal again in more detail. I will here talk about why the implicit behaviour
is bad in our case.

### The issue of `Expression` implicit behaviour

In the current code, when user writes (lets stay on triangles)

```python
a = Expression("sin(x[0]*x[1])", degree=2) * TestFunction(P1) * dx
```

this translates into a tabulation kernel which accepts one coefficient `w[6]`.
It is the vector of coefficients with respect to P2 basis functions.
For every cell, there is an underlying local interpolation of `sin(x[0]*x[1])`
to P2 space, which results in cell-local set of these coefficients.

Instead, if one does
```python
x = SpatialCoordinate(mesh)
a = sin(x[0] * x[1]) * TestFunction(P1) * dx
```

function `sin(x[0] * x[1])` is evaluated at quadrature points and resulting tabulation
kernel doesn't have any coefficients as arguments. (no additional memory fetching
during assembly!)

This shows unnecesary implicitness and complexity that comes with acceptation
of generic object in form. It is not very "natural" to hide the true behaviour from user.

Making `degree` in expression more explicit we pushed a bit users to think about
inner interpolation, but I doubt anyone is aware of the actual coefficients behaviour.

In addition, in the UFL syntax the UFL degree estimation is ON, taking into account
also the geometry mapping, etc... User do not need, but could, force his own quadrature
degree.

Yes, I am aware that in some cases (local chemical/plasticity/... problem solved at each quadrature
point) expression cannot be written as UFL primitive. But for such cases we should have a fast(!)
interpolation to `Quadrature` finite element. For instance
```python
expr = MyMagicExpression()
expr_interp = interpolate(MyMagicExpression(), Q_gauss_2)
assemble(expr_interp * dx)
```
Of course, memory requirements are a bit higher in this case, but contiguous data layout can
pay it back in runtime performance.

---

### `Constant` in C++

There is no reason to treat `Constant` as a special class in dolfin cpp layer. Why?
Because (due UFL design) it is just a Real FE Coefficient, i.e. a cpp's `Function`. Of course, we'll keep the helper function for python interface...

---

I would really like to see, that we strictly mirror the UFL behaviour on DOLFIN side.
`ufl.Coefficient` ---> `dolfin/function/Function`,
`ufl.Constant` == `ufl.Coefficient` ---> `dolfin/function/Function`

And in UFL, only Coefficient is allowed to be in form.

**Comment by michalhabera** [comment]
@garth-wells @chrisrichardson I would really appreciate If you think about this and give back comments.

**Comment by garth-wells** [comment]
See also #1

**Comment by garth-wells** [comment]
See https://github.com/FEniCS/dolfinx/pull/243 and https://github.com/FEniCS/dolfinx/pull/229.
