### ISSUE TITLE
Define python `import` scheme

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#185]
For now and ever, we should come up with python side module structure.

I propose:
- 2-level structure, e.g. dolfin.{fem/la/io/...}.{classname}
  This can be simply done with wildcard import in `foo/__init__.py` and in `foo/foobar.py` we will control what wildcard means using `__all__ = ["Function", "Constant", ...]`
  We do not really want user to have `function.function.Function`... 2-level seems ideal to me.

The code would like

```python
from dolfin.function import TrialFunction, TestFunction
from dolfin.fem import assemble
from dolfin.io import XDMFFile

...
```

**Comment by chrisrichardson** [comment]
This is good. Can we make a GitHub Project, and collect some of these proposals together.

**Comment by garth-wells** [comment]
This is ok for now, can revisit again later if needed.
