### ISSUE TITLE
"Handle Derivatives"

### ISSUE THREAD

**Issue by bradlipovsky** [FEniCS/dolfinx#1853]
I'd like to be able to be able to evaluate derivatives in a particular ufl.algebra.Sum, but I keep ending up here: 

https://github.com/FEniCS/dolfinx/blob/d2ecfa4a0c78a22f0c5aff6fc29ce1c90dc20612/python/dolfinx/fem/function.py#L249

What would it take to "handle derivatives"?

**Comment by jhale** [comment]
This codepath should be removed, we have a new way of e.g. evaluating gradients (and other arbitrary ufl.Expressions) using `dolfinx.Expression`. @michalhabera and I are polishing this at the moment, you can keep an eye on this pull request: https://github.com/FEniCS/dolfinx/pull/1858

**Comment by jhale** [comment]
It would be really helpful if you could provide a short example of what you are trying to achieve so we can work on this using our new approach.

**Comment by bradlipovsky** [comment]
Consider the [elasticity demo ](https://fenicsproject.org/pub/tutorial/html/._ftut1008.html).

This code reproduces the above assertion failure:

```
s = sigma(u)
sxx = s[0,0]
sxx( (0.1,0.1,0.1) )
```

Note that I did have to change out `nabla_div` for `sym(grad(-))` in the definition of `sigma(u)` since it appears like nabla_div isn't around any longer.  I put the modified version [here](https://gist.github.com/bradlipovsky/e720c1e0093b3f2b0f14da03e252d18e).

**Comment by jhale** [comment]
Thanks. Funnily enough, this is exactly the problem we plan to add a demo for. In the meantime you can use a projection to solve for the stresses.

**Comment by jhale** [comment]
I just noticed you script is using DOLFIN, not DOLFINx. For DOLFIN it would be best to search for 'calculating stresses' on our discourse forum. For DOLFINx you can either project or we will have a solution for direct evaluation soon.
