### ISSUE TITLE
Could not find a package configuration file provided by "Basix" error while building cpp dolfinx. Any solution for this?

### ISSUE THREAD

**Issue by lokit-iscitech** [FEniCS/dolfinx#1915]
When running cmake command, I keep getting the error "Could not find a package configuration file provided by "Basix"". Any idea how to solve this?

**Comment by adeebkor** [comment]
Are you able to build `ffcx`?

**Comment by loukitkhemka** [comment]
Actually, I want to build dolfinx only because I want to experiment with the CPP and PETSc code. So I did not build ffcx.

**Comment by lokit-iscitech** [comment]
Man, I give up. It is install one library after another after another. Screw FENICS. I don't give a s**t any more

**Comment by mscroggs** [comment]
Basix and FFCx are requirements of dolfinx, so you can't install dolfinx only. I recommend using a Docker image to run DOLFINx, as there are images that have the requirements installed already
