### ISSUE TITLE
Issue when creating mesh

### ISSUE THREAD

**Issue by pmosx** [FEniCS/dolfinx#1933]
I have problem when trying to create a mesh.

The code that i tested: 
```` 
import numpy as np
from dolfinx.mesh import CellType, create_unit_square, create_interval
from mpi4py import MPI
n_elem = 128
mesh = create_unit_square(MPI.COMM_WORLD, n_elem, n_elem)
````
The error that i got is: 
````
Traceback (most recent call last):
  File "poisson.py", line 8, in <module>
    mesh = create_unit_square(MPI.COMM_WORLD, n_elem, n_elem)
  File "/home/pmosx/.local/lib/python3.8/site-packages/dolfinx/mesh.py", line 324, in create_unit_square
    return create_rectangle(comm, [np.array([0.0, 0.0]),
  File "/home/pmosx/.local/lib/python3.8/site-packages/dolfinx/mesh.py", line 296, in create_rectangle
    mesh = _cpp.mesh.create_rectangle(comm, points, n, cell_type, ghost_mode, partitioner, diagonal)
RuntimeError: Incompatible dimension of arrays, compile in DEBUG for more info
````
However, the command 
```` 
mesh = create_interval(MPI.COMM_WORLD, 128, [0.,1.])
````
executed without any errors.

Code executed with latest dolfinx/dolfinx after compiling from source.

**Comment by jorgensd** [comment]
I cannot reproduce this error.
Could you print the following:
```python
import dolfinx.common
print(dolfinx.common.git_commit_hash)
import dolfinx
print(dolfinx.__version__)
```

**Comment by pmosx** [comment]
The output is: 
```
1b1d6b49a850cf558fd6cb499bb8270e98803640
0.3.1.0
```

**Comment by jorgensd** [comment]
Could you give a detailed description as to how you built dolfinx. 

You said:
"Code executed with latest dolfinx/dolfinx after compiling from source."
Does that mean that you are using the `dolfinx/dolfinx` docker container, and that you then installed the dolfinx c++ and Python interfaces?

**Comment by pmosx** [comment]
I have compiled from source all the dependencies, as they described https://docs.fenicsproject.org/dolfinx/main/python/installation.html. Then, i added their respective python interface. Their installation did not seem to be broken as the test that they supply are executed successfully.

**Comment by pmosx** [comment]
The error originated from a incorrect compilation phase of basix. Now, everything runs smoothly.
