### ISSUE TITLE
Remove `Function::compute_point_values`

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1958]
This function is slow and no longer required now that we have improved interpolation support. Remaining use is the in the IO code.

Was removed from the Python interface in #1955.

**Comment by jorgensd** [comment]
This function is no longer exposed in any layer, as it is only used internally in `dolfinx/io/xdmf_utils.cpp`, ref #1990, so I guess we can close this issue.

**Comment by garth-wells** [comment]
I'd suggest leaving it open since it shouldn't be used in internally either.
