### ISSUE TITLE
Remove calls to `dolfinx::MPI::compute_graph_edges` in `SparsityPattern`

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1965]
`dolfinx::MPI::compute_graph_edges` involves global MPI all-to-all calls. However, the required information (or at the least the relevant neighbourhood) is often already known from earlier steps. In these cases `dolfinx::MPI::compute_graph_edges` should be avoided.

See https://github.com/FEniCS/dolfinx/pull/1930/files#r790335252.

**Comment by jorgensd** [comment]
@garth-wells Could we close this issue, as you have added the `nbx` algorithm?
