### ISSUE TITLE
Flawless mesh workflow

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#198]
This is quite general issue, would be nice to keep in mind.

FEniCS solvers, in past, focused more on complicated forms solved on simple domains, but real world engineering applications are also about simple forms solved on complicated domains.

Its needed to make workflow: 
1. mesh editor (gmsh) --> 2. `xdmf/vtk` mesh files --> 3. DOLFIN-X `Mesh`, `MeshFunction`, `MeshValueCollection`

as smooth, as possible.

For a sketch of what actions have to be automated see https://gist.github.com/michalhabera/bbe8a17f788192e53fd758a67cbf3bed

This is motivated with countless requests from community. The target user community is not negligible.

**Comment by tianyikillua** [comment]
> FEniCS solvers, in past, focused more on complicated forms solved on simple domains, but real world engineering applications are also about simple forms solved on complicated domains.

Excellent!

The interface MED of meshio (https://github.com/nschloe/meshio/pull/352#issuecomment-475204271) provides a new way of defining boundaries for real engineering geometries, through salome, an open-source pre- and post software.

**Comment by massimiliano-leoni** [comment]
> > FEniCS solvers, in past, focused more on complicated forms solved on simple domains, but real world engineering applications are also about simple forms solved on complicated domains.
> 
> Excellent!
> 
> The MED interface of meshio ([nschloe/meshio#352 (comment)](https://github.com/nschloe/meshio/pull/352#issuecomment-475204271)) provides a new way of defining boundaries for real engineering geometries, through salome, an open-source pre- and post software.

This is similar to the workflow we use with fenics-hpc, where we often run simulations on very complex geometries. I was wondering what the fenics solution was, as this would be an important aspect in a possible switch. Would you like to discuss this further?

**Comment by jorgensd** [comment]
I guess some of this has already been addressed, by adding the possibility to load a mesh through the mesh initializer with the geometry (nodes defining the geometry) and the topology (the connectivity of each cell) as input arguments. PR #631 opens up for the possibility of distributing the mesh from the first processor to the others by using `build_distributed_mesh`. 

Right now, it is not clear which format (XDMF, VTK or something else) should be the format to consider for the future (especially for higher order geometries). This has to be considered.

**Comment by garth-wells** [comment]
Can we close this now @michalhabera @jorgensd?

**Comment by michalhabera** [comment]
After #1020, I would say. It needs a few more demos to showcase what is possible, but in general mesh+tags are now possible with file storage and also directly from arrays, both in parallel.

**Comment by michalhabera** [comment]
Happily closing this. Demos will come in the near future to explore all options possible now, but the functionality should be available.

The PR was mainly about:
- too many ways of tagging parts of the mesh
    - there is now only MeshTags
- too much gymnastics needed when reading tagged parts of the mesh, for example in gmsh 
    - MeshTags IO in XDMFFile supports reading format which gmsh/meshio stores, no intermediate steps needed (maybe apart from mixed topology)
- not working in parallel/higher-order
    - resolved as well
