### ISSUE TITLE
Add __citation__ PEP compatibility

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#202]
As discussed at NumFOCUS summit.

https://github.com/adrn/CitationPEP

**Comment by chrisrichardson** [comment]
What should go in the citation? The FEniCS Book (which is gradually becoming obsolete)?
Or should we push to zenodo, get a doi, and use that as the citation? (which is a bit chicken and egg) - can we get a DOI from zenodo before packing up the repo?

**Comment by jhale** [comment]
The FEniCS Book is obsolete, apart from describing the academic goals of the project. On the other hand, it does pickup citations for some people :)

I know that Figshare will issue DOIs prior to making an item public. I find Zenodo a bit complex, but I'm sure it will do the same.

**Comment by wence-** [comment]
You can pre-reserve a zenodo DOI for an upload before finalising the contents.
