### ISSUE TITLE
Add SNES API

### ISSUE THREAD

**Issue by jiayingqi** [FEniCS/dolfinx#2027]
Hi,

Somehow this suggestion is related to the comment in issue#1285: "It's questionable why we have a Newton solver that depends in PETSc when we could just use PETSc SNES".

So I would like to ask if it is possible to release the API of SNES to the users directly. Then the users can directly and conveniently call a wide range of nonlinear solvers in PETSc instead of just using the classical newton solver. 

For example, I have to use the quasi-newton solver together with a line search algorithm to deal with some problems which are difficult to converge with the classical newton solver. And I have to write a subroutine as shown in the `NonlinearPDE_SNESProblem()` class. 

I think it would be great to make FEniCSx users be able to use a wider range of nonlinear solvers conveniently. Thanks!

**Comment by michalhabera** [comment]
@jiayingqi You can check https://github.com/michalhabera/dolfiny/blob/master/dolfiny/snesblockproblem.py. We have few examples on how to use SNES for block/non-block problems. But you'll see that using SNES for single unknown field is very straightforward.
