### ISSUE TITLE
Mailmap outdated

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2031]
Has not been updated for 6 years. Should be updated or removed.

**Comment by garth-wells** [comment]
We definitely don't want to update it! Any harm in just removing it?

**Comment by jorgensd** [comment]
> We definitely don't want to update it! Any harm in just removing it?

I dont think so.
Historically, it had been used to map commits from different emails to the same user.

doesnt seem like it is supported with github: https://github.com/orgs/community/discussions/22518
