### ISSUE TITLE
Support refinement and MeshTags

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#2033]
It would be help when refining a mesh that has associated MeshTags if we could created 'refined' MeshTags for the refines mesh.

**Comment by chrisrichardson** [comment]
Yes, this has been an 'outstanding' issue for some time. The 'parent' cell is computed for each new cell, so in principal, much of the data is there. Doing it for facets in parallel is probably a bit more tricky.

**Comment by arvedes** [comment]
Do you have any plans to implement this feature in the near future? I'd be very important for my project, for which I'd prefer to use dolfinx. However, if this will be implemented on the long run only, I'll have to take dolfin v2019.

I'm currently only doing 2D simulations on a single-core, so if you have any hint's for a custom quick-and-dirty solution I'd also be very grateful.

**Comment by garth-wells** [comment]
It's a high priority - hopefully in the next few weeks.

**Comment by arvedes** [comment]
Thank you very much, that would be great!

**Comment by garth-wells** [comment]
Fixes in #2104.
