### ISSUE TITLE
dolfinx.mesh.create_meshtags unusable with ufl.Measure after #2044

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#2048]
I believe that #2044 has introduced a regression when generating mesh tags through `dolfinx.mesh.create_meshtags` rather than `dolfinx.mesh.meshtags`.

Indeed, mesh tags generated through `dolfinx.mesh.create_meshtags` do not have the required `ufl_id` attribute, which instead `MeshTagsMetaClass` has. Without such attribute, assembly fails with errors along the lines of
```
File /usr/local/lib/python3.9/dist-packages/ufl/form.py:438, in Form._analyze_subdomain_data(self)
    436         subdomain_data[domain][it] = sd
    437     elif sd is not None:
--> 438         if data.ufl_id() != sd.ufl_id():
    439             error(
    440                 "Integrals in form have different subdomain_data objects."
    441             )
    442 self._subdomain_data = subdomain_data

AttributeError: 'dolfinx.cpp.mesh.MeshTags_int32' object has no attribute 'ufl_id'
```

Consider either:
1) adding the `ufl_id` attribute to tags generated through `dolfinx.mesh.create_meshtags`, or
2) hiding such function from the public interface, if after #2044 the user should rely on `dolfinx.mesh.meshtags` instead.

BTW, `create_meshtags` is reported twice in https://github.com/FEniCS/dolfinx/blob/main/python/dolfinx/mesh.py#L26-L27

**Comment by garth-wells** [comment]
`ufl_id()` in UFL is annoying and clumsy. I don't see why `if data is not sd` isn't adequate.

@francesco-ballarin  Can you try the branch https://github.com/FEniCS/dolfinx/tree/garth/fix-meshtags-id? Could also post a MWE that can be added to the tests?

**Comment by francesco-ballarin** [comment]
OK @garth-wells , I will push the MWE to your branch (and have a look at fixing the current recursion error).

**Comment by francesco-ballarin** [comment]
@garth-wells I have pushed the required test to your branch. I'll leave it you to fix the recursion error in the `name` setter, I tried with a solution that seemed obvious to me but that did not work ;)

My end use case are currently affected by the `name` setter error, but as soon as that setter is restored I will test them too.

**Comment by jorgensd** [comment]
For later reference; the issue only occurs when sending in tuples as `subdomain_id`. Then `ufl` requires an `ufl_id` on the input `subdomain_data`. MWE reproducing the error below:
```python
    import numpy as np

    from dolfinx.graph import create_adjacencylist
    from dolfinx.mesh import (create_meshtags, create_unit_cube,
                              locate_entities_boundary)
    from ufl import Measure, TestFunction, TrialFunction, inner
    from dolfinx.fem import FunctionSpace
    from mpi4py import MPI

    comm = MPI.COMM_WORLD

    mesh = create_unit_cube(comm, 6, 6, 6)
    tdim = mesh.topology.dim
    marked_facets = locate_entities_boundary(mesh, tdim - 1, lambda x: np.isclose(x[1], 1))
    f_v = mesh.topology.connectivity(tdim - 1, 0).array.reshape(-1, 3)

    entities = create_adjacencylist(f_v[marked_facets])
    values = np.full(marked_facets.shape[0], 2, dtype=np.int32)

    ft = create_meshtags(mesh, tdim - 1, entities, values)

    V = FunctionSpace(mesh, ("Lagrange", 1))
    u = TrialFunction(V)
    v = TestFunction(V)
    ds = Measure("ds", subdomain_data=ft, subdomain_id=(2, 3))
    a = inner(u, v) * ds
    assert isinstance(a.subdomain_data(), dict)

```
