### ISSUE TITLE
An error occurred while installing the c++ core

### ISSUE THREAD

**Issue by xiang-tao** [FEniCS/dolfinx#2054]
I am using an Ubuntu system. When I run the command cmake .. in the terminal, an error occurs. The error message is as follows:
```
CMake Error at CMakeLists.txt:162 (find_package):
  Could not find a package configuration file provided by "Basix" with any of
  the following names:

    BasixConfig.cmake
    basix-config.cmake

  Add the installation prefix of "Basix" to CMAKE_PREFIX_PATH or set
  "Basix_DIR" to a directory containing one of the above files.  If "Basix"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/xt/github/dolfinx/cpp/build/CMakeFiles/CMakeOutput.log".
```
Since I don't know anything about cmake syntax, I don't know how to solve this error, I hope to get your help, thank you.

**Comment by jorgensd** [comment]
Have you installed [basix](https://github.com/FEniCS/basix) which is one of the dependencies of DOLFINx: https://docs.fenicsproject.org/dolfinx/main/python/installation.html#source
