### ISSUE TITLE
paraview crashed when loading hdf5 file 

### ISSUE THREAD

**Issue by tengzhang48** [FEniCS/dolfinx#2061]
Hello,

I created a singularity container based on the docker container on the docker hub (both dolfinx/dolfinx and dolfinx/lab). I can run the python demos, such as poisson and elasticity and generate the output files. But I cannot open them in paraview. I tried different versions of paraview from 5.8 to 5.10 and have similar errors. It will crash when I try to load the output file.

What are the possible reasons for this? Is this related to the transfer from docker container to singularity container? I am running simulations on computer clusters and thus can only use singularity. 

Thanks.

Best,
Teng

**Comment by jorgensd** [comment]
What XDMF-reader are you using in Paraview, there are three readers as described here: https://discourse.paraview.org/t/xmdf-reader-names-xdmf2-reader/4756/2
You should use: Xdmf3ReaderT

**Comment by tengzhang48** [comment]
I tried all three readers. I just tested it again using Xdmf3ReaderT and still get paraview crashed.

**Comment by pmosx** [comment]
I experienced the same problem when I ran the examples with mpi. When i executed them in serial, there was no problem.

**Comment by jorgensd** [comment]
There is a bug due to the naming scheme for functions in dolfinx.
A workaround is to rename the function that you want to write to file, i.e.:
```python
uh.name = "u"
with io.XDMFFile(msh.comm, "poisson.xdmf", "w") as file:
    file.write_mesh(msh)
    file.write_function(uh)
```

**Comment by tengzhang48** [comment]
Yes, it works now. Thanks a lot.

Best,
Teng
