### ISSUE TITLE
How to compile dolfinx in window?

### ISSUE THREAD

**Issue by zhang-qiang-github** [FEniCS/dolfinx#2065]
How can I compile dolfinx in window? Is it possible to provide CMakelists.txt so that I can compile it by VS?

**Comment by garth-wells** [comment]
Simple answer is no, it's not possible. As @jorgensd mentions, DOLFINx depends on PETSc and PETSc does not support Windows.

We are moving to make PETSc optional, in which case a Windows build may be possible if there is community support.

The recommended way to run DOLFINx under Windows is (i) using Windows Subsystem for Linux or (ii) Docker.
