### ISSUE TITLE
Error when passing values to dolfinx.fem.Expression.eval()

### ISSUE THREAD

**Issue by srosenbu** [FEniCS/dolfinx#2091]
https://github.com/FEniCS/dolfinx/blob/cefa0092702e80e254c7a8e58d6af17f05b12a8d/python/dolfinx/fem/function.py#L169

I get an error when I try to call 
`Expression.eval(cells, values=some_values)` 
but 
`some_values = Expression.eval(cells)` 
works just fine.
It seems to me that there is just a small typo in `Expression.eval.` Expression does not have an attribute `_dtype`, but it has an attribute `dtype`.
Minimal example:
```python
import dolfinx as dfx
import basix
from mpi4py import MPI
import numpy as np
import ufl

mesh = dfx.mesh.create_unit_square(MPI.COMM_WORLD, 2, 2)
P1 = dfx.fem.VectorFunctionSpace(mesh, ("CG", 1))
v = dfx.fem.Function(P1)

map_c = mesh.topology.index_map(mesh.topology.dim)
num_cells = map_c.size_local
cells = np.arange(num_cells, dtype=np.int32)

expr = dfx.fem.Expression(ufl.nabla_grad(v), P1.element.interpolation_points)

values1 = expr.eval(cells)

values2 = np.zeros_like(values1)

expr.eval(cells, values=values2)
```

The Error message:
```
Traceback (most recent call last):
  File "/root/podman_exchange/dolfinx-helpers/expr_error.py", line 21, in <module>
    expr.eval(cells, values=values2)
  File "/usr/local/dolfinx-real/lib/python3.8/dist-packages/dolfinx/fem/function.py", line 169, in eval
    if values.dtype != self._dtype:
AttributeError: 'Expression' object has no attribute '_dtype'
```

Renaming the variable in the attached line from `self._dtype` to `self.dtype` solves the problem for me
``` python
if values.dtype != self._dtype: 
```
to
``` python
if values.dtype != self.dtype: 
```
[Edit] I specified what I changed in the code

**Comment by IgorBaratta** [comment]
Hi @srosenbu 
Thanks for spotting the issue/solution. 

I just created a PR with your proposed change.
