### ISSUE TITLE
Installing using conda

### ISSUE THREAD

**Issue by ahmad681** [FEniCS/dolfinx#2097]
I was told conda only supports the older version of fenics 2019. 
I installed anaconda just fine, and I try to install fenics using conda create -n fenicsproject -c conda-forge fenics  as shown in https://fenicsproject.org/download/archive/ 
that didn't work and keeps outputting 
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - fenics

Current channels:

  - https://conda.anaconda.org/conda-forge/label/prerelease/win-64
  - https://conda.anaconda.org/conda-forge/label/prerelease/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

then I try to use conda install -c conda-forge fenics or conda install -c conda-forge/label/prerelease fenics
conda install -c conda-forge/label/cf201901 fenics 

and none worked, same messege popped up. 

Any clue? Thanks

**Comment by Parisa-Omidvar** [comment]
FEnics is not supported for windows. you need to use docker.

**Comment by garth-wells** [comment]
This report is for FEniCS/DOLFN rather than FEniCSx/DOLFINx. You can try the Slack channel.

**Comment by ahmad681** [comment]
oops, sorry garth, 
So I did install docker, but it keeps saying virtualization must be enabled. Quite frankly, I never understood what virtualization is, and so I am wondering if you ever encountered that, and think enabling virtualization would affect machine performance.

**Comment by garth-wells** [comment]
Performance in Docker is generally very good, especially with Linux. Compute performance on other operating systems is generally good, with the most common degradation being IO rather than compute performance.
