### ISSUE TITLE
LaTeX doesn't render in dolfinx documentation

### ISSUE THREAD

**Issue by jrichterpowell** [FEniCS/dolfinx#2098]
When viewing the dolfinx documentation, the tex  doesn't render property (it displays uncompiled). This makes it difficult to read any of the examples.

I've attached a screenshot of the [example page](https://docs.fenicsproject.org/dolfinx/main/python/demos/demo_poisson.html):
<img width="762" alt="image" src="https://user-images.githubusercontent.com/23251147/160511954-ebf29621-6a0a-4a7d-9d14-7596ae57f353.png">

I've only tested this on MacOS, but the tex is not rendered in any of chrome, firefox or safari.

**Comment by garth-wells** [comment]
Here is a live link: https://docs.fenicsproject.org/dolfinx/main/python/demos/demo_poisson.html

@jhale?
