### ISSUE TITLE
Add custom Basix element demo

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#2114]
Following #2113, custom Basix elements will be supported in DOLFINx. We should add a demo showing how to use them. It can link to the Basix demo (https://github.com/FEniCS/basix/issues/404) for an explanation of the inputs when creating the element.

**Comment by garth-wells** [comment]
@mscroggs does #2140 fix this issue?

**Comment by mscroggs** [comment]
Not quite, I want to add a demo of a custom Basix element too
