### ISSUE TITLE
Interpolation on a submesh

### ISSUE THREAD

**Issue by jpdean** [FEniCS/dolfinx#2126]
Interpolation on a mesh where a process has no cells currently causes a segfault. Returning an empty array of interpolation coordinates on processes with no cells (see https://github.com/FEniCS/dolfinx/tree/jpdean/submesh_function_fix) fixes this. However, if a process happens to own a dof that is not in a cell on that process, it's value will not be set on that process during intepolation. A work around is to send ghost values back to their owners, but this seems like a hack. This issue should only affect point evaluation dofs on the mesh vertices.

**Comment by garth-wells** [comment]
@jpdean can this be closed?

**Comment by jpdean** [comment]
Yes, this has been fixed properly now by determining new owners for unconnected submesh vertices
