### ISSUE TITLE
Package pyvista missing from Docker image dolfinx/lab

### ISSUE THREAD

**Issue by LukBukkit** [FEniCS/dolfinx#2151]
Hello,

while following the tutorial on https://jorgensd.github.io/dolfinx-tutorial/chapter1/fundamentals_code.html, I noticed that the Python package `pyvista` is missing from the Docker image of [`dolfinx/lab`](https://hub.docker.com/r/dolfinx/lab) with the `latest` and `latest-amd64` tags.
To reproduce the problem:
1. Start a lab container with `docker run -it --entrypoint "/bin/bash" dolfinx/lab`
2. Try to import the package pyvista: `python3 -c "import pyvista"`

The following error occurs:
```
lukas@lukas-debian:~$ docker run -it --entrypoint "/bin/bash" dolfinx/lab
root@c80014fb7b7b:~# python3 -c "import pyvista"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyvista'
```

The same error occurs when trying to import pyvista within a Jupyter Notebook. The selection of the kernel is irrelevant for the issue.
![grafik](https://user-images.githubusercontent.com/8070210/165180788-20d9b89b-72df-4363-817f-a7b1b37f2b2f.png)

Best wishes,
Lukas

**Comment by tgroche** [comment]
I ran into the same issue. I verified with `pip list` that it was not installed.
Installing pyvista in the container by hand solved it but looking at the image history it should already be installed.

**Comment by LukBukkit** [comment]
I've published a Docker container with the correct dependencies as a temporary fix. Feel free to use it.
https://github.com/LukBukkit/dolfinx-lab-pyvista
https://hub.docker.com/r/lukbukkit/dolfinx-lab-pyvista

**Comment by jorgensd** [comment]
Seems like the ARG PYVISTA_VERSION is not passed through to the lab images, ref:
https://github.com/FEniCS/dolfinx/runs/6168108266?check_suite_focus=true (line 344)
```bash
#37 [lab 4/5] RUN dpkgArch="$(dpkg --print-architecture)";     case "$dpkgArch" in amd64)     pip3 install --no-cache-dir pyvista==${PYVISTA_VERSION} ;;     esac;     pip3 install --no-cache-dir matplotlib
#37 1.436 ERROR: Could not find a version that satisfies the requirement pyvista==
#37 1.436 ERROR: No matching distribution found for pyvista==
```
@jhale  any idea why the arg doesn't work?
I'm test a fix locally and will make a PR if it works

**Comment by LukBukkit** [comment]
Thanks for your help!

When working on the step [Plotting the mesh using pyvista](https://jorgensd.github.io/dolfinx-tutorial/chapter1/fundamentals_code.html#plotting-the-mesh-using-pyvista) of the official tutorial, the packages `pythreejs` and `ipygany` are also required. It is intention that those packages are missing from the `dolfinx/lab` container or is this unintended?
