### ISSUE TITLE
dolfinx:complex in docker  doesn't work

### ISSUE THREAD

**Issue by cwang392** [FEniCS/dolfinx#216]
Hello There,

Thank you for your efforts on complex number supporting. 

I installed dolfinx:complex from docker as follows, but it doesn't work.
 sudo docker pull quay.io/fenicsproject/dolfinx:complex 
 sudo docker run --shm-size=1g -ti -v $(pwd):/home/shared quay.io/fenicsproject/dolfinx:complex 

Could you give any suggestions?

Thanks,
Cunfu.

**Comment by garth-wells** [comment]
Please use the Slack channel or mailing lists (https://fenicsproject.org/community/) for help - this is a Docker related questions rather than a code issue.
