### ISSUE TITLE
Python dependencies

### ISSUE THREAD

**Issue by tiagovla** [FEniCS/dolfinx#2185]
Are those the correct versions? I could only find  `fenics-ffcx@v0.4.2` and `fenics-ufl@2022.1.0.post0`.
https://github.com/FEniCS/dolfinx/blob/8e5bc85c15f19b4bb01bbc30411633e2d0995101/python/setup.py#L21-L22

**Comment by tiagovla** [comment]
Oh, those are the `main` ones.

**Comment by jhale** [comment]
I understand that you understand but I will just explain it here in case other people stumble on the thread.

In this pre v1.0.0 phase, when we make a release we bump main version by 0.0.1 and add .dev0.
