### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'Conj' and 'Form'

### ISSUE THREAD

**Issue by PBouteiller** [FEniCS/dolfinx#2187]
Hi i have met a very basic bug, or at least a strange behaviour, using dolfin legacy (my installation may be corrupted) 

Here is a very minimal code showing the issue:

from dolfin import *

mesh = RectangleMesh(Point(0., 0.), Point(1, 1), 1, 1, "crossed")
V = VectorFunctionSpace(mesh, 'CG', degree=2)
u_ = TestFunction(V)
x = SpatialCoordinate(mesh)

# Working
first_form = inner(Constant((1,1)), u_) * x[0] * dx
print("First form", first_form)

# Not working
dx1 = x[0] * dx
second_form = inner(Constant((1,1)), u_) * dx1
print("Second form", second_form)
 
Do you know if this bug has been solved with dolfinx ?

**Comment by jorgensd** [comment]
This is an issue with ufl, where there are no operation defined between the `Conj` operator and a `ufl`-form. 
Similar code for dolfinx:
```python
from ufl import TestFunction, inner, dx, SpatialCoordinate
from mpi4py import MPI
from petsc4py import PETSc
from dolfinx.mesh import (CellType, create_unit_square)
from dolfinx.fem import (VectorFunctionSpace, Constant, form)

# ----------------------------------------------------
mesh = create_unit_square(MPI.COMM_WORLD,10, 10, CellType.triangle)

V = VectorFunctionSpace(mesh, ("CG", 2))
u_ = TestFunction(V)
x = SpatialCoordinate(mesh)
c = Constant(mesh,  PETSc.ScalarType((1,1)))
first_form = inner(c, u_) * x[0] * dx
form1 = form(first_form)

dx1 = x[0] * dx
second_form = inner(c, u_) * dx1
form2 = form(second_form)
print("Second form", second_form)
print("First form", first_form)
```
Please submit an issue to the [ufl issue tracker](https://github.com/FEniCS/ufl/issues).
It can be traced back to these two functions, which does not support multiplying a ufl-form with the inner product, as it is not constant over each cell.
