### ISSUE TITLE
Support interactive plotting backends for Pyvista in JupyterLab images

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2192]
The default backend of pyvista only renders static graphics in the `dolfinx/lab` images.
Preferably we would like to have interactive plotting.

Options are listed at: 
https://docs.pyvista.org/user-guide/jupyter/index.html#state-of-3d-interactive-jupyterlab-plotting
where the two packages that stand out is `pythreejs` and `ipygany`, as they do not require a virtual framebuffer.

**Comment by jhale** [comment]
You added these, do they work?

**Comment by garth-wells** [comment]
Works.
