### ISSUE TITLE
Function argument names are wrong in the pybind11 generated functions

### ISSUE THREAD

**Issue by atouminet** [FEniCS/dolfinx#2220]
Hello, quick feedback from a user perspective.

Take any function from the python module `dolfinx.cpp`, for instance `dolfinx.cpp.fem.CoordinateElement.pull_back` that can be called as a method (without explicitly importing the cpp module) `mesh.geometry.cmap.pull_back(x, cell_geom)`.

The argument names for these functions are not explicit enough, for instance the generated prototype for `pull_back` is
`(self: dolfinx.cpp.fem.CoordinateElement, arg0: numpy.ndarray[numpy.float64], arg1: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.float64]`.
From the user perspective, that makes it hard to understand how to call this function, and thus one has to read the C++ documentation or source code.

A fix for this would be to add the original argument names in the pybind11 code, as explained [here](https://stackoverflow.com/questions/71443908/how-to-have-pybind11-positional-argument-names-show-up-on-help) for example.

**Comment by jorgensd** [comment]
> Are you welcoming external PR's? If so I might have some time to implement this, it does not seem that hard to do :]

We are open for PR from anyone:)
