### ISSUE TITLE
Current python API makes it cumbersome to tabulate basis functions of a function space

### ISSUE THREAD

**Issue by Armand-Touminet** [FEniCS/dolfinx#2221]
Let's say that I want to tabulate the basis of a finite element at some points in the reference cell.
I believe the easiest way to do this with the current python API is to use `basix` to create a `basix.finite_element` and then call the `tabulate` method.

However, this has limitations in the following cases:
1. I create a `dolfinx.fem.FunctionSpace` from the basix element, discard the basix element variable and manipulate only the function space in the rest of my code.
2. I create a `dolfinx.fem.FunctionSpace` from a `ufl` element.

In both cases, a `dolfinx.cpp.fem.FiniteElement` can be accessed as a member of the function space object. But the `FiniteElement` object exposes very few methods in the python API, in particular it does not expose the `tabulate` method that is available in the C++ interface.

I thus propose one of the following:
1. Expose more methods in the python interface of `dolfinx.cpp.fem.FiniteElement`
2. Provide the ability to construct a basix element from a `dolfinx.cpp.fem.FiniteElement`

**Comment by jorgensd** [comment]
See: https://github.com/FEniCS/dolfinx/pull/2205
