### ISSUE TITLE
Switching to complex mode from conda install

### ISSUE THREAD

**Issue by mattragoza** [FEniCS/dolfinx#2236]
Hi there,

I just installed the fenics-dolfinx package from conda forge and I would like to use it to solve complex-valued PDEs. However, the instructions in the README for switching to complex mode refer to shell scripts that I can't find within my conda environment after installing the package.

How can I switch to complex mode after installing the package with conda?

**Comment by jorgensd** [comment]
@minrk do you have any suggestions as to how to tell conda that we need the complex build of petsc?

**Comment by minrk** [comment]
Yes, we can do this. Should it require complex petsc, or build both real and complex?

**Comment by jorgensd** [comment]
It should build both, as in most cases, people do not want to use complex numbers (real should be default mode).
In the docker images, we install both: https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile#L240-L288, https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile#L328-L329
and then let the user change the `PYTHONPATH` for each install: https://github.com/FEniCS/dolfinx#docker-images

I guess a slightly different approach has to be adopted with conda.

Any thoughts @jhale, @garth-wells ?

**Comment by minrk** [comment]
Yeah, for conda real/complex will be different builds of the same package, so after https://github.com/conda-forge/fenics-dolfinx-feedstock/pull/14 you would do:

```bash
conda install fenics-dolfinx # to get 'real' by default
```

or 

```bash
conda install fenics-dolfinx petsc=*=complex*
```

to install the appropriate dolfinx compatible with a complex petsc build. You can opt-in to real as well by replacing 'complex' with 'real'.


If you want both at the same time for some reason, that would be creating two envs, much like you do with $PYTHOHNPATH:

```bash
conda create -n dolfinx-real fenics-dolfinx
conda create -n dolfinx-complex fenics-dolfinx petsc=*=complex*
```

**Comment by mattragoza** [comment]
Thanks for the quick fix! If I were to include this in a conda `environment.yml` file, should it look like this?

```
dependencies:
  - fenics-dolfinx
  - petsc=*=complex*
```
Or should they be on the same line:

```
dependencies:
  - fenics-dolfinx petsc=*=complex*
```

**Comment by minrk** [comment]
The former. You are asking for two packages:

1. `fenics-dolfinx`, and 
2. Any complex build of petsc (`petsc=*=complex*`)

And conda will pick the appropriate dolfinx build to match.

This should work now, since the complex builds have been published.
