### ISSUE TITLE
`LocalSolver` not available in dolfinx

### ISSUE THREAD

**Issue by tianjuxue** [FEniCS/dolfinx#2243]
Hello,

From the [forum](https://fenicsproject.discourse.group/t/nonlinear-hyperelasticity-in-dolfin-x-minimal-example-and-a-few-issues/3098/16), the [LocalSolver](https://fenicsproject.org/olddocs/dolfin//2017.1.0/python/programmers-reference/fem/solving/LocalSolver.html) is not available in dolfinx. This function is particularly useful for local projections, e.g., it is used in this [plasticity example](https://comet-fenics.readthedocs.io/en/latest/demo/2D_plasticity/vonMises_plasticity.py.html).

Any chance this function can be implemented? 

Thanks,
Tianju

**Comment by jorgensd** [comment]
Instead of doing a projection, why not use interpolation, as described in: https://github.com/FEniCS/dolfinx/blob/main/python/demo/demo_elasticity.py#L225

**Comment by jorgensd** [comment]
Do you have any notion as to when you would need a LocalSolver instead if interpolation @garth-wells ?

**Comment by tianjuxue** [comment]
> Instead of doing a projection, why not use interpolation, as described in: https://github.com/FEniCS/dolfinx/blob/main/python/demo/demo_elasticity.py#L225

I need to use quadrature element to represent those internal variables of plasticity defined on quadrature points, e.g.,

```
W_ele = ufl.TensorElement("Quadrature", mesh.ufl_cell(), degree=deg_stress, quad_scheme='default', symmetry=True)
W = fem.FunctionSpace(mesh, W_ele)
```
and if I do `Expression` (e.g., `sigma_vm_expr = Expression(sigma_vm, W.element.interpolation_points`), I get an error

**RuntimeError: Cannot get interpolation points - no Basix element available. Maybe this is a mixed element?**

**Comment by jorgensd** [comment]
> > Instead of doing a projection, why not use interpolation, as described in: https://github.com/FEniCS/dolfinx/blob/main/python/demo/demo_elasticity.py#L225
> 
> I need to use quadrature element to represent those internal variables of plasticity defined on quadrature points, e.g.,
> 
> ```
> W_ele = ufl.TensorElement("Quadrature", mesh.ufl_cell(), degree=deg_stress, quad_scheme='default', symmetry=True)
> W = fem.FunctionSpace(mesh, W_ele)
> ```
> 
> and if I do `Expression` (e.g., `sigma_vm_expr = Expression(sigma_vm, W.element.interpolation_points`), I get an error
> 
> **RuntimeError: Cannot get interpolation points - no Basix element available. Maybe this is a mixed element?**

I realized that @michalhabera  must have used this already, and by inspection of the tests, i found: https://github.com/FEniCS/dolfinx/blob/6c631eb50ef9bf72f6d14828928ae2caaddcd3cd/python/test/unit/fem/test_expression.py#L321 which does what you would like to (as far as I can tell).

**Comment by tianjuxue** [comment]
> 

Thank you so much. I think this completely solves my problem. I have incorporated it into my code

https://github.com/tianjuxue/plasticity/blob/main/src/mechanical.py#L244

**Comment by jorgensd** [comment]
> > 
> 
> Thank you so much. I think this completely solves my problem. I have incorporated it into my code
> 
> https://github.com/tianjuxue/plasticity/blob/main/src/mechanical.py#L244

I wouldn't call it a local projection, as it is actually an interpolation operator

**Comment by tianjuxue** [comment]
> 

That's right. Just changed the naming.
