### ISSUE TITLE
Core dump upon 'import dolfinx' when using Spack

### ISSUE THREAD

**Issue by frysally** [FEniCS/dolfinx#2251]
Dear all,
I tried to install DOLFINx on [Anvil](https://www.rcac.purdue.edu/knowledge/anvil) with Spack exactly following the [link](https://github.com/FEniCS/dolfinx/blob/main/README.md). It shows that the installation was successful
[intallation_log.txt](https://github.com/FEniCS/dolfinx/files/8970190/intallation_log.txt), but when I input "python -c 'import dolfinx'", it outputs "Segmentation fault (core dumped)". Meanwhile, things like "import ufl" seem to work.

The python version I'm using is built within Spack (Python 3.9.13). I contacted Anvil team and they can reproduce the error. Instead, a containerized version with Singularity seems to work. However, Spack is still a preferred way to avoid MPI issues. Could you figure out what's happening?

**Comment by cmaurini** [comment]
This was the solution for me 

https://fenicsproject.slack.com/archives/C26N589GV/p1648056744986039

**Comment by frysally** [comment]
Thanks @cmaurini. The OS I'm using is CentOS 8 Linux. I cannot import basix--it also produces segfault.

**Comment by cmaurini** [comment]
So this is probably the same issue I had. After a long fight, I solved with this patch, adding `NO EXTRAS` option to `pybind11` in `CMakeListq.txt`. It is probably a bug in RHEL8/CENTOS8, see https://github.com/pybind/pybind11/issues/3386. For me it appeared after a system update on the cluster.

```
diff --git a/python/CMakeLists.txt b/python/CMakeLists.txt
index dea67a22d9..36d40ce837 100644
--- a/python/CMakeLists.txt
+++ b/python/CMakeLists.txt
@@ -43,7 +43,7 @@ set(CMAKE_CXX_EXTENSIONS OFF)
 
 # Create the binding library
 # pybind11 handles its own calls to target_link_libraries
-pybind11_add_module(cpp MODULE
+pybind11_add_module(cpp MODULE NO_EXTRAS
   dolfinx/wrappers/dolfinx.cpp
   dolfinx/wrappers/common.cpp
   dolfinx/wrappers/fem.cpp
```

**Comment by cmaurini** [comment]
Yes, I personally uses spack to build basic dependencies when needed, or the modules generated via spack by the sys-admin, but then I build petsc/basix/ffcx/ufl/dolfinx by myself. I am a little bit overwhelmed by the spack technology. 

I suggest to try to build by hands just `basix` without `dolfinx`. It  has a minimal set of dependencies. This is the way I found to get out of it.

**Comment by lgorenstein** [comment]
Update: Being in a bit of time crunch, we ~cheated~ have taken a shortcut and used the  [Conda method](https://github.com/FEniCS/dolfinx/blob/main/README.md#conda) to install. Everything worked quite nicely, both simple `import dopfinx` and actual examples.

**Comment by garth-wells** [comment]
Closing, as most likely a bug in version of gcc shipped with Redhat/Centos 8.
