### ISSUE TITLE
Conda installation Issues

### ISSUE THREAD

**Issue by slavakung** [FEniCS/dolfinx#2259]
When I try to install from source I receive:

`
/Documents/Fenics/dolfinx-main/cpp/build$ cmake ..
fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:126 (find_package):
  By not providing "Findpugixml.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pugixml", but
  CMake did not find one.

  Could not find a package configuration file provided by "pugixml" with any
  of the following names:

pugixmlConfig.cmake
pugixml-config.cmake

  Add the installation prefix of "pugixml" to CMAKE_PREFIX_PATH or set
  "pugixml_DIR" to a directory containing one of the above files.  If
  "pugixml" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
`

When I try to install by anaconda:

`
conda install -c conda-forge fenics-dolfinx mpich pyvista
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
....
`

However when I try with spack, it appears to install without error

Yet when I try 

`python

import fenics`

or 
`
python
import dolphinx
`

the libraries are not found

Please help?

**Comment by jorgensd** [comment]
If you install from source, you need to install `pugixml`, as it is listed as a dependency at: https://docs.fenicsproject.org/dolfinx/main/python/installation.html#dependencies

The conda message is not complete, so i cannot help you with that.

For the spack installation, you have misspelled the package name (it is `dolfinx` not `dolphinx`

**Comment by slavakung** [comment]
Thank you for your response. I include the conda message in full below, I had thought the latest trace would be enough if it was a common issue.

With spack, sorry for the silly mistake, indeed import dolfinx is error-free. import fenics however does not find the library. Is there an independent conda package for fenics itself, or is this fully included in the dolfinx python package in the latest version?





conda install -c conda-forge fenics-dolfinx mpich pyvista
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 1021, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 230, in get_reduced_index
        push_record(record)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 204, in push_record
        combined_depends = record.combined_depends
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/models/records.py", line 329, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 480, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 480, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 511, in _merge
        final = this_component.merge(that_component)
      File "/home/slava/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 764, in merge
        % (self.raw_value, other.raw_value))
    ValueError: Incompatible component merge:
      - '*real*'
      - 'real_*'

`$ /home/slava/anaconda3/bin/conda install -c conda-forge fenics-dolfinx mpich pyvista`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/slava/anaconda3/bin/conda
             CONDA_PREFIX=/home/slava/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/slava/anaconda3/bin/python
               CONDA_ROOT=/home/slava/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/slava/anaconda3/bin:/home/slava/.yarn/bin:/home/slava/.config/ya
                          rn/global/node_modules/.bin:/home/slava/.nvm/versions/node/v12.18.4/bi
                          n:/home/slava/anaconda3/bin:/home/slava/anaconda3/condabin:/home/slava
                          /.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b
                          in:/usr/games:/usr/local/games:/snap/bin:/home/slava/Android/Sdk/emula
                          tor:/home/slava/Android/Sdk/tools:/home/slava/Android/Sdk/tools/bin:/h
                          ome/slava/Android/Sdk/platform-tools
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/slava/anaconda3
            shell level : 1
       user config file : /home/slava/.condarc
 populated config files : 
          conda version : 4.8.5
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.31
       base environment : /home/slava/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/slava/anaconda3/pkgs
                          /home/slava/.conda/pkgs
       envs directories : /home/slava/anaconda3/envs
                          /home/slava/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.22.0 CPython/3.7.6 Linux/5.13.0-48-generic ubuntu/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

**Comment by jorgensd** [comment]
For DOLFINx, you do not need any `fenics` package, as `fenics` and `dolfin` was names for the same package in the legacy version. For the conda issues, maybe @minrk has any suggestion?

**Comment by minrk** [comment]
I'll have to look for an explanation/workaround/fix, but it looks like a conda bug that it's erroring when presented with overlapping globs.

You might try creating a fresh env (replace `conda install ...` with `conda create -n myenv ...`) in case it's a conflict with the current env.

**Comment by TJHeeringa** [comment]
I got the same error as slavakung when running `conda install -c conda-forge fenics-dolfinx mpich pyvista`. When creating a fresh env using `conda env create --file environment.yml` like suggested by minrk, the error is still appears. In both cases I can install all my packages, including mpich and pyvista, just fine, but the package `fenics-dolfinx` gives the following error:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/16029718/177325508-bb269673-9b2d-4325-915f-8c761ade0ab8.png">

I am doing this on a mac with MacOS 11.6 and 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/16029718/177326343-2838c883-d706-4814-93f9-ce576f4b8fd4.png">

**Comment by TJHeeringa** [comment]
This seems to happen to more packages lately, see for example https://github.com/conda/conda/issues/11442, https://github.com/conda/conda-build/issues/4498 and https://github.com/pyne/pyne/issues/1452. The last one includes a comment with a workaround (if using mamba instead of conda is okay for you): https://github.com/pyne/pyne/issues/1452#issuecomment-1136232682.

Thus, it seems this is an issue with conda and not necessarily with dolfinx.

**Comment by minrk** [comment]
Tracked and submitted fix to conda: https://github.com/conda/conda/pull/11612

The core of this appears to be in the conda-forge petsc packages, which should be getting fixed builds to avoid the conflict. New packages should be up later today. Tracking: https://github.com/conda-forge/petsc-feedstock/issues/147

**Comment by minrk** [comment]
Mamba works now, I'm not sure if repodata needs to be patched for conda to avoid considering the older builds.

**Comment by minrk** [comment]
The petsc metadata patches have been applied, so this should be fixed:

```
docker run --rm -it condaforge/miniforge3 conda create -n test --dry-run fenics-dolfinx
```

<details>

<summary>output</summary>

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/conda/envs/test

  added / updated specs:
    - fenics-dolfinx


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-4.5          |            2_gnu          23 KB  conda-forge
    adios2-2.8.1               |mpi_openmpi_py310hf25f2b0_0         5.0 MB  conda-forge
    binutils_impl_linux-aarch64-2.36.1|       h026399b_2        10.4 MB  conda-forge
    binutils_linux-aarch64-2.36|      h7854541_10          24 KB  conda-forge
    blosc-1.21.1               |       hdfcada4_3          35 KB  conda-forge
    boost-cpp-1.74.0           |       ha1c1135_8        16.5 MB  conda-forge
    bzip2-1.0.8                |       hf897c2e_4         396 KB  conda-forge
    c-ares-1.18.1              |       hf897c2e_0         118 KB  conda-forge
    ca-certificates-2022.6.15  |       h4fd8a4c_0         149 KB  conda-forge
    cffi-1.15.1                |  py310hf0c4615_0         254 KB  conda-forge
    fenics-basix-0.4.2         |  py310h9ceb0a0_3         179 KB  conda-forge
    fenics-dolfinx-0.4.1       |py310h5d9564e_108         933 KB  conda-forge
    fenics-ffcx-0.4.2          |     pyhb871ab6_1          93 KB  conda-forge
    fenics-libbasix-0.4.2      |       h8f8c065_3         839 KB  conda-forge
    fenics-libdolfinx-0.4.1    |     h9aa49a8_108        18.4 MB  conda-forge
    fenics-ufcx-0.4.2          |       hb871ab6_1          14 KB  conda-forge
    fenics-ufl-2022.1.0        |     pyhd8ed1ab_0         165 KB  conda-forge
    fftw-3.3.10                |mpi_openmpi_h99744b4_2         6.2 MB  conda-forge
    gcc_impl_linux-aarch64-10.3.0|      ha07e0e6_16        44.3 MB  conda-forge
    gcc_linux-aarch64-10.3.0   |      h4e3e293_10          25 KB  conda-forge
    gmp-6.2.1                  |       h7fd3ca4_0         737 KB  conda-forge
    gxx_impl_linux-aarch64-10.3.0|      ha07e0e6_16        10.9 MB  conda-forge
    gxx_linux-aarch64-10.3.0   |      h72ff769_10          24 KB  conda-forge
    hdf5-1.12.1                |mpi_openmpi_hf150c17_4         4.1 MB  conda-forge
    hypre-2.25.0               |mpi_openmpi_hb574ba3_0         1.9 MB  conda-forge
    icu-70.1                   |       ha18d298_0        13.6 MB  conda-forge
    kernel-headers_linux-aarch64-4.18.0|      h5b4a56d_13         1.1 MB  conda-forge
    keyutils-1.6.1             |       h4e544f5_0         110 KB  conda-forge
    krb5-1.19.3                |       h750e270_0         1.6 MB  conda-forge
    ld_impl_linux-aarch64-2.36.1|       h02ad14f_2         669 KB  conda-forge
    libblas-3.9.0              |15_linuxaarch64_openblas          13 KB  conda-forge
    libcblas-3.9.0             |15_linuxaarch64_openblas          12 KB  conda-forge
    libcurl-7.83.1             |       h22f3f83_0         358 KB  conda-forge
    libedit-3.1.20191231       |       he28a2e2_2         131 KB  conda-forge
    libev-4.33                 |       h516909a_1         103 KB  conda-forge
    libffi-3.4.2               |       h3557bc0_5          58 KB  conda-forge
    libgcc-devel_linux-aarch64-10.3.0|      h8e480ec_16         252 KB  conda-forge
    libgcc-ng-12.1.0           |      h3242a24_16         530 KB  conda-forge
    libgfortran-ng-12.1.0      |      he9431aa_16          23 KB  conda-forge
    libgfortran5-12.1.0        |      h41d5c85_16         1.3 MB  conda-forge
    libgomp-12.1.0             |      h3242a24_16         456 KB  conda-forge
    liblapack-3.9.0            |15_linuxaarch64_openblas          12 KB  conda-forge
    libnghttp2-1.47.0          |       h2b6b862_0         953 KB  conda-forge
    libnsl-2.0.0               |       hf897c2e_0          31 KB  conda-forge
    libopenblas-0.3.20         |pthreads_h6cb6f83_0         7.1 MB  conda-forge
    libpng-1.6.37              |       hf9034f9_3         343 KB  conda-forge
    libsanitizer-10.3.0        |      h971684a_16         5.9 MB  conda-forge
    libsodium-1.0.18           |       hb9de7d4_1         231 KB  conda-forge
    libssh2-1.10.0             |       hd8c4cff_2         246 KB  conda-forge
    libstdcxx-devel_linux-aarch64-10.3.0|      h8e480ec_16         8.9 MB  conda-forge
    libstdcxx-ng-12.1.0        |      hd01590b_16         4.2 MB  conda-forge
    libuuid-2.32.1             |    hf897c2e_1000          30 KB  conda-forge
    libzlib-1.2.12             |       h4e544f5_2          71 KB  conda-forge
    lz4-c-1.9.3                |       h01db608_1         199 KB  conda-forge
    metis-5.1.0                |    h7fd3ca4_1006         4.2 MB  conda-forge
    mpfr-4.1.0                 |       h719063d_1         435 KB  conda-forge
    mpi-1.0                    |          openmpi           4 KB  conda-forge
    mpi4py-3.1.3               |  py310h0808628_1         587 KB  conda-forge
    mumps-include-5.2.1        |      h8af1aa0_11          24 KB  conda-forge
    mumps-mpi-5.2.1            |      hc617c41_11         3.8 MB  conda-forge
    ncurses-6.3                |       headf329_1         1.1 MB  conda-forge
    numpy-1.23.1               |  py310he617cf3_0         6.6 MB  conda-forge
    openmpi-4.1.4              |     h34d0eb5_100         3.9 MB  conda-forge
    openssl-3.0.5              |       h4e544f5_0         2.8 MB  conda-forge
    parmetis-4.0.3             |    ha1755b7_1005         288 KB  conda-forge
    petsc-3.17.3               |real_hbd9d3f5_100        13.1 MB  conda-forge
    petsc4py-3.17.3            |real_ha71fb2f_101         1.2 MB  conda-forge
    pip-22.1.2                 |     pyhd8ed1ab_0         1.5 MB  conda-forge
    ptscotch-6.0.9             |       h836f696_2         1.6 MB  conda-forge
    pycparser-2.21             |     pyhd8ed1ab_0         100 KB  conda-forge
    python-3.10.5              |h92ab765_0_cpython        13.0 MB  conda-forge
    python_abi-3.10            |          2_cp310           4 KB  conda-forge
    readline-8.1.2             |       h38e3740_0         305 KB  conda-forge
    scalapack-2.2.0            |       hb3004b9_1         2.3 MB  conda-forge
    scotch-6.0.9               |       h07b6642_2         1.4 MB  conda-forge
    setuptools-63.1.0          |  py310hbbe02a8_0         1.4 MB  conda-forge
    slepc-3.17.1               |real_h9812a30_102         5.2 MB  conda-forge
    slepc4py-3.17.1            |real_hb6b66b3_103         379 KB  conda-forge
    snappy-1.1.9               |       hc7e91e1_1          36 KB  conda-forge
    sqlite-3.39.0              |       hc74f5b8_0         2.0 MB  conda-forge
    suitesparse-5.10.1         |       h1404dd6_1         2.3 MB  conda-forge
    superlu-5.2.2              |       h4b58547_0         221 KB  conda-forge
    superlu_dist-7.2.0         |       hec336ca_0         1.2 MB  conda-forge
    sysroot_linux-aarch64-2.17 |      h43d7e78_13        33.7 MB  conda-forge
    tbb-2021.5.0               |       hdd96247_1         1.7 MB  conda-forge
    tk-8.6.12                  |       hd8af866_0         3.4 MB  conda-forge
    tzdata-2022a               |       h191b570_0         121 KB  conda-forge
    wheel-0.37.1               |     pyhd8ed1ab_0          31 KB  conda-forge
    xtensor-0.24.2             |       hdd96247_0         189 KB  conda-forge
    xtl-0.7.4                  |       hd62202e_0          96 KB  conda-forge
    xz-5.2.5                   |       h6dd45c4_1         357 KB  conda-forge
    yaml-0.2.5                 |       hf897c2e_2          91 KB  conda-forge
    zeromq-4.3.4               |       h01db608_1         380 KB  conda-forge
    zfp-0.5.5                  |       h01db608_8         195 KB  conda-forge
    zlib-1.2.12                |       h4e544f5_2          97 KB  conda-forge
    zstd-1.5.2                 |       haad177d_2         446 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       281.4 MB

The following NEW packages will be INSTALLED:

  _openmp_mutex      conda-forge/linux-aarch64::_openmp_mutex-4.5-2_gnu
  adios2             conda-forge/linux-aarch64::adios2-2.8.1-mpi_openmpi_py310hf25f2b0_0
  binutils_impl_lin~ conda-forge/linux-aarch64::binutils_impl_linux-aarch64-2.36.1-h026399b_2
  binutils_linux-aa~ conda-forge/linux-aarch64::binutils_linux-aarch64-2.36-h7854541_10
  blosc              conda-forge/linux-aarch64::blosc-1.21.1-hdfcada4_3
  boost-cpp          conda-forge/linux-aarch64::boost-cpp-1.74.0-ha1c1135_8
  bzip2              conda-forge/linux-aarch64::bzip2-1.0.8-hf897c2e_4
  c-ares             conda-forge/linux-aarch64::c-ares-1.18.1-hf897c2e_0
  ca-certificates    conda-forge/linux-aarch64::ca-certificates-2022.6.15-h4fd8a4c_0
  cffi               conda-forge/linux-aarch64::cffi-1.15.1-py310hf0c4615_0
  fenics-basix       conda-forge/linux-aarch64::fenics-basix-0.4.2-py310h9ceb0a0_3
  fenics-dolfinx     conda-forge/linux-aarch64::fenics-dolfinx-0.4.1-py310h5d9564e_108
  fenics-ffcx        conda-forge/noarch::fenics-ffcx-0.4.2-pyhb871ab6_1
  fenics-libbasix    conda-forge/linux-aarch64::fenics-libbasix-0.4.2-h8f8c065_3
  fenics-libdolfinx  conda-forge/linux-aarch64::fenics-libdolfinx-0.4.1-h9aa49a8_108
  fenics-ufcx        conda-forge/noarch::fenics-ufcx-0.4.2-hb871ab6_1
  fenics-ufl         conda-forge/noarch::fenics-ufl-2022.1.0-pyhd8ed1ab_0
  fftw               conda-forge/linux-aarch64::fftw-3.3.10-mpi_openmpi_h99744b4_2
  gcc_impl_linux-aa~ conda-forge/linux-aarch64::gcc_impl_linux-aarch64-10.3.0-ha07e0e6_16
  gcc_linux-aarch64  conda-forge/linux-aarch64::gcc_linux-aarch64-10.3.0-h4e3e293_10
  gmp                conda-forge/linux-aarch64::gmp-6.2.1-h7fd3ca4_0
  gxx_impl_linux-aa~ conda-forge/linux-aarch64::gxx_impl_linux-aarch64-10.3.0-ha07e0e6_16
  gxx_linux-aarch64  conda-forge/linux-aarch64::gxx_linux-aarch64-10.3.0-h72ff769_10
  hdf5               conda-forge/linux-aarch64::hdf5-1.12.1-mpi_openmpi_hf150c17_4
  hypre              conda-forge/linux-aarch64::hypre-2.25.0-mpi_openmpi_hb574ba3_0
  icu                conda-forge/linux-aarch64::icu-70.1-ha18d298_0
  kernel-headers_li~ conda-forge/noarch::kernel-headers_linux-aarch64-4.18.0-h5b4a56d_13
  keyutils           conda-forge/linux-aarch64::keyutils-1.6.1-h4e544f5_0
  krb5               conda-forge/linux-aarch64::krb5-1.19.3-h750e270_0
  ld_impl_linux-aar~ conda-forge/linux-aarch64::ld_impl_linux-aarch64-2.36.1-h02ad14f_2
  libblas            conda-forge/linux-aarch64::libblas-3.9.0-15_linuxaarch64_openblas
  libcblas           conda-forge/linux-aarch64::libcblas-3.9.0-15_linuxaarch64_openblas
  libcurl            conda-forge/linux-aarch64::libcurl-7.83.1-h22f3f83_0
  libedit            conda-forge/linux-aarch64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-aarch64::libev-4.33-h516909a_1
  libffi             conda-forge/linux-aarch64::libffi-3.4.2-h3557bc0_5
  libgcc-devel_linu~ conda-forge/linux-aarch64::libgcc-devel_linux-aarch64-10.3.0-h8e480ec_16
  libgcc-ng          conda-forge/linux-aarch64::libgcc-ng-12.1.0-h3242a24_16
  libgfortran-ng     conda-forge/linux-aarch64::libgfortran-ng-12.1.0-he9431aa_16
  libgfortran5       conda-forge/linux-aarch64::libgfortran5-12.1.0-h41d5c85_16
  libgomp            conda-forge/linux-aarch64::libgomp-12.1.0-h3242a24_16
  liblapack          conda-forge/linux-aarch64::liblapack-3.9.0-15_linuxaarch64_openblas
  libnghttp2         conda-forge/linux-aarch64::libnghttp2-1.47.0-h2b6b862_0
  libnsl             conda-forge/linux-aarch64::libnsl-2.0.0-hf897c2e_0
  libopenblas        conda-forge/linux-aarch64::libopenblas-0.3.20-pthreads_h6cb6f83_0
  libpng             conda-forge/linux-aarch64::libpng-1.6.37-hf9034f9_3
  libsanitizer       conda-forge/linux-aarch64::libsanitizer-10.3.0-h971684a_16
  libsodium          conda-forge/linux-aarch64::libsodium-1.0.18-hb9de7d4_1
  libssh2            conda-forge/linux-aarch64::libssh2-1.10.0-hd8c4cff_2
  libstdcxx-devel_l~ conda-forge/linux-aarch64::libstdcxx-devel_linux-aarch64-10.3.0-h8e480ec_16
  libstdcxx-ng       conda-forge/linux-aarch64::libstdcxx-ng-12.1.0-hd01590b_16
  libuuid            conda-forge/linux-aarch64::libuuid-2.32.1-hf897c2e_1000
  libzlib            conda-forge/linux-aarch64::libzlib-1.2.12-h4e544f5_2
  lz4-c              conda-forge/linux-aarch64::lz4-c-1.9.3-h01db608_1
  metis              conda-forge/linux-aarch64::metis-5.1.0-h7fd3ca4_1006
  mpfr               conda-forge/linux-aarch64::mpfr-4.1.0-h719063d_1
  mpi                conda-forge/linux-aarch64::mpi-1.0-openmpi
  mpi4py             conda-forge/linux-aarch64::mpi4py-3.1.3-py310h0808628_1
  mumps-include      conda-forge/linux-aarch64::mumps-include-5.2.1-h8af1aa0_11
  mumps-mpi          conda-forge/linux-aarch64::mumps-mpi-5.2.1-hc617c41_11
  ncurses            conda-forge/linux-aarch64::ncurses-6.3-headf329_1
  numpy              conda-forge/linux-aarch64::numpy-1.23.1-py310he617cf3_0
  openmpi            conda-forge/linux-aarch64::openmpi-4.1.4-h34d0eb5_100
  openssl            conda-forge/linux-aarch64::openssl-3.0.5-h4e544f5_0
  parmetis           conda-forge/linux-aarch64::parmetis-4.0.3-ha1755b7_1005
  petsc              conda-forge/linux-aarch64::petsc-3.17.3-real_hbd9d3f5_100
  petsc4py           conda-forge/linux-aarch64::petsc4py-3.17.3-real_ha71fb2f_101
  pip                conda-forge/noarch::pip-22.1.2-pyhd8ed1ab_0
  ptscotch           conda-forge/linux-aarch64::ptscotch-6.0.9-h836f696_2
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  python             conda-forge/linux-aarch64::python-3.10.5-h92ab765_0_cpython
  python_abi         conda-forge/linux-aarch64::python_abi-3.10-2_cp310
  readline           conda-forge/linux-aarch64::readline-8.1.2-h38e3740_0
  scalapack          conda-forge/linux-aarch64::scalapack-2.2.0-hb3004b9_1
  scotch             conda-forge/linux-aarch64::scotch-6.0.9-h07b6642_2
  setuptools         conda-forge/linux-aarch64::setuptools-63.1.0-py310hbbe02a8_0
  slepc              conda-forge/linux-aarch64::slepc-3.17.1-real_h9812a30_102
  slepc4py           conda-forge/linux-aarch64::slepc4py-3.17.1-real_hb6b66b3_103
  snappy             conda-forge/linux-aarch64::snappy-1.1.9-hc7e91e1_1
  sqlite             conda-forge/linux-aarch64::sqlite-3.39.0-hc74f5b8_0
  suitesparse        conda-forge/linux-aarch64::suitesparse-5.10.1-h1404dd6_1
  superlu            conda-forge/linux-aarch64::superlu-5.2.2-h4b58547_0
  superlu_dist       conda-forge/linux-aarch64::superlu_dist-7.2.0-hec336ca_0
  sysroot_linux-aar~ conda-forge/noarch::sysroot_linux-aarch64-2.17-h43d7e78_13
  tbb                conda-forge/linux-aarch64::tbb-2021.5.0-hdd96247_1
  tk                 conda-forge/linux-aarch64::tk-8.6.12-hd8af866_0
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xtensor            conda-forge/linux-aarch64::xtensor-0.24.2-hdd96247_0
  xtl                conda-forge/linux-aarch64::xtl-0.7.4-hd62202e_0
  xz                 conda-forge/linux-aarch64::xz-5.2.5-h6dd45c4_1
  yaml               conda-forge/linux-aarch64::yaml-0.2.5-hf897c2e_2
  zeromq             conda-forge/linux-aarch64::zeromq-4.3.4-h01db608_1
  zfp                conda-forge/linux-aarch64::zfp-0.5.5-h01db608_8
  zlib               conda-forge/linux-aarch64::zlib-1.2.12-h4e544f5_2
  zstd               conda-forge/linux-aarch64::zstd-1.5.2-haad177d_2



DryRunExit: Dry run. Exiting.
```

</details>
