### ISSUE TITLE
demo_stokes.py pressure is wrong

### ISSUE THREAD

**Issue by wolfseifert** [FEniCS/dolfinx#2274]
Running the first part of `demo_stokes.py` (down to line `296`) for dolfinx 0.4.1 and using `VTKFile` instead of `XDMFFile` to get some human readable output you can see that the pressure is highest around (0.0, 1.0) and lowest around (1.0, 1.0).

For the _lid driven cavity problem_ it should be the other way around.

Maybe the algebraic sign of the pressure is wrong.

**Comment by jhale** [comment]
Indeed, the final weak form depends on the notion of pressure used. 

This is noted in the comments at the top of the file https://github.com/FEniCS/dolfinx/blob/main/python/demo/demo_stokes.py#L26.

However, further down the mathematical formulation clearly uses the non-symmetric formulation.
https://github.com/FEniCS/dolfinx/blob/main/python/demo/demo_stokes.py#L54

And then the symmetric formulation is actually used in the UFL implementation.

**Comment by wolfseifert** [comment]
Oh, I did not see this:

```
# ```{note}
# The sign of the pressure has been flipped from the classical
# definition. This is done in order to have a symmetric system
# of equations rather than a non-symmetric system of equations.
# ```
```
So now I `multiply(p.x.array, -1.0)` and everything is fine.

Thanks!
