### ISSUE TITLE
Replace `const std::array<T, 3>` with `std::span<const T, 3>` as input to functions

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2284]
Would be very sensible in `geometry` code.

**Comment by garth-wells** [comment]
@jorgensd Is there a particular benefit? Or can this be closed now?

**Comment by jorgensd** [comment]
In certain cases this has a benefit. Imagine that you have an array of size 3*N where you have gathered all the data you want to send in to a function that takes in an std::array. If we use `std::span<const T, 3>` instead of `const std::array<T,3>` one would not have to copy the data (however I admit there is some overhead in creating a span as well).

We can close this issue for now as I do not recall which functions I wanted this for. I'll make more targeted issues on this if I see the need for it.
