### ISSUE TITLE
0.5.0 XSIMD support: C++ demo_poisson fails undefined reference to `dolfinx::mesh::locate_entities_boundary`

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/dolfinx#2326]
I'm trying to get a Debian build of dolfinx 0.5.0. libdolfinx.so and the python modules build, and C++ unit tests pass. But C++ demo_poisson fails to compile, with
```
[ 28%] Linking CXX executable demo_poisson
cd /projects/fenics/build/fenics-dolfinx/obj-x86_64-linux-gnu-real/demo/poisson && /usr/bin/cmake -E cmake_link_script CMakeFiles/demo_poisson.dir/link.txt --verbose=1
/usr/bin/c++ -g -O2 -ffile-prefix-map=/projects/fenics/build/fenics-dolfinx=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -pthread CMakeFiles/demo_poisson.dir/main.cpp.o CMakeFiles/demo_poisson.dir/poisson.c.o -o demo_poisson  -Wl,-rpath,/projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/openmpi/lib:/usr/lib/x86_64-linux-gnu/hdf5/openmpi:/usr/lib/slepcdir/slepc3.17/x86_64-linux-gnu-real/lib:/usr/lib/petscdir/petsc3.17/x86_64-linux-gnu-real/lib /projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu/libdolfinx_real.so.0.5.0 /usr/lib/x86_64-linux-gnu/libpugixml.so.1.12 /usr/lib/x86_64-linux-gnu/libbasix.so.0.5.0 /usr/lib/x86_64-linux-gnu/libboost_timer.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.74.0 /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so /usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so /usr/lib/slepcdir/slepc3.17/x86_64-linux-gnu-real/lib/libslepc_real.so /usr/lib/petscdir/petsc3.17/x86_64-linux-gnu-real/lib/libpetsc_real.so 
/usr/bin/ld: CMakeFiles/demo_poisson.dir/main.cpp.o: in function `main':
./obj-x86_64-linux-gnu-real/demo/poisson/main.cpp:170: undefined reference to `dolfinx::mesh::locate_entities_boundary(dolfinx::mesh::Mesh const&, int, std::function<xt::xtensor_container<xt::uvector<bool, std::allocator<bool> >, 1ul, (xt::layout_type)1, xt::xtensor_expression_tag> (xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2ul, (xt::layout_type)1, xt::xtensor_expression_tag> const&)> const&)'
collect2: error: ld returned 1 exit status
```

Does cpp/demo/poisson need to be updated for the 0.5.0 API?  Or would it be an xtensor problem?

**Comment by drew-parsons** [comment]
This is building against xtensor 0.24.2-2.

**Comment by jhale** [comment]
What is the outcome of this? Do we need to make a DOLFINx 0.5.1 release with a fix?

**Comment by jhale** [comment]
I can't reproduce this error in the Docker image `dolfinx/dolfinx:v0.5.0`.

**Comment by drew-parsons** [comment]
Is that with xtensor 0.23 or 0.24 ?  Is dolfinx known to pass demo tests with either xtensor version?

**Comment by drew-parsons** [comment]
Good, so to speak. We know the problem isn't xtensor in that case.  Debian has a [pmix problem](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017356) at the moment, I'll check if I can continue to reproduce the error after that is resolved.

**Comment by drew-parsons** [comment]
I've identified the source of the discrepancy.  libdolfinx.so was prepared with `-DXTENSOR_USE_XSIMD=ON` (i.e. adding `-DXTENSOR_USE_XSIMD` to the compilation rules).  

When building the demos, this flag was not added. So the signature for `locate_entities_boundary` in libdolfinx.so differs from the one in main.cpp.o for the demo, resulting in the build error.

If I add  `-DXTENSOR_USE_XSIMD=ON` to the cmake run used with the demo then the demo builds and runs fine.

What's the best way to deal with this situation?  In one sense it's just a local configuration issue.  I can fix the debian build by adding the flag.

But on the other hand it makes the installation fragile.  If a user doesn't realise that libdolfinx.so was built with XSIMD support then they might not know they need to include `-DXTENSOR_USE_XSIMD=ON`, and are left wondering why their build fails.  Can we make cmake management of xsimd support more robust? For instance include it in DOLFINXConfig.cmake ?

In fact `find_dependency(xsimd)` is already included in DOLFINXConfig.cmake, but on it's own it doesn't set `XTENSOR_USE_XSIMD`.   Should  DOLFINXConfig.cmake be setting `XTENSOR_USE_XSIMD` at the same point where `find_dependency(xsimd)` is invoked?

**Comment by drew-parsons** [comment]
I think part of the reason this didn't show up previously in debian builds is because cpp/dolfinx/CMakeLists.txt was being [patched ](https://salsa.debian.org/science-team/fenics/fenics-dolfinx/-/blob/master/debian/patches/cmake_dolfinx_xsimd.patch) to add `target_compile_definitions(dolfinx PUBLIC XTENSOR_USE_XSIMD)`.  I'm trying to drop this patch for 0.5.0, in line with the simplifications made to Xtensor/XSIMD support.

dolfinx added explicit xsimd support in PR #1512, Apr 22, 2021 (dolfinx 0.1.0). 
It was removed with the switch to C++20 support in PR #2111, 14 Jul 2022 (dolfinx 0.5.0).

What do you advise?  I'm assuming here that building with `XTENSOR_USE_XSIMD` is still desirable in principle, albeit managed by the xtensor cmake files, not dolfinx (in 0.5.0).

**Comment by drew-parsons** [comment]
The problem is more pernicious than just building C++ demos however.  In the python module the available XSIMD support failed to propagate into the python extensions:
```
$ nm -D /projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/python3/dist-packages/dolfinx/cpp.cpython-310-x86_64-linux-gnu.so | grep locate_entities
                 U _ZN7dolfinx4mesh15locate_entitiesERKNS0_4MeshEiRKSt8functionIFN2xt17xtensor_containerINS5_7uvectorIbSaIbEEELm1ELNS5_11layout_typeE1ENS5_22xtensor_expression_tagEEERKNS6_INS7_IdSaIdEEELm2ELSA_1ESB_EEEE
                 U _ZN7dolfinx4mesh24locate_entities_boundaryERKNS0_4MeshEiRKSt8functionIFN2xt17xtensor_containerINS5_7uvectorIbSaIbEEELm1ELNS5_11layout_typeE1ENS5_22xtensor_expression_tagEEERKNS6_INS7_IdSaIdEEELm2ELSA_1ESB_EEEE
```
There's no reference to xsimd there.  In libdolfinx.so the corresponding symbols were defined (with `XTENSOR_USE_XSIMD`) as
```
$ nm -D /projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu/libdolfinx_real.so | grep locate_entities
0000000000179720 T _ZN7dolfinx4mesh15locate_entitiesERKNS0_4MeshEiRKSt8functionIFN2xt17xtensor_containerINS5_7uvectorIbN5xsimd17aligned_allocatorIbLm16EEEEELm1ELNS5_11layout_typeE1ENS5_22xtensor_expression_tagEEERKNS6_INS7_IdNS9_IdLm16EEEEELm2ELSC_1ESD_EEEE
000000000017aea0 T _ZN7dolfinx4mesh24locate_entities_boundaryERKNS0_4MeshEiRKSt8functionIFN2xt17xtensor_containerINS5_7uvectorIbN5xsimd17aligned_allocatorIbLm16EEEEELm1ELNS5_11layout_typeE1ENS5_22xtensor_expression_tagEEERKNS6_INS7_IdNS9_IdLm16EEEEELm2ELSC_1ESD_EEEE
```
The discrepant definition occurs in the symbol string after `xtensor_containerINS5_7uvector`

**Comment by drew-parsons** [comment]
The failures in both places can be easily fixed by restoring Debian patch cmake_dolfinx_xsimd.patch in the form
```
Index: fenics-dolfinx/cpp/dolfinx/CMakeLists.txt
===================================================================
--- fenics-dolfinx.orig/cpp/dolfinx/CMakeLists.txt      2022-09-03 17:36:00.045397082 +0200
+++ fenics-dolfinx/cpp/dolfinx/CMakeLists.txt   2022-09-03 17:38:03.414700851 +0200
@@ -75,6 +75,9 @@

 # xtensor
 target_link_libraries(dolfinx PUBLIC xtensor)
+if(XTENSOR_USE_XSIMD)
+  target_compile_definitions(dolfinx PUBLIC XTENSOR_USE_XSIMD)
+endif()

 # Boost
 target_link_libraries(dolfinx PUBLIC Boost::headers)
```
i.e. if xtensor is configured to use xsimd at build time (in libdolfinx.so), then this patch ensures the `XTENSOR_USE_XSIMD` is used also at runtime. The flag gets inserted into both DOLFINXTargets.cmake and dolfinx.pc.  No need for `find_package(xsimd)`, xtensor finds that itself. Just need to let xtensor know that xsimd is needed.

I'm happy to prepare a PR for it if you like.

**Comment by chrisrichardson** [comment]
It would be nice to remove xtensor, but I guess it is useful for BCs etc. @drew-parsons - sure, let's have a PR, if it will fix it.

**Comment by garth-wells** [comment]
I think we should simply remove xsimd from the cmake config.

**Comment by drew-parsons** [comment]
> I think we should simply remove xsimd from the cmake config.

Do you mean xtensor? But it's still being used. xsimd is already removed from dolfinx, apart from the reference in cmake/templates/DOLFINXConfig.cmake.in (which as far as I can see could itself be removed.  xtensor will find xsimd, if it's instructed to use it)

But since dolfinx still uses xtensor, the challenge is that xtensor itself independently configures to use xsimd, if XTENSOR_USE_XSIMD is set.

In one sense that's not dolfinx's problem.  But it becomes a question of how to manage it if a local installation does want to take advantage of the xsimd acceleration provided internally inside xtensor.  Should dolfinx ban that configuration?  How would the ban be managed, in installation documentation?

The 3-line patch I'm proposing here resolves the trouble easily enough.

**Comment by jhale** [comment]
This reminds me of the great Eigen SIMD crash issue!

1. I would propose that you keep `XTENSOR_USE_XSIMD` off in the Debian builds? We are only using xtensor in very few places now and it is likely to be removed long term. The performance benefits of enabling SIMD are probably marginal or non-existent.

2. I would accept the patch, as it seems like the proper way to do set things up for user's that do enable `XTENSOR_USE_XSIMD` in their own builds.

**Comment by drew-parsons** [comment]
OK, I'll prepare the PR.

Interesting question whether to switch off xsimd in the first place.  In one sense if we do keep it, then it means we're able to use dolfinx as a CI test for the xsimd packge ;)
