### ISSUE TITLE
C++ demos need better CI testing

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#2327]
See Issue #2326

**Comment by jhale** [comment]
Doesn't https://github.com/FEniCS/dolfinx/blob/main/.github/workflows/ccpp.yml#L129 build and test the C++ demos?

**Comment by garth-wells** [comment]
@chrisrichardson not clear to me what specifically needs to be better.

**Comment by drew-parsons** [comment]
Digging further into #2326, the issue there is managing XSIMD support when running demos.
