### ISSUE TITLE
Unify usage of MeshTags in Python interface

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2348]
Currently we use a mixture of the `MeshTagsMetaClass` and the `dolfinx::mesh::MeshTags<T>` in the Python interface.

This causes issues when using explicit typing, for instance with `mypy`, see: https://github.com/FEniCS/dolfinx/pull/2219

We should make sure that all `MeshTags` used in Python is wrapped with the meta-class.

**Comment by garth-wells** [comment]
Fixed in #2522.
