### ISSUE TITLE
ImportError: cannot import name 'QQ' from 'sympy.polys.domains.rationalfield'

### ISSUE THREAD

**Issue by jiangzhangze** [FEniCS/dolfinx#2349]
I met this error:` ImportError: cannot import name 'QQ' from 'sympy.polys.domains.rationalfield'`when I use `from dolfin import *`.Here are some informations about my packages：
`absl-py                      1.2.0
ale-py                       0.7.5
astunparse                   1.6.3
attrs                        22.1.0
box2d-py                     2.3.5
cachetools                   5.2.0
certifi                      2019.11.28
cffi                         1.15.1
charset-normalizer           2.1.1
cloudpickle                  2.1.0
cycler                       0.11.0
Cython                       0.29.32
fasteners                    0.17.3
fenics                       2019.1.0
fenics-dijitso               2019.1.0
fenics-dolfin                2019.1.0
fenics-ffc                   2019.1.0.post0
fenics-fiat                  2019.1.0
fenics-ufl                   2019.1.0
flatbuffers                  1.12
fonttools                    4.37.1
gast                         0.4.0
glfw                         2.5.4
google-auth                  2.11.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.48.1
gym                          0.25.2
gym-notices                  0.0.8
h5py                         3.7.0
idna                         3.3
imageio                      2.21.2
importlib-metadata           4.12.0
importlib-resources          5.9.0
iniconfig                    1.1.1
joblib                       1.1.0
keras                        2.9.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
libclang                     14.0.6
lz4                          4.0.2
Markdown                     3.4.1
MarkupSafe                   2.1.1
matplotlib                   3.5.3
mpi4py                       3.1.3
mpmath                       1.2.1
mujoco                       2.2.0
mujoco-py                    2.1.2.14
numpy                        1.21.6
oauthlib                     3.2.0
opencv-python                4.6.0.66
opt-einsum                   3.3.0
packaging                    21.3
pandas                       1.1.5
petsc4py                     3.12.0
Pillow                       9.2.0
pip                          22.1.2
pkgconfig                    1.3.1
pluggy                       1.0.0
protobuf                     3.19.4
py                           1.11.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pybind11                     2.4.3
pycparser                    2.21
pygame                       2.1.0
PyOpenGL                     3.1.6
pyparsing                    3.0.9
pytest                       7.0.1
python-dateutil              2.8.2
pytz                         2022.2.1
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
scikit-learn                 1.0.2
scipy                        1.7.3
setuptools                   63.4.1
six                          1.16.0
sklearn                      0.0
slepc4py                     3.12.0
stable-baselines             2.10.2
swig                         4.0.2
sympy                        1.10.1
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.9.2
tensorflow-estimator         2.9.0
tensorflow-io-gcs-filesystem 0.26.0
termcolor                    1.1.0
threadpoolctl                3.1.0
tomli                        2.0.1
typing_extensions            4.3.0
urllib3                      1.26.12
Werkzeug                     2.2.2
wheel                        0.37.1
wrapt                        1.14.1
zipp                         3.8.1`

**Comment by jiangzhangze** [comment]
Here are the versions of my fenics：`fenics                       2019.1.0
fenics-dijitso               2019.1.0
fenics-dolfin                2019.1.0
fenics-ffc                   2019.1.0.post0
fenics-fiat                  2019.1.0
fenics-ufl                   2019.1.0`

and the version of sympy:`sympy                        1.10.1`

**Comment by jorgensd** [comment]
Note that you are using the legacy version of FEniCS, which is located at https://bitbucket.org/fenics-project/dolfin/src.
It has not been updated since 2019, as indicated by the tags, and thus there is likely an API change in sympy causing this error

Note that one in modern Python does not encourage the use of wildcard-imports (`from foo import *`)
