### ISSUE TITLE
Calling `fem.form` changes ufl form sometimes

### ISSUE THREAD

**Issue by jpdean** [FEniCS/dolfinx#2352]
The following code

```
import ufl
from dolfinx import fem, mesh
from mpi4py import MPI

comm = MPI.COMM_WORLD
msh = mesh.create_unit_square(comm, 1, 1)
V = fem.FunctionSpace(msh, ("Lagrange", 1))
u, v = ufl.TrialFunction(V), ufl.TestFunction(V)
a = ufl.inner(ufl.grad(u), ufl.grad(v)) * ufl.dx

print(a.subdomain_data())
fem.form(a)
print(a.subdomain_data())
```

outputs
```
{Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 0): {'cell': [None]}}
{Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1, variant='equispaced'), dim=2, variant='equispaced'), 0): {'cell': [None]}}
```
when the cache is empty and then
```
{Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 0): {'cell': [None]}}
{Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 0): {'cell': [None]}}
```
afterwards. The issue seems to occur when the JIT compiler is called.

**Comment by chrisrichardson** [comment]
This seems to happen in ffcx in `analysis.py`
https://github.com/FEniCS/ffcx/blob/943263d69e282613b000267e1f599754a8337d34/ffcx/analysis.py#L157

**Comment by garth-wells** [comment]
Nasty - the UFL form should be immutable.

@mscroggs: could you take a look?

**Comment by michalhabera** [comment]
The "private" property `_ufl_coordinate_element` should never be changed, as well as any other underscore UFL properties.

I do not think `analysis.py` is a good place for defining default coordinate element variant. Should be rather in basix?

**Comment by mscroggs** [comment]
The issue is that we want to have GLL as the default variant unless it's a coordinate element, in which case the default should be equispaced.

I'll take a look and see if there's a different way we can acheive this without changing the element

**Comment by garth-wells** [comment]
@mscroggs any updates on this?
