### ISSUE TITLE
`xdmf_utils` does not recognize quadratic hexahedron cell types

### ISSUE THREAD

**Issue by amit112amit** [FEniCS/dolfinx#2375]
When trying to read a XDMF file with TopologyType Hexahedraon_20, I get a Runtime Error complaining about an unknown cell type.
I could trace it to the `xdmf_utils::get_cell_type` function, which only supports linear hexahedrons.

I tried using `create_mesh` to manually create the quadratic hexahedron mesh contained in H5 file associated with the XDMF but it takes too long to create the mesh as I have more than 500000 nodes in the mesh.

I found `test_higher_order_mesh.py` which has hexahedrons up to order 4. So there must be a bug somewhere.

**Comment by jorgensd** [comment]
Hexahedron 20 is not supported in DOLFINx.
We support 27 node hexahedrons as second order hexes

**Comment by amit112amit** [comment]
Ok! Thank you for the quick response.

**Comment by amit112amit** [comment]
I am sorry, I tried to read a mesh from an XDMF file containing a single Hex27 element. My XDMF file opens correctly in Paraview but not in `dolfinx`.

I have attached the `SimpleHex27.h5` and `SimpleHex27.xdmf` files used in the test code:
Consider the minimum working example:

```console
>>> from mpi4py import MPI
>>> import dolfinx.io as io
>>> xf = io.XDMFFile(MPI.COMM_WORLD, 'SimpleHex27.xdmf', 'r')
>>> mesh = xf.read_mesh(name='Grid')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/dolfinx-real/lib/python3.10/dist-packages/dolfinx/io/utils.py", line 154, in read_mesh
    cell_shape, cell_degree = super().read_cell_type(name, xpath)
RuntimeError: Cannot recognise cell type. Unknown value: hexahedron_27
>>> 
```

[SimpleHex27.zip](https://github.com/FEniCS/dolfinx/files/9644220/SimpleHex27.zip)

**Comment by jorgensd** [comment]
@amit112amit 
I've resolved this in #2376 .
However, note that the data in your XDMFFile is not correct.
Reading it in with meshio
```python
import meshio

mesh = meshio.read("SimpleHex27.xdmf")
print(mesh)
```
yields:
```bash
<meshio mesh object>
  Number of points: 27
  Number of cells:
    hexahedron27: 27
```
which is not correct (There should be only one cell).

I've fixed this in your mesh by doing:
```python
import meshio

mesh = meshio.read("SimpleHex27.xdmf")
print(mesh)
import numpy
def create_mesh(mesh, cell_type, prune_z=False):
    cells = mesh.get_cells_type(cell_type)
    points = mesh.points[:,:2] if prune_z else mesh.points
    out_mesh = meshio.Mesh(points=points, cells={cell_type: cells.reshape(1,-1)})
    return out_mesh

hex_mesh = create_mesh(mesh, "hexahedron27")
meshio.write("mesh.xdmf", hex_mesh)
```
which in general should use `cells.reshape(-1, 27)` for second order hex meshes.

This new mesh can be read in with the branch:
```python
from mpi4py import MPI
import dolfinx.io as io
with io.XDMFFile(MPI.COMM_WORLD, 'mesh.xdmf', 'r') as xdmf:
    mesh = xdmf.read_mesh(name="Grid")
import ufl
import dolfinx
print(dolfinx.fem.assemble_scalar(dolfinx.fem.form(1*ufl.dx(domain=mesh))))

with io.XDMFFile(mesh.comm, 'mesh_out.xdmf', 'w') as xdmf:
    xdmf.write_mesh(mesh)
```
yielding
```bash
0.9999999999999989
```

**Comment by amit112amit** [comment]
Thank you very much for the quick response again @jorgensd! 

Thank you for fixing the XDMF, as well. I was trying to create a Minimum Working Example. So I created the XDMF and the backend HDF5 file manually. In the process, I transposed the topology data by mistake.

**Comment by amit112amit** [comment]
Sorry, I am not well-versed in Github issues etiquette. I think I should leave this issue open, and when your pull request will be merged, it will get closed automatically. Therefore, re-opening it.

**Comment by jorgensd** [comment]
> Sorry, I am not well-versed in Github issues etiquette. I think I should leave this issue open, and when your pull request will be merged, it will get closed automatically. Therefore, re-opening it.

We leave the issue open until the PR is merged. Thanks for reporting the issue.
