### ISSUE TITLE
Add basix, ffcx, ufl as git submodules

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#2418]
I was recently in the situation of having to revert my code to its status a few months ago and run it.
That meant reverting the `dolfinx` repository too and `basix`, `ffcx` and `ufl` alongside with it.
Since the APIs of these dependencies change quickly, it is sometimes tricky to identify which revision of each of them will work with a given revision of `dolfinx`.
This could be easily fixed by adding these dependencies as git submodules to the `dolfinx` repository.
This would automatically keep track of their current commit, for example, when a new commit is pushed to `dolfinx/main`.
A user could then automagically checkout the correct revision for all dependencies simply by doing

```
git checkout <checksum>
git submodule update --init --recursive
```

**Comment by jhale** [comment]
Full disclosure, I'm not a big fan of submodules (clunky and non-intuitive).

Having said that, I still think this is unnecessary:

1. The `main` branches (almost) always works together on any given date, as it is enforced by our Pull Request/CI system. You can use git to automatically checkout a version on a particular date, e.g.

```
git checkout `git rev-list -n 1 --before="2022-10-20 00:00" main`
```

2. No one is stopping you from storing a set of working FEniCSx commits as submodules in your own repository.

**Comment by garth-wells** [comment]
I'm to close this because we've visited it before and decided that the complications outweighed any benefits.

We're making releases reasonably frequently now, and most users should use a release version.
