### ISSUE TITLE
Remove `std::map` from non-matching mesh interpolation

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#2419]
See e.g. https://github.com/FEniCS/dolfinx/pull/2245/files#diff-6208a9ad6f57063c470b05140af6f96ed580abdce54401eab6b0f89df2344ddaR106

**Comment by jorgensd** [comment]
Would we resolve this by making a flat vector of size (MPI_COMM.size) and fill it with -1 if rank is not part of the sub-set communicator?

Another alternative, as out_ranks is sorted, is to use `std::ranges::lower_bound` to find the appropriate index on the fly?
https://github.com/FEniCS/dolfinx/blob/f6a4a5a3de45003a38d3b8d3c667a1d1cf14adf9/cpp/dolfinx/fem/interpolate.h#L178-L199
What would people prefer? @garth-wells @chrisrichardson @jhale

**Comment by garth-wells** [comment]
@jorgensd don't create an array with a size equal to the number of communicator MPI ranks.
