### ISSUE TITLE
Add code formatters

### ISSUE THREAD

**Issue by tiagovla** [FEniCS/dolfinx#2426]
Since there's already `clang-format` support. What about [black](https://github.com/psf/black) for python and [cmake-format](https://github.com/cheshirekow/cmake_format) for cmake?

**Comment by jorgensd** [comment]
Personally I dont like how black formats code. Hoewever, if everyone else wants it I will not stand in the way.

**Comment by garth-wells** [comment]
I'm happy for now with `flake8` that runs on the CI.

**Comment by tiagovla** [comment]
I agree that black's formatting is not the best, especially at formatting arrays. It might be worth testing cmake-format though.

**Comment by jhale** [comment]
I'd be interested to see the clang-format output on a PR.

I think most fenics developers are using autopep8 to format Python. This isn't explicitly documented anywhere though.

**Comment by tiagovla** [comment]
> I'd be interested to see the clang-format output on a PR.
> 
> I think most fenics developers are using autopep8 to format Python. This isn't explicitly documented anywhere though.

https://github.com/FEniCS/dolfinx/pull/2431

**Comment by jhale** [comment]
Fixed in #2431
