### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by tiagovla** [FEniCS/dolfinx#2440]
Maybe adding benchmarks (e.g. with [google-benchmark](https://github.com/google/benchmark)) would be interesting to compare the performance between changes/versions.

**Comment by nate-sime** [comment]
Does this offer more than what's done already with https://fenics.github.io/performance-test-results/ ?

**Comment by tiagovla** [comment]
I didn't know that existed, it looks pretty nice. Since it's already covered, feel free to close this issue.

With a benchmark framework, it's possible to create quite specialized benchmarks, run them multiple times with different input ranges, and compare the results in a standardized way to any other commit.

I usually create those when I'm trying to optimize hot regions of code, compare linear algebra backends, or create microbenchmarks of CPU usage, memory usage, processing time, error... And of course, benchmark whole simulations.
