### ISSUE TITLE
Add target to run C++ demos

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#250]
Add back a target via CMake to (i) build and (ii) run all C++ demos.

**Comment by chrisrichardson** [comment]
Some progress towards this in the branch `chris/cmake-demos`.
Remaining issues:

*  OpenMPI requires the `--allow-run-as-root` flag. It would be preferable to remove this, and use an environment variable. This may now be possible in the latest OpenMPI: https://github.com/open-mpi/ompi/pull/5598

* Hyperelasticity demo fails to compile in complex mode: Either make it work, or prevent it from running.

**Comment by garth-wells** [comment]
Fixes by PR #274.
