### ISSUE TITLE
Docker workflow failing

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#2530]
Hi @jhale,
the docker workflow seems to have started failing around a week ago, at `Build DOLFINx end-user images (arm64, ARM64)`, specifically at the `Build lab` step.

The relevant part of the output is
```
#34 5.349   × Preparing metadata (pyproject.toml) did not run successfully.
#34 5.349   │ exit code: 1
#34 5.349   ╰─> [6 lines of output]
#34 5.349       
#34 5.349       Cargo, the Rust package manager, is not installed or is not on PATH.
#34 5.349       This package requires Rust and Cargo to compile extensions. Install it through
#34 5.349       the system's package manager or via https://rustup.rs/
#34 5.349       
#34 5.349       Checking for Rust toolchain....
#34 5.349       [end of output]
```

Surprisingly (to me, at least), the `amd64` build runs successfully. 

Due to this, the `dolfinx/dolfinx:nightly` tag has not been recently updated. I realized this while testing a downstream library, and started wondering why `dolfinx.mesh.MeshTags` was not there :O, even though the PR that introduced it was merged a couple of days ago.

**Comment by jorgensd** [comment]
There is an issue in the arm images, namely that y_py does not have an arm wheel. Should be resolved by https://github.com/y-crdt/ypy/pull/115

**Comment by jorgensd** [comment]
Now moved to: https://github.com/y-crdt/ypy/pull/119

**Comment by garth-wells** [comment]
Fixed in upstream package.
