### ISSUE TITLE
[BUG]: Basix version conflict

### ISSUE THREAD

**Issue by aaronsxzhao** [FEniCS/dolfinx#2570]
### How to reproduce the bug

I am installing c++ core of dolfinx, after typing `cmake ..`, it says 

> Could not find a configuration file for package "Basix" that is compatible with requested version "0.7". The following configuration files were considered but not accepted: /opt/homebrew/lib/python3.10/site-packages/basix/lib/cmake/basix/BasixConfig.cmake, version: 0.6.0

However, when i went to this page [https://github.com/FEniCS/basix](url), the latest version of basix was exactly 0.6.0. I am so confused and hope someone to solve my problem

### Version

main branch

**Comment by garth-wells** [comment]
You are mixing release and development versions. 0.7 is the development version, so you need the dev version of Basix to compile the dev version of DOLFINx.

**Comment by tomasApo** [comment]
> You are mixing release and development versions. 0.7 is the development version, so you need the dev version of Basix to compile the dev version of DOLFINx.

@garth-wells that was an unpleasant  answer, its clear this is a beginner/not advanced question. You could have easily guided us to the right link. I've now found it after 20mins...

Solution: 
Step 1: Uninstall fenics-basicx `pip uninstall fenics-basix`
Step 2: `pip install git+https://github.com/FEniCS/basix.git`
