### ISSUE TITLE
Check Basix UFL element vs general UFL element inputs to function spaces

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#2578]
On https://github.com/FEniCS/dolfinx/blob/c736689d180216717db2831b05354a2e3c8b2ec3/python/dolfinx/fem/function.py#L470, a general UFL element can be input.

The functionality added in https://github.com/FEniCS/dolfinx/pull/2576#pullrequestreview-1332699479 only supports basix UFL elements.

We/I should check which functions support which element classes, and hopefully extend them all to support general UFL elements

**Comment by mscroggs** [comment]
It would also be nice to get rid of any `isinstance`s in favour of `try`...`except`

**Comment by francesco-ballarin** [comment]
With #2766 reverting changes in #2576, and having closed #2577, @mscroggs this can be probably closed too.

> It would also be nice to get rid of any isinstances in favour of try...except
This one got addressed in #2651.
