### ISSUE TITLE
v0.6.0 missing from documentation webpage

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2585]
### How to reproduce the bug

The webpage
https://docs.fenicsproject.org/
does not produce v0.6.0 as latest release

### Version

main branch

**Comment by mscroggs** [comment]
I've opened a PR in FEniCS/docs to fix this (https://github.com/FEniCS/docs/pull/11).

We should add that this needs doing to the "how to make a release" guide

**Comment by garth-wells** [comment]
Fixed by https://github.com/FEniCS/docs/pull/11.
