### ISSUE TITLE
Check where 'assert' should be changed to an exception

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#26]
In many places `assert` is used instead of throwing an exception. This is likely due to the old `dolfin_error` being clunky to use (taking too many arguments).

Need to review the assert and throw exceptions where appropriate. Good example is checking the return code for file operations, e.g. calling HDF5 functions.

**Comment by michalhabera** [comment]
Nice essay on the use of assertions, https://blog.regehr.org/archives/1091
