### ISSUE TITLE
Bump PETSc?

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2609]
New release (3.19.0) is out https://gitlab.com/petsc/petsc/-/tags/v3.19.0

Do we want to bump, or wait until a post release with bug fixes?

**Comment by francesco-ballarin** [comment]
> a post release with bug fixes

v3.19.1 is now out

**Comment by garth-wells** [comment]
All Dockerfiles are presenting at PETSc 3.19.2.
