### ISSUE TITLE
Sparsity pattern overpopulated for exterior facets

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2614]
https://github.com/FEniCS/dolfinx/blob/4fb398fc16bf80e0497341c498485b0ab44a6080/cpp/dolfinx/fem/petsc.h#L134-L151
these lines will give you facets on process boundaries with ghost mode None, as illustrated with the following MWE

```python
import dolfinx
from mpi4py import MPI

mesh = dolfinx.mesh.create_unit_square(
    MPI.COMM_WORLD, 10, 10, ghost_mode=dolfinx.mesh.GhostMode.none)
mesh.topology.create_connectivity(mesh.topology.dim-1, mesh.topology.dim)

num_facets_local = mesh.topology.index_map(mesh.topology.dim-1).size_local
f_to_c = mesh.topology.connectivity(mesh.topology.dim-1, mesh.topology.dim)

exterior_facets = []
for facet in range(num_facets_local):
    cells = f_to_c.links(facet)
    if len(cells) == 1:
        exterior_facets.append(facet)

actual_exterior_facets = dolfinx.mesh.exterior_facet_indices(mesh.topology)

print(len(exterior_facets), len(actual_exterior_facets))
```
yielding
```bash
 mpirun -n 3 python3 mwe10.py 
22 15
17 9
18 16
```
This does not show up as an error in further code, as it only adds extra entries that are not used later in the code.

@garth-wells do you think it is worthwhile using `dolfinx::mesh::exterior_facet_indices` to get the correct facets?

**Comment by francesco-ballarin** [comment]
It looks to me that what you are proposing is already done when preparing the sparsity pattern for a plain matrix
https://github.com/FEniCS/dolfinx/blob/4fb398fc16bf80e0497341c498485b0ab44a6080/cpp/dolfinx/fem/utils.h#L220-L225
but not in the block matrix case
https://github.com/FEniCS/dolfinx/blob/4fb398fc16bf80e0497341c498485b0ab44a6080/cpp/dolfinx/fem/petsc.h#L134-L151

There are also further inconsistencies between the two cases, e.g. the plain matrix case is extracting the minimal set of cells
https://github.com/FEniCS/dolfinx/blob/4fb398fc16bf80e0497341c498485b0ab44a6080/cpp/dolfinx/fem/utils.h#L202
and interior facets
https://github.com/FEniCS/dolfinx/blob/4fb398fc16bf80e0497341c498485b0ab44a6080/cpp/dolfinx/fem/utils.h#L209
associated to subdomains passed in with the ufl measure, while the block matrix implementation is using all cells
https://github.com/FEniCS/dolfinx/blob/4fb398fc16bf80e0497341c498485b0ab44a6080/cpp/dolfinx/fem/petsc.h#L110
and all interior facets
https://github.com/FEniCS/dolfinx/blob/4fb398fc16bf80e0497341c498485b0ab44a6080/cpp/dolfinx/fem/petsc.h#L127

**Comment by jorgensd** [comment]
> It looks to me that what you are proposing is already done when preparing the sparsity pattern for a plain matrix

Almost, as I wasnt thinking about using the form information (Which as you point out, could reduce the pattern Even further).
