### ISSUE TITLE
Cython generated headers broken for petsc4py

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#2619]
### How to reproduce the bug

See https://gitlab.com/petsc/petsc/-/issues/1359

### Minimal Example (Python)

Build DOLFINx Python interface with petsc4py built using Cython 0.29.34

### Version

main branch

### Installation

Possible to reproduce on MacOS and Ubuntu.

**Comment by jhale** [comment]
PETSc and petsc4py can be built on commit `ffdfd6a` (~3.18.5) as a temporary workaround.

**Comment by jhale** [comment]
The previous comment is incorrect.

Building petsc4py with Cython 0.36.34 (latest) produces headers that are incompatible with the mpi4py headers that are pre-built on pypa with Cython 0.36.33 or 0.36.34.

In short, users must build petsc4py using Cython 0.36.32 or 0.36.33 if they are using mpi4py from pypi.org which contains pre-generated headers with Cython 0.36.33.

An alternative is to build mpi4py and petsc4py from source using a consistent Cython version.

**Comment by jhale** [comment]
As pointed out by @garth-wells still having issues on Mac: https://github.com/FEniCS/dolfinx/actions/runs/4891338240/jobs/8731728473

**Comment by garth-wells** [comment]
'Fixed' now for macOS CI. Complicated interaction between distutils, petsc4py build system, and Github macOS image led to strange behaviour.

Closing issue because there is nothing to do from our side.
