### ISSUE TITLE
[BUG]: `AttributeError: Can't set attribute` -- except I can

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#2625]
### How to reproduce the bug

I wanted to flip the sign of the values of a `MeshTags` object that I read from file.
In all my ignorance, I did `meshTags.values *= -1` but I got an error. The values still got changed though...

```
meshTags.values
Out[47]: array([-11, -11, -11, ..., -11, -11, -11], dtype=int32)

meshTags.values *= -1
Traceback (most recent call last):

  File "/tmp/ipykernel_94324/1239962826.py", line 1, in <module>
    meshTags.values *= -1

AttributeError: can't set attribute 'values'


meshTags.values
Out[49]: array([11, 11, 11, ..., 11, 11, 11], dtype=int32)
```

### Version

main branch

### Installation

I'm running in the latest docker image.

**Comment by jorgensd** [comment]
You can use `meshTags.values[:] *= -1` i think (not at a computer so cant test it). It has to do with how Numpy interacts with pybind

**Comment by jorgensd** [comment]
You could also use `meshTags.values.__imul__(-1)`.
Ref:
```python
import pdb
from IPython import embed
import dolfinx
from mpi4py import MPI
import numpy as np

mesh = dolfinx.mesh.create_unit_interval(MPI.COMM_WORLD, 10)
num_cells = mesh.topology.index_map(mesh.topology.dim).size_local
cells = np.arange(num_cells, dtype=np.int32)
mt = dolfinx.mesh.meshtags(mesh, mesh.topology.dim, cells, cells)

print(mt.indices)
mt.indices[:] *= -2
print(mt.indices)
mt.indices.__imul__(-2)
print(mt.indices)
```
yielding
```bash
[0 1 2 3 4 5 6 7 8 9]
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18]
[ 0  4  8 12 16 20 24 28 32 36]
```
It is actually how the `@property` decorator works
```python
import numpy as np


class A():
    def __init__(self, n):
        self._a = np.arange(n, dtype=np.int32)

    @property
    def a(self):
        return self._a


class_var = A(10)
class_var.a[:] *= 10
print(class_var.a)
class_var.a.__imul__(10)
print(class_var.a)
class_var.a *= 10
print(class_var.a)
```

```bash
[ 0 10 20 30 40 50 60 70 80 90]
[  0 100 200 300 400 500 600 700 800 900]
Traceback (most recent call last):
  File "/root/shared/mwe123.py", line 19, in <module>
    class_var.a *= 10
```

Thus I think we can close this as I think we would like to keep using property decorators.

**Comment by massimiliano-leoni** [comment]
I don't think I got the point across 😆

Everything you said is correct but the fact remains that assigning to a read-only property should not modify the property, which is what the snippet above shows to happen.

**Comment by jorgensd** [comment]
I guess it still boils down to how `@property` decorators treat `__imul__`, as I guess the code I posted would have the same result if executed in an interactive console (not at the laptop now, feel free to test it).

I guess the most viable option would be to create out own property decorator that would not throw an assign error.

**Comment by jorgensd** [comment]
Oh wait, indices and values are const in C++

https://github.com/FEniCS/dolfinx/blob/main/cpp/dolfinx/mesh/MeshTags.h#L98

**Comment by jorgensd** [comment]
To me this seems like a pybind11 issue, as even changing the `py::array_t<const std::int32>` leaves the numpy.array flags `WRITABLE` as `True`.

**Comment by garth-wells** [comment]
This behaves as expected for me. The line
```python
mt.values *= 2
```
gives
```
AttributeError: property 'values' of 'MeshTags' object has no setter
```
whereas 
```python
mt.values[:] *= 2
```
works fine and changes the values.

Python doesn't 'do' const. A 'read-only' property here means that you can access the property/array, but you cannot assign a new array to it. `*=` calls `__imul__` , which has a return value which it tries to assign. But there is not setter, so it fails. The second version modifies `mt.values`, but doesn't assign a new array to it.

**Comment by jorgensd** [comment]
The point is that from a C++ perspective these arrays are const spans, thus it should not be possible to modify an entry of the array

**Comment by garth-wells** [comment]
I'm going to close this as the behaviour is 'correct', even if unexpected. Let's open a new issues to discuss how `const` C++ should be treated from Python.

For the reported code, the behaviour is expected. The code `mt.values *= 2` is equivalent to `mt.values = __imul__(mt.values, 2)` with
```python
def __imul__(x, val):
   x[:] *= val
   return x
```
This changes the array `mt.values`, followed by an exception when attempting to assign to `mt.values`. `ipython` skips over the exception. The above explains why, after the exception, the data is changed.

The correct way to change the values would be `mt.values[:] *= 2`
