### ISSUE TITLE
Add MPI scatter support to common::IndexMap

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#263]
It would be helpful for `IndexMap` to support efficient scatters between processes that share data.

**Comment by chrisrichardson** [comment]
What interface are you thinking of? Something like:
`IndexMap::scatter(std::vector<T>&);` where the vector is local+ghost in size?
Is it basically just a sync of the ghost entries?

**Comment by garth-wells** [comment]
I hadn't thought about the interface, just that needing communication between index sets that share global entries (in the ghost section of all but one) is very common and can be kept quite local. The communication can go in a variety of directions. At the moment we know for a ghost who the owner is, but we don't know which processes ghost an owned index.

PETSc does this with VecGhostUpdateBegin/End.

**Comment by garth-wells** [comment]
I actually need something for communicating between all processes that share an index. Immediate application is communicating dofs that have a Dirchlet bc applied.

**Comment by chrisrichardson** [comment]
OK, I think I now have that functionality in my branch. Still needs a bit more documentation, but could try with DirichletBC, if you want to test it out...

**Comment by garth-wells** [comment]
See #399.
