### ISSUE TITLE
[Feature Request]: Incomplete type annotation for dolfinx.fem.functions.Constant

### ISSUE THREAD

**Issue by thisch** [FEniCS/dolfinx#2631]
### Describe new/missing feature

Since PETSc can be built with support for complex-valued scalars, passing complex values to `fem.Constant` should be supported. According to the [type-annotation](https://github.com/FEniCS/dolfinx/blob/e952664b086f6c7e7662c53ec54e8d774b101de4/python/dolfinx/fem/function.py#L32) `float`s are supported but `complex` values aren't, even though they work at runtime.

**Comment by jorgensd** [comment]
If we want to have a complete type-setting for a constant, one would also have to write out `numpy.float32`  and `numpy.complex64` as well, as they do not have formal python representations.
