### ISSUE TITLE
Regression for interpolation of a callable on cells subset

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#2638]
My `RBniCSx` CI started failing a couple of days ago, and I tracked down the issue to a regression in the interpolation of a callable on cell subsets.

The culprit can be either #2632, #2634, or #2636. I am leaning towards the first, but I can't really spot what has caused the regression.
I added a couple of failing tests in [`francesco/interpolation-callable-subset`](https://github.com/FEniCS/dolfinx/tree/francesco/interpolation-callable-subset), feel free to use that branch for the fix. In particular:
- `python/test/unit/fem/test_interpolation.py::test_interpolate_subset`: the cases with `callable_ == True` are failing, while `callable_ == False` (i.e., the former version of the test, where a UFL expression is used rather than a callable) passes
- `python/test/unit/fem/test_interpolation.py::test_interpolate_callable_subset`: the case `bound == 0.5` fails, while `bound == 1.5` (i.e, the cell subset is actually the whole domain) passes

cc @niravshah241 since this regression may affect his work on shape parametrization/mesh motion

**Comment by jorgensd** [comment]
One thing to note in your tests is that you should scatter_forward after calling interpolation on a subset (not that it is the root cause of the error).

**Comment by garth-wells** [comment]
@jorgensd good catch.
