### ISSUE TITLE
Getting the correct release version

### ISSUE THREAD

**Issue by elnaranjobanjo** [FEniCS/dolfinx#2663]
Hello,
I am looking to install dolfinx version 0.6 and I have installed using: pip install fenics-basix the 0.6 version of basix.

but whenever I run cmake .. from muy build directory in cpp I get the following error:

CMake Error at CMakeLists.txt:192 (find_package):
Could not find a configuration file for package "Basix" that is compatible
with requested version "0.6".

The following configuration files were considered but not accepted:

/usr/lib/x86_64-linux-gnu/cmake/basix/BasixConfig.cmake, version: 0.5.1
/lib/x86_64-linux-gnu/cmake/basix/BasixConfig.cmake, version: 0.5.1

It seems to be looking for it in the wrong place, because when I run pip install fenics-basix I get the following message:
Requirement already satisfied: fenics-basix in /home/seb/.local/lib/python3.10/site-packages (0.6.0).

Can you help me figure out how to get cmake to look for basix in the correct folder?

**Comment by chrisrichardson** [comment]
The easiest way is probably just to delete the 0.5.1 libraries from your system. Can I recommend that you try the fenics discourse forum, you will likely get more help there. https://fenicsproject.discourse.group/
