### ISSUE TITLE
[BUG]: Error: InstallError: /usr/bin/gcc has no Fortran compiler added in spack. Add it or use openblas~fortran!

### ISSUE THREAD

**Issue by prusso630** [FEniCS/dolfinx#2671]
### How to reproduce the bug

I have after running spack install:

Error: InstallError: /usr/bin/gcc has no Fortran compiler added in spack. Add it or use openblas~fortran!

for WSL2 Ubuntu 22.04. 

I tried installing gfortran with buld-essential packages and also f2c. No luck yet, not really sure yet how to fix this...

### Version

0.6.0

### DOLFINx git commit

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dolfinx'

### Installation

spack install

**Comment by jhale** [comment]
As this is related to Spack not dolfinx you would get the best support using Spack's support channels.

On Ubuntu WSL you could simply use our Ubuntu packages (see README.md) for 0.6.0.

**Comment by garth-wells** [comment]
After installing `gfortran`, run
```bash
spack compiler find
```
and then check the output of 
```bash
spack compilers
```
You should now see a fortran compiler listed.

**Comment by prusso630** [comment]
At this point spack is not finding gfortran after spack compiler find and or spack compilers. I also tried spack gcc install and or a variation with --install on WSL2 none of which yet seem to work for WSL2 so I moved on to building just with natively installed Ubuntu to see how things go over there.
