### ISSUE TITLE
[BUG]: ERROR: Could not find a version that satisfies the requirement fenics-basix<0.8.0,>=0.7.0.dev0

### ISSUE THREAD

**Issue by prusso630** [FEniCS/dolfinx#2682]
### How to reproduce the bug

I'm not sure how it would be reproducible yet. I have recent downloads of basicx ffcx and ufl that I am trying to install from source. So far following instructions from here:
https://fenicsproject.discourse.group/t/installation-error-with-ufcx/9086/6

Is this a resolvable conflict somehow?

### Output (Python)

```bash
```
prusso@lenovo:~/ffcx$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/prusso/ffcx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from fenics-ffcx==0.7.0.dev0) (59.6.0)
ERROR: Could not find a version that satisfies the requirement fenics-basix<0.8.0,>=0.7.0.dev0 (from fenics-ffcx) (from versions: 0.4.0, 0.4.2.post1, 0.5.0, 0.6.0)
ERROR: No matching distribution found for fenics-basix<0.8.0,>=0.7.0.dev0
```
```

### Version

main branch

So I tried again a second time with a fresh install of Ubuntu 22.04 and got this one a little bit different conflict:
```
prusso@keniva:~/ffcx$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/prusso/ffcx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from fenics-ffcx==0.7.0.dev0) (59.6.0)
Collecting numpy
  Downloading numpy-1.25.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 32.4 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement fenics-ufl<2023.3.0,>=2023.2.0.dev0 (from fenics-ffcx) (from versions: 2017.1.0.post1, 2017.2.0, 2018.1.0, 2019.1.0, 2022.1.0.post0, 2022.2.0, 2023.1.0, 2023.1.1.post0)
ERROR: No matching distribution found for fenics-ufl<2023.3.0,>=2023.2.0.dev0
```

**Comment by garth-wells** [comment]
This is ffcx, not dolfinx.

Usually If you install a development version of one FEniCS library, you need the development version of the FEniCS dependencies. In this case you need to install the development version of Basix.

It's generally recommended to use the release versions when possible.
