### ISSUE TITLE
[BUG]: complex demo_axis, demo_pml sometimes fails

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/dolfinx#2686]
### How to reproduce the bug

The complex-number python demo in dolfinx 0.6, [demo_axis.py](https://docs.fenicsproject.org/dolfinx/main/python/demos/demo_axis.html),  often (though not always) fails on less common architectures like [armel](https://ci.debian.net/data/autopkgtest/unstable/armel/f/fenics-dolfinx/34904462/log.gz), [armhf](https://ci.debian.net/data/autopkgtest/unstable/armhf/f/fenics-dolfinx/34904463/log.gz), [s390x](https://ci.debian.net/data/autopkgtest/unstable/s390x/f/fenics-dolfinx/34904466/log.gz).

The error is a somewhat larger error in the complex calculated quantities, scattering error 16.9% instead of 0.36%,  extinction error 1.65% instead of 0.40%.  A sample test error from [s390x](https://ci.debian.net/data/autopkgtest/unstable/s390x/f/fenics-dolfinx/34904466/log.gz) is copied below

The demo does not always fail, e.g. armel apparently passed with glibc 2.37 [here](https://ci.debian.net/data/autopkgtest/unstable/armel/f/fenics-dolfinx/34541977/log.gz)  
Other less common architectures pass, such as [ppc64el](https://ci.debian.net/data/autopkgtest/testing/ppc64el/f/fenics-dolfinx/34879669/log.gz)

Could there be assumptions in the complex number code that don't hold on all architectures? There is some Redhat gcc complex number discussion, for instance, at https://bugzilla.redhat.com/show_bug.cgi?id=1918519

### Minimal Example (Python)

[demo_axis.py](https://github.com/FEniCS/dolfinx/blob/v0.6.0/python/demo/demo_axis/demo_axis.py)

### Output (Python)

```bash
1496s =================================== FAILURES ===================================
1496s _____________________ test_demos_mpi[path15-demo_axis.py] ______________________
...
1496s ----------------------------- Captured stdout call -----------------------------
...
1496s Info    : Done meshing 2D (Wall 0.178272s, CPU 0.179425s)
1496s Info    : 2391 nodes 4950 elements
1496s 
1496s The analytical absorption efficiency is 0.9622728008329892
1496s The numerical absorption efficiency is 0.9583126467646697
1496s The error is 0.4115417233960486%
1496s 
1496s The analytical scattering efficiency is 0.07770397394691526
1496s The numerical scattering efficiency is 0.0644973472397121
1496s The error is 16.996076309077182%
1496s 
1496s The analytical extinction efficiency is 1.0399767747799045
1496s The numerical extinction efficiency is 1.0228099940043818
1496s The error is 1.6506888607349703%
1496s ----------------------------- Captured stderr call -----------------------------
1496s Traceback (most recent call last):
1496s   File "/tmp/autopkgtest-lxc.tupamcyj/downtmp/build.4cF/src/python/demo/demo_axis/demo_axis.py", line 696, in <module>
1496s     assert err_sca < 0.01
1496s            ^^^^^^^^^^^^^^
1496s AssertionError
1496s --------------------------------------------------------------------------
```

### Version

0.6.0

### DOLFINx git commit

debian build 0.6.0-2

### Installation

[debian CI](https://ci.debian.net/packages/f/fenics-dolfinx/) test run using debian [builds](https://buildd.debian.org/status/package.php?p=fenics-dolfinx) from official debian buildds ([armel](https://buildd.debian.org/status/fetch.php?pkg=fenics-dolfinx&arch=armel&ver=1%3A0.6.0-2&stamp=1687741167&raw=0), [armfl](https://buildd.debian.org/status/fetch.php?pkg=fenics-dolfinx&arch=armhf&ver=1%3A0.6.0-2&stamp=1687740864&raw=0), [s390x](https://buildd.debian.org/status/fetch.php?pkg=fenics-dolfinx&arch=s390x&ver=1%3A0.6.0-2&stamp=1687739480&raw=0))

### Additional information

- PETSc 3.18  (3.18.6+dfsg1-1)
- OpenMPI 4.1.5 (4.1.5-2)

**Comment by garth-wells** [comment]
See #2556 for an issue with this demo, which might or might not be related.

**Comment by drew-parsons** [comment]
"less common"... got it failing on i386 now
https://ci.debian.net/data/autopkgtest/testing/i386/f/fenics-dolfinx/35412547/log.gz

**Comment by IgorBaratta** [comment]
I'm working on it.
The demo is actually over-complicated and requires some simplifications.
But I'll also review the tolerances used.

**Comment by IgorBaratta** [comment]
I have looked only at `demo_axis`, but I'm thinking that similar enhancements might apply to `demo_pml` as well.
I plan to address these issues and submit a pull request in the next few days.

**Comment by IgorBaratta** [comment]
I haven't reviewed this in a while, but I have a branch where I started addressing some of the issues. 
I'll get back to you soon.
