### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'ffcx'

### ISSUE THREAD

**Issue by prusso630** [FEniCS/dolfinx#2687]
### How to reproduce the bug

If one installs with spack fenics-ffcx is showing as installed by spack of version 0.6.0 so I tried to cmake the cpp folder with fenics-dolfinx 0.6.0 so I have from cmake a dependency is showing missing that spack showing is installed it. So is there maybe a place I can update my CMake and or how to? As it related to:
https://fenicsproject.discourse.group/t/installing-dolfinx-with-spack-on-ubuntu-22-04/11594/13

thanks...

### Minimal Example (Python)

```Python
spack env create fenicsx-env
spack env activate fenicsx-env
spack add fenics-dolfinx@main cflags="-O3" fflags="-O3"
spack install
```

### Output (Python)

```bash
ModuleNotFoundError: No module named 'ffcx'
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find UFCx (missing: UFCX_INCLUDE_DIRS UFCX_VERSION) (Required is
  at least version "0.6")
```

### Version

0.6.0

### Installation

spack env create fenicsx-env
spack env activate fenicsx-env
spack add fenics-dolfinx@main cflags="-O3" fflags="-O3"
spack install

Ubuntu 22.04

### Additional information

Is it possible for me to update cmake somehow that you can show me?

**Comment by garth-wells** [comment]
`spack add fenics-dolfinx@main` installs DOFLINx. It does not install ffcx.

If you want ffcx, add `py-fenics-ffcx@...` to the Spack environment.
