### ISSUE TITLE
[BUG]: MR #2651 broke reading meshtags in C++

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#2701]
### How to reproduce the bug

Before commit https://github.com/FEniCS/dolfinx/commit/547e645bbafb1b3e1965b9e8cb042e17ae6fa59f the following MWE worked fine

```
#include <dolfinx.h>
#include <dolfinx/io/XDMFFile.h>

using namespace dolfinx;

int main(int argc, char *argv[])
{
  init_logging(argc, argv);

  io::XDMFFile meshFile(MPI_COMM_WORLD, "Domain.xdmf", "r");
  auto mesh = std::make_shared<mesh::Mesh<double>>(meshFile.read_mesh(
      fem::CoordinateElement<double>(mesh::CellType::tetrahedron, 1),
      mesh::GhostMode::none, "Grid"));

  mesh->topology_mutable()->create_connectivity(2, 0);
  auto mt_parts = meshFile.read_meshtags(*mesh, "Grid");
}
```

Afterwards, the call to `read_meshtags` causes a runtime error at line 302 here:

https://github.com/FEniCS/dolfinx/blob/547e645bbafb1b3e1965b9e8cb042e17ae6fa59f/cpp/dolfinx/io/HDF5Interface.h#L294-L302

The input file `Domain.xdmf` contains
```
<Xdmf Version="3.0">
<Domain>
<Grid Name="Grid">
    <Geometry GeometryType="XYZ">
        <DataItem DataType="Float" Dimensions="149597 3" Format="HDF" Precision="8">Domain.h5:/data0</DataItem>
    </Geometry>
    <Topology TopologyType="Tetrahedron" NumberOfElements="867273" NodesPerElement="4">
        <DataItem DataType="Int" Dimensions="867273 4" Format="HDF" Precision="8">Domain.h5:/data1</DataItem>
    </Topology>
    <Attribute Name="subdomain" AttributeType="Scalar" Center="Cell">
        <DataItem DataType="Int" Dimensions="867273" Format="HDF" Precision="8">Domain.h5:/data2</DataItem>
    </Attribute>
</Grid>
</Domain>
</Xdmf>
```

### Version

main branch

**Comment by garth-wells** [comment]
Can you post a complete example for reproducing the error?

**Comment by massimiliano-leoni** [comment]
@garth-wells the code above looks quite self-contained to me. Do you want me to attach a mesh file?

**Comment by massimiliano-leoni** [comment]
[Domain.zip](https://github.com/FEniCS/dolfinx/files/11916896/Domain.zip)

Well, I'll attach it anyway, here it is.

**Comment by jorgensd** [comment]
I have the same issue in my tutorial https://github.com/jorgensd/dolfinx-tutorial/blob/dokken/update_release/chapter3/subdomains.py#L242
when running it locally I get the error message stated by @massimiliano-leoni, and my CI is failing: https://github.com/jorgensd/dolfinx-tutorial/actions/runs/5447788733/jobs/9910209673

**Comment by jorgensd** [comment]
"Self-contained" example using gmsh and meshio to generate the xdmf file:
```python
import meshio
import gmsh
from dolfinx.io import XDMFFile

from mpi4py import MPI

gmsh.initialize()
proc = MPI.COMM_WORLD.rank

if proc == 0:
    gmsh.model.occ.addRectangle(0, 0, 0, 1, 0.5, tag=1)
    gmsh.model.occ.synchronize()
    gmsh.model.addPhysicalGroup(2, [1], 1)
    gmsh.model.mesh.generate(2)
    gmsh.write("mesh.msh")
gmsh.finalize()

def create_mesh(mesh, cell_type, prune_z=False):
    cells = mesh.get_cells_type(cell_type)
    cell_data = mesh.get_cell_data("gmsh:physical", cell_type)
    points = mesh.points[:, :2] if prune_z else mesh.points
    out_mesh = meshio.Mesh(points=points, cells={cell_type: cells}, cell_data={"name_to_read": [cell_data]})
    return out_mesh

if proc == 0:
    # Read in mesh
    msh = meshio.read("mesh.msh")
    triangle_mesh = create_mesh(msh, "triangle", prune_z=True)
    meshio.write("mesh.xdmf", triangle_mesh)
MPI.COMM_WORLD.barrier()


with XDMFFile(MPI.COMM_WORLD, "mesh.xdmf", "r") as xdmf:
    mesh = xdmf.read_mesh(name="Grid")
    ct = xdmf.read_meshtags(mesh, name="Grid")
```

**Comment by jorgensd** [comment]
@massimiliano-leoni I don't think this is an actual bug, it is actually a warning that the input mesh_tag is not using the correct dtype (int32). I guess you converted your mesh/mesh_tags with `meshio`?
If yes, one has to slightly adapt the converter:
```python
def create_mesh(mesh, cell_type, prune_z=False):
    cells = mesh.get_cells_type(cell_type)
    cell_data = mesh.get_cell_data("gmsh:physical", cell_type)
    points = mesh.points[:, :2] if prune_z else mesh.points
    out_mesh = meshio.Mesh(points=points, cells={cell_type: cells}, cell_data={"name_to_read": [cell_data.astype(np.int32)]})
    return out_mesh
```

**Comment by massimiliano-leoni** [comment]
@jorgensd you're being quite lenient with what constitutes a bug and what doesn't :P
A warning would be "careful! I'm reading a compatible data type but there could be narrowing/whatever"; this, on the other hand, crashes the simulation.

Anyway, I've adapted my conversion script [thanks for the example!] so I can work around this issue but when this rolls out into stable I imagine a bunch of users will face the same problem.
