### ISSUE TITLE
Revise method name `MatrixCSR::finalize`

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#2710]
The above method name is misleading. After a call to 'finalize', matrix entries can still be changed. The method performs a reverse scatter.

Now that we're using `MatrixCSR` more in demos, we should fix the name before the next release.

**Comment by chrisrichardson** [comment]
`assemble` is also bad. We could use `scatter_reverse` to match Vector. Or `gather_rows` perhaps?

**Comment by garth-wells** [comment]
`assemble` is widely used - PETSc and Tpetra use it.

**Comment by chrisrichardson** [comment]
I think Tpetra uses `fillComplete`

**Comment by IgorBaratta** [comment]
I think it should have a name that clearly indicates that it's performing some communication.
`assemble` or `fillComplete` don't convey this meaning for me.

**Comment by jhale** [comment]
Reconcile?
