### ISSUE TITLE
Assess switch from pybind11 to nanobind

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#2712]
There may be benefits to switching from pybind11 to nanobind (https://github.com/wjakob/nanobind).

This will require a careful assessment, and the blockers resolved.

**Comment by garth-wells** [comment]
See https://github.com/wjakob/nanobind/pull/292 on support for complex.

**Comment by chrisrichardson** [comment]
Const is still a pain

**Comment by wjakob** [comment]
I just saw this issue because of a mention in the nanobind repo. Just to clarify: pybind11 handles `shared_ptr<const...>` and nanobind does not? 

(If so, note that neither of these two frameworks honors const-ness, so this will likely not do what you want even for the pybind11 side.)

**Comment by chrisrichardson** [comment]
@wjakob. Yes. It is just an interfacing and convenience issue. Clearly python does not generally care about const (though I guess numpy has some idea). 
The problem is we are wrapping functions with signatures including e.g. `vector<vector<const Foo>>` as input args. Now we have to unwrap/copy everything and write a lambda. Not impossible, just more laborious. pybind seems to conveniently just ignore the const.

**Comment by wjakob** [comment]
The `shared_ptr` issue should now be fixed on the master branch: https://github.com/wjakob/nanobind/commit/21ee32b714dd96af1b5c42d43a3129eb3084ad08

**Comment by garth-wells** [comment]
> `std::complex<T>` is supported as of the latest release.

Thanks @wjakob. Does `nb::ndarray` support complex floats?

**Comment by chrisrichardson** [comment]
I've updated the branch  https://github.com/FEniCS/dolfinx/tree/nanobind to sync with main.
I think `shared_ptr` may be now OK. Complex numbers are in nanobind for STL,  but we still need `ndarray` to support `std::complex`.

**Comment by wjakob** [comment]
Another user has made a PR about this exact feature ;) -> https://github.com/wjakob/nanobind/pull/319 (not sure if it's related to FEniCS)

**Comment by chrisrichardson** [comment]
Thanks for the heads-up @wjakob. I think they are looking for alien life (SETI Institute), which is a bit outside of our domain.

**Comment by luigifcruz** [comment]
I mean, FEniCS can be useful for radio astronomy too! 😄 

Just as a clarification, my PR (https://github.com/wjakob/nanobind/pull/319) was written for the Python bindings of [BLADE](https://github.com/luigifcruz/blade), a GPU-accelerated software being used as the DSP-backend on the Allen Telescope Array for astronomy and SETI purposes.

**Comment by wjakob** [comment]
Thanks to @luigifcruz, this is now merged 🎉 . I just pushed out nanobind 1.7.0 with this change.

**Comment by garth-wells** [comment]
Thanks @luigifcruz, thanks @wjakob!

**Comment by garth-wells** [comment]
Switch (almost?) complete in #2820. Can be merged once new nanobind release made.
