### ISSUE TITLE
[BUG]: Scotch Partitioner not working

### ISSUE THREAD

**Issue by JaviLGPKE** [FEniCS/dolfinx#2716]
### How to reproduce the bug

I am running a larger program that runs perfectly well both in series and in parallel, with no patitioner. I am trying to reduce run time by trying out a partitioner, I decided to use the scotch partitioner as it seems it's the only one that managed to install correcly.
However when i try to run with it, it seems to only show me the connectivity, claiming incompatible function arguments.

### Minimal Example (Python)

```Python
import dolfinx as dfx
from mpi4py import MPI

mesh = dfx.mesh.create_interval(MPI.COMM_WORLD, 30, [0,1], dfx.mesh.GhostMode.shared_facet, dfx.graph.partitioner_scotch)
```

### Output (Python)

```bash
Traceback (most recent call last):
  File "/home/javi/cidetec/temp/MPI/Partitioner/test_mesh_partitioner.py", line 18, in <module>
    mesh = dfx.mesh.create_interval(comm, 30, [0,1], dfx.mesh.GhostMode.shared_facet, dfx.graph.partitioner_scotch)
  File "/usr/local/dolfinx-real/lib/python3.10/dist-packages/dolfinx/mesh.py", line 338, in create_interval
    mesh = _cpp.mesh.create_interval(comm, nx, points, ghost_mode, partitioner)
TypeError: partitioner_scotch(): incompatible function arguments. The following argument types are supported:
    1. (imbalance: float = 0.025, seed: int = 0) -> Callable[[MPICommWrapper, int, dolfinx.cpp.graph.AdjacencyList_int64, bool], dolfinx.cpp.graph.AdjacencyList_int32]

Invoked with: <mpi4py.MPI.Intracomm object at 0x7f86d5427fd0>, 1, 1, <AdjacencyList> with 30 nodes
  0: [0 1 ]
  1: [1 2 ]
  2: [2 3 ]
  3: [3 4 ]
  4: [4 5 ]
  5: [5 6 ]
  6: [6 7 ]
  7: [7 8 ]
  8: [8 9 ]
  9: [9 10 ]
  10: [10 11 ]
  11: [11 12 ]
  12: [12 13 ]
  13: [13 14 ]
  14: [14 15 ]
  15: [15 16 ]
  16: [16 17 ]
  17: [17 18 ]
  18: [18 19 ]
  19: [19 20 ]
  20: [20 21 ]
  21: [21 22 ]
  22: [22 23 ]
  23: [23 24 ]
  24: [24 25 ]
  25: [25 26 ]
  26: [26 27 ]
  27: [27 28 ]
  28: [28 29 ]
  29: [29 30 ]
```

### Version

main branch

### Installation

I am using the dolfinx/dolfinx:latest image on docker desktop.

**Comment by garth-wells** [comment]
Try 
```python
mesh = dfx.mesh.create_interval(MPI.COMM_WORLD, 30, [0,1], dfx.mesh.GhostMode.shared_facet, dfx.graph.partitioner_scotch())
```
(note the `()` at the end of `partitioner_scotch`.

`partitioner_scotch` is a function and not a property - it can take arguments.

**Comment by JaviLGPKE** [comment]
I tried this change on create_interval {and a create_box: mesh2 = dfx.mesh.create_box(comm=MPI.COMM_WORLD, points=[(0, 0 , 0), (3, 1, 1)], n=[30, 10, 10], partitioner=dfx.graph.partitioner_scotch()) } but it triggers the same error.

**Comment by jorgensd** [comment]
You need to wrap the scotch partitioner
```python

partitioner = dolfinx.mesh.create_cell_partitioner(partitioner_scotch())
mesh2 = dfx.mesh.create_box(comm=MPI.COMM_WORLD, points=[(0, 0 , 0), (3, 1, 1)], n=[30, 10, 10], partitioner= partitioner)
```

I've made some examples to illustrate the usage at https://jsdokken.com/dolfinx_docs/meshes.html
