### ISSUE TITLE
[BUG]: Commit 08006c48e81ccdcd27700bce0bc9ea0c7dc93fcb breaks parallel solve

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#2719]
### How to reproduce the bug

In commit 08006c48e81ccdcd27700bce0bc9ea0c7dc93fcb some lines were removed from `cpp/dolfinx/la/petsc.cpp` that perform a ghost update [see screenshot] but I don't see this update showing up anywhere else in the commit.
I noticed that, without those lines, one of my pieces of code [contact mechanics] crashes while solving some fixed-point problems with "PETSc has generated inconsistent data" which is consistent with ghost values not being updated.

![image](https://github.com/FEniCS/dolfinx/assets/12351309/81ab9944-724c-4c8c-87b8-33b71dba6b8a)

I attach a small C++ program that shows different behaviours when run in serial [works] and in parallel [crashes].
[contactMWE.zip](https://github.com/FEniCS/dolfinx/files/12002649/contactMWE.zip)

### Version

main branch

### DOLFINx git commit

08006c48e81ccdcd27700bce0bc9ea0c7dc93fcb

### Installation

Compiled by me

**Comment by garth-wells** [comment]
Your code is not going a forward scatter to update the ghost values after the linear solve. There should be a forward scatter for `u` after line 242 of `catheterEvoNLTargetForce.cpp` if you're going to use ghost entries.

The code starting at line 245 operates on owned and ghost entries, but the ghosts haven't been updated.

**Comment by massimiliano-leoni** [comment]
Thanks for the explanation! I understand the issue now.
On the other hand, in the Poisson demo we don't see that because after the solve it only outputs to file and it doesn't need the ghost values for that, right?

This is quite subtle, anyway, and maybe we can add a line of documentation somewhere.

If it's intended that the user take care of this manually, then this issue can be closed!

**Comment by garth-wells** [comment]
The demos are missing a forward scatter for the IO to be correct, see #2722.

**Comment by massimiliano-leoni** [comment]
Got it, thanks!
