### ISSUE TITLE
Add support for cell-wise data in ADIOS2 output

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#2720]
### Describe new/missing feature

In the current source code we throw an error complaining that VTK does not support cell data

https://github.com/FEniCS/dolfinx/blob/e561c6cdbb3712d73e42699044acc5ed6ac43c0b/cpp/dolfinx/io/ADIOS2Writers.h#L898-L905

which _used_ to be true. However, a few months ago this changed as the Merge Request https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7401 in VTK was accepted.

At this point we should implement the missing functionality.

**Comment by jorgensd** [comment]
It is not yet in a released version of Paraview (as far as Im aware). However, i agree that once  there is a binary with the support we should implement this.

**Comment by massimiliano-leoni** [comment]
My compiled version of Paraview is a binary that supports it.

**Comment by massimiliano-leoni** [comment]
I compile `master` and in any case I will compile whatever it takes to get that feature :D
