### ISSUE TITLE
[BUG]: Problems with demo_pml

### ISSUE THREAD

**Issue by alberto-battistel** [FEniCS/dolfinx#2737]
### How to reproduce the bug

I ran the demo_pml.py from the current version (0.7) and it gives the error:

> ModuleNotFoundError: No module named 'basix.ufl'

If I download and run the demo_pml.py from the version 0.6.0 it gives the error:

> ImportError: cannot import name 'VTXWriter' from 'dolfinx.io' (/usr/lib/petsc/lib/python3/dist-packages/dolfinx/io/__init__.py)

I am on ubuntu on WSL.
I have installed following the instruction with the ppa
`dpkg -l fenicsx`
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version               Architecture Description
+++-==============-=====================-============-============================================
ii  fenicsx        2:0.6.0.4~ppa1~jammy1 all          Automated Solution of Differential Equations
```

### Output (Python)

```bash
ModuleNotFoundError                       Traceback (most recent call last)
~/new 2.py in <module>
     35
     36 import ufl
---> 37 from basix.ufl import element
     38 from dolfinx.fem.petsc import LinearProblem
     39 from dolfinx.io import VTXWriter, gmshio

ModuleNotFoundError: No module named 'basix.ufl'


or


ImportError                               Traceback (most recent call last)
~/demo_pml.py in <module>
     34 from typing import Tuple, Union
     35
---> 36 from dolfinx.io import VTXWriter, gmshio
     37 from efficiencies_pml_demo import calculate_analytical_efficiencies
     38 from mesh_wire_pml import generate_mesh_wire

ImportError: cannot import name 'VTXWriter' from 'dolfinx.io' (/usr/lib/petsc/lib/python3/dist-packages/dolfinx/io/__init__.py)
```

### Version

main branch

### DOLFINx git commit

`python3 -c 'import dolfinx; print(dolfinx.common.git_commit_hash)'`
gives:

> ubuntu

### Installation

Installed with 

`add-apt-repository ppa:fenics-packages/fenics
apt update
apt install fenicsx`

on ubuntu on a WSL2 on Windows 10

**Comment by francesco-ballarin** [comment]
The issue should be fixed now that 0.7.0 has been released. If that is not the case, feel free to reopen this issue.
