### ISSUE TITLE
[BUG]: "Basix" requested version 0.7 but latest is 0.6

### ISSUE THREAD

**Issue by ludoic** [FEniCS/dolfinx#2739]
### How to reproduce the bug

I ran pip install fenics-basix to install basix, which result in installation of version 0.6

While installing dolfinx from source, cmake tells me "Basix" requested version is 0.7

### Version

main branch

**Comment by francesco-ballarin** [comment]
If you want to install `dolfinx` from the current `main` branch, then you should also install `basix` from its current `main` branch. This would get you the yet unreleased version 0.7 of `basix`, see
https://github.com/FEniCS/dolfinx/blob/main/python/setup.py#L14
