### ISSUE TITLE
AttributeError: 'LinearProblem' object has no attribute '_solver'

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#2757]
### How to reproduce the bug

I'm getting this error on the Basix CI when running the `demo_pml.py` demo.

### Output (Python)

See https://github.com/FEniCS/basix/actions/runs/6094169143/job/16535151559?pr=682

### Version

main branch

**Comment by mscroggs** [comment]
I've opened a dummy PR to test if this fails everywhere: https://github.com/FEniCS/dolfinx/pull/2756

**Comment by jorgensd** [comment]
This is usually related to an earlier error, that causes the shutdown of LinearProblem to fail

**Comment by mscroggs** [comment]
> This is usually related to an earlier error, that causes the shutdown of LinearProblem to fail

Just came to the same conclusion.

Looks like the underlying error is in the petsc wrappers:

```
TypeError: create_matrix(): incompatible function arguments. The following argument types are supported:
    1. (a: dolfinx.cpp.fem.Form_float64, type: str = '') -> mat

Invoked with: <dolfinx.cpp.fem.Form_complex128 object at 0x7f620649fa30>
```

It looks to me like only real versions of the petsc functions are currently wrapped, so complex assembly is causing an issue

**Comment by jorgensd** [comment]
You cannot wrap both real and complex mode petsc at the same time. These demos should only be executed with complex mode. It should exit at: https://github.com/FEniCS/dolfinx/blob/main/python/demo/demo_pml/demo_pml.py#L51-L53 if you have real mode  petsc compiled with dolfinx

**Comment by jorgensd** [comment]
Seems like you are actually building against dolfinx complex mode: https://github.com/FEniCS/basix/actions/runs/6094169143/workflow?pr=682#L32 thus the python binding on the DOLFINx side seems wrong.

**Comment by mscroggs** [comment]
Might be that the complex issue on only local. I'm getting a different error on CI (https://github.com/FEniCS/dolfinx/actions/runs/6095574531/job/16539428071?pr=2756) which looks related to dolfinx/ffcx#602

**Comment by mscroggs** [comment]
Looks like https://github.com/FEniCS/ffcx/pull/604 might fix this
