### ISSUE TITLE
Deprecate VectorFunctionSpace

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#2759]
Instead of having VectorFunctionSpace, we should allow FunctionSpace to accept a `rank` and/or `shape` argument like the function `basix.ufl.element` (https://github.com/FEniCS/basix/blob/c02294f58b363ee6e7d35e5fc6c2a48996350c09/python/basix/ufl.py#L1590-L1619)

**Comment by garth-wells** [comment]
Fixed by PR #2766.
