### ISSUE TITLE
Rename `create_adjacencylist` to `adjacency_list`

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#2760]

**Comment by IgorBaratta** [comment]
or to `adjacency_list`?

**Comment by garth-wells** [comment]
> or to `adjacency_list`?

I think without underscore is better - otherwise we would need `function_space` rather than `functionspace`, `sparsity_pattern`, etc, throughout. For me, the underscore doesn't make anything clearer but does add more visual noise.
