### ISSUE TITLE
Assembly tests failing for float32

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#2762]
### How to reproduce the bug

fem/test_assmbler.py and fem/test_custom_assembler are currently failing (see https://github.com/FEniCS/dolfinx/actions/runs/6098503708/job/16548469123?pr=2761)

### Output (Python)
eg
```bash
FAILED python/test/unit/fem/test_assembler.py::test_basic_assembly_constant[mode0] - assert 1.604281465006352e-06 == 0.0 ± 1.0e-06
  comparison failed
  Obtained: 1.604281465006352e-06
  Expected: 0.0 ± 1.0e-06
```

### Version

main branch

**Comment by garth-wells** [comment]
What changed to trigger this CI failure?

**Comment by mscroggs** [comment]
I think something FFCx, hence why I opened https://github.com/FEniCS/ffcx/issues/607

**Comment by garth-wells** [comment]
@chrisrichardson is this expected with your FFCx changes? Has the code body for kernels changed?

**Comment by chrisrichardson** [comment]
It could be, yes. I changed the precision for table output for float, but maybe it is not quite enough decimal places.

**Comment by mscroggs** [comment]
https://github.com/FEniCS/ffcx/pull/608 should solve this issue
