### ISSUE TITLE
Remove deprecated `fem.FunctionSpace` function

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#2767]
And rename `FunctionSpaceBase` -> `FunctionSpace`.

**Comment by francesco-ballarin** [comment]
Would it be a good idea to do this immediately after https://github.com/FEniCS/ufl/pull/197 is merged?

My rationale is that I will probably have to go through my codes and double check that every single time I create a function space I do not use `ufl.legacy` elements anymore (and replace them with `basix` ones, if I were not using them already). If this case change were enforced while I was already doing these checks, in a single pass I would be killing two birds with one stone.

**Comment by mscroggs** [comment]
> Would it be a good idea to do this immediately after [FEniCS/ufl#197](https://github.com/FEniCS/ufl/pull/197) is merged?

This seems like a sensible approach to me

**Comment by francesco-ballarin** [comment]
OK, I'll do this after #2784 is merged.
