### ISSUE TITLE
Clearer explaination of how `grad` works on `vector`-elements

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2792]
### Describe new/missing feature

Now that we have deprecated usage of `vector`-elements, and only sending in shape, we should carefully document how this works with ufl and `div`, `grad` etc.

**Comment by garth-wells** [comment]
@jorgensd Unless you're willing to do this I don't think this issue will be addressed. It's not great having non-bug issues hanging around, so would be better to close unless it will be addressed asap.

**Comment by jorgensd** [comment]
Feel free to close it then. I dont have bandwidth to add that atm.
