### ISSUE TITLE
[BUG]: Install from source and required Basix version

### ISSUE THREAD

**Issue by LucasPa** [FEniCS/dolfinx#2805]
### How to reproduce the bug

Hello,

I try to install dolfinx from the source with cmake. But CMakeLists.txt requires Basix version >= 0.7 while the latest release at https://github.com/FEniCS/basix is the 0.6. Isn't that an error in the CMakeList.txt file ?

Best,

Lucas

### Version

main branch

**Comment by francesco-ballarin** [comment]
If you install `dolfinx` from source (i.e., cloning the github repository), then you should install all FEniCSx components (in particular, `basix` and `ffcx`) from source by cloning their respective repositories. That will give you version `0.7` for all required components.

**Comment by jorgensd** [comment]
Cloning a github repository will set the repository at the state of the default branch. The default branch of Basix is `main`, which is were development is happening.

If you want to change this to the 0.6.0 release you can call `git checkout v0.6.0` inside the repository, or call
`git clone --branch v0.6.0 --single-branch https://github.com/FEniCS/basix.git` to only clone the 0.6.0 branch
