### ISSUE TITLE
recommended aur (Arch) library

### ISSUE THREAD

**Issue by ng0177** [FEniCS/dolfinx#2811]
### Describe new/missing feature

The following items exist among others. Which is recommended? A hint in Readme could be useful.

```
3 aur/basix-git 0.7.0.dev0_r934.571d504-3 (+0 0.00) 
    FEniCS finite element basis evaluation library
2 aur/basix 0.7.0-1 (+2 0.00) 
    FEniCS finite element basis evaluation library
1 aur/fenics-basix-git 0.7.0.dev0_r945.1117a8d-1 (+0 0.00)
```

**Comment by francesco-ballarin** [comment]
IMHO, you should be installing `python-fenics-dolfinx`, which will pull in the appropriate `basix` version out of the three that you mentions.

Keep in mind that those aur packages are not managed by us. There seem to be two different maintainers (`rmsc` and `carlosal1015`), try to get in touch with both of them to have them explain why there are three different packages.

**Comment by ng0177** [comment]
Thanks! I guess the names are just synonyms. Comment added. https://aur.archlinux.org/packages/python-fenics-dolfinx#comment-937260
