### ISSUE TITLE
add `dolfinx.fem.FunctionSpace.basix_element`

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#2817]
I went through my codes in preparation of #2784, and replaced a few occurences of `VectorElement` and `MixedElement` instances with `basix.ufl` elements.

One thing that I found odd is that to define a `basix.ufl` element I used `dolfinx.mesh.Mesh.basix_cell` instead of `dolfinx.mesh.Mesh.ufl_cell`, but to extract the resulting element from a `dolfinx.fem.FunctionSpace` I had to use `dolfinx.fem.FunctionSpace.ufl_element`, even if the element was actually created through `basix`.

Would it make sense to have both a `dolfinx.fem.FunctionSpace.basix_element` and `dolfinx.fem.FunctionSpace.ufl_element` function/property, similarly to the pair `dolfinx.mesh.Mesh.basix_cell` and `dolfinx.mesh.Mesh.ufl_cell`?

**Comment by mscroggs** [comment]
The Basix and UFL elements of a space should now be the same, so we could just rename `FunctionSpace.basix_element` to `FunctionSpace.element`

**Comment by francesco-ballarin** [comment]
> so we could just rename `FunctionSpace.basix_element` to `FunctionSpace.element`

I am not sure if I should interpret this as:
1) "I'd like to amend your proposal, and add `FunctionSpace.element` instead of `FunctionSpace.basix_element`." That would still be less confusing for me then querying `FunctionSpace.ufl_element`, so I'd be happy anyways with the slightly different name, or
2) rename `FunctionSpace.ufl_element` (i.e., the only property/method who is actually there right now) to `FunctionSpace.element`. I'd be happy with that too, but since that method comes in by inheritance https://github.com/FEniCS/ufl/blob/e1e8e5627b0c7db17687bdb32857820ac4ddc072/ufl/functionspace.py#L66, having to change that in `ufl` will surely disrupt `firedrake`, for instance.


While preparing this answer, I realized that there actually is already an `element` property
https://github.com/FEniCS/dolfinx/blob/main/python/dolfinx/fem/function.py#L659
* Can it be safely used instead of every call to `ufl_element`?
(in particular, it seems to me that it returns the C++ object, and not some python wrapped version of it). 
* Would using this property (or a similar one) be the suggested way in future to interact with the underlying element?
(Most cases I encountered four days ago while opening the original post were very simple, like determining the name of the family, the degree, the shape of the family, ...)

**Comment by francesco-ballarin** [comment]
> Perhaps the current name ufl_element isn't too bad, and future-proofs us against any work to allow the use elements not from Basix (not that I know of any plans to do this).

OK! I'll keep this open for a few more days in case anyone else wants to add their comment. If no further comments are added on this, at some point next week I'll close this as not planned.

**Comment by francesco-ballarin** [comment]
No further comments in the last 5 days. We reached the agreement to keep the existing name.
