### ISSUE TITLE
Is fiddling with dl open flags still needed in `dolfinx/__init__.py`?

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#2835]
See https://github.com/FEniCS/dolfinx/blob/main/python/dolfinx/__init__.py#L10-L25

`git blame` says it came in 6 years ago when `pybind11` wrappers were first prepared for `dolfin`. 

Around six months ago I realized that this was causing problems on Colab, and have a patch in https://github.com/fem-on-colab/fem-on-colab/blob/main/fenicsx/patches/06-do-not-fiddle-with-dlopenflags-in-dolfinx to drop it when packaging there.

With the wrappers moving from `pybind11` to `nanobind`, now seems a good time to raise this issue.

**Comment by garth-wells** [comment]
From memory, it was for Numpy and how it links with BLAS/Lapack.
