### ISSUE TITLE
ParMETIS not found when building `dolfinx` with `docker/Dockerfile.end-user`

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#2845]
While testing #2844 I noticed the following while `cmake` is run on the `cpp` part.

```
#17 3.780 -- The following RECOMMENDED packages have not been found:
#17 3.780 
#17 3.780  * ParMETIS (required version >= 4.0.2), Parallel Graph Partitioning and Fill-reducing Matrix Ordering, <http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview>
#17 3.780    Parallel graph partitioning
#17 3.780 
```

Is this on purpose? It seems odd that the end user image does not have a package which is recommended by ourselves.

**Comment by garth-wells** [comment]
ParMETIS has a restrictive license; we're not permitted to (re-)distribute it.
