### ISSUE TITLE
Reduce number of build threads in Docker end-user image builds

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#2861]
### Describe new/missing feature

Using ninja on a 4-core 6GB arm64 instance leads to a crash in the pybind11/Python build. Increasing the instance size to 8-cores works.

Reducing the number of build threads used by ninja on the 4-core instance will probably fix the issue.

**Comment by garth-wells** [comment]
`nanobind` will likely fix this.

**Comment by jhale** [comment]
Indeed. That's why I hold off as it's easier to let ninja do its thing on build threads.

**Comment by garth-wells** [comment]
Working after nanobind switch.

**Comment by francesco-ballarin** [comment]
After #2894 #2895 #2896, this is happening again. I have temporarily increased back the number of cores to 8 in #2897, but that change needs to be reverted at some point to avoid doubling the charge on every nightly run.

**Comment by garth-wells** [comment]
Let's not waste human time on this.
