### ISSUE TITLE
Regression in Python `assemble_vector` performance after nanobind migration

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2891]
### How to reproduce the bug

Using a quite simple linear form with a mixed element

### Minimal Example (Python)

```Python
from dolfinx import fem, mesh as dmesh
import basix.ufl
from mpi4py import MPI
import ufl
import time

degree = 1
mesh = dmesh.create_unit_square(MPI.COMM_WORLD, 1000, 1000)

cell = mesh.ufl_cell()
FE = basix.ufl.element("Lagrange", str(cell), degree)
ME = basix.ufl.mixed_element([FE, FE])
VQ = fem.functionspace(mesh, ME)

# Define test, trial and functions for previous timestep
Az, V = ufl.TrialFunctions(VQ)
vz, q = ufl.TestFunctions(VQ)
dx = ufl.Measure("dx", domain=mesh)
L = vz * dx
cpp_L = fem.form(L)
b = fem.create_vector(cpp_L)

start = time.perf_counter()
fem.assemble_vector(b.array, cpp_L)
end = time.perf_counter()
print(end - start)

```

### Output (Python)

```bash
ghcr.io/fenics/dolfinx/dolfinx:nightly gives: 1.091861698001594
ghcr.io/fenics/dolfinx/dolfinx:v0.7.2 gives: 0.03441590800139238
```

### Version

main branch

### DOLFINx git commit

a7fa17b9914564e4672ccb25a3fae7d9f6944aeb

### Installation

Using docker

**Comment by jorgensd** [comment]
Even an issue without mixed elements:
```python
from dolfinx import fem, mesh as dmesh
import basix.ufl
from mpi4py import MPI
import ufl
import time

degree = 1
mesh = dmesh.create_unit_square(MPI.COMM_WORLD, 1000, 1000)

cell = mesh.ufl_cell()
FE = basix.ufl.element("Lagrange", str(cell), degree)
VQ = fem.functionspace(mesh, FE)

# Define test, trial and functions for previous timestep
Az = ufl.TrialFunction(VQ)
vz = ufl.TestFunction(VQ)
dx = ufl.Measure("dx", domain=mesh)
L = vz * dx
cpp_L = fem.form(L)
b = fem.create_vector(cpp_L)
start = time.perf_counter()
fem.assemble_vector(b.array, cpp_L)
end = time.perf_counter()
print(end - start)
```
Main: 1.004702399000962
0.7.2: 0.034690725999098504

**Comment by jorgensd** [comment]
Even removing the constants/coeff packing, we still have this issue
```python
from dolfinx import fem, mesh as dmesh
import basix.ufl
from mpi4py import MPI
import ufl
import time

degree = 1
mesh = dmesh.create_unit_square(MPI.COMM_WORLD, 1000, 1000)

cell = mesh.ufl_cell()
FE = basix.ufl.element("Lagrange", str(cell), degree)
VQ = fem.functionspace(mesh, FE)

# Define test, trial and functions for previous timestep
Az = ufl.TrialFunction(VQ)
vz = ufl.TestFunction(VQ)
dx = ufl.Measure("dx", domain=mesh)
L = vz * dx
cpp_L = fem.form(L)
b = fem.create_vector(cpp_L)
coeffs = fem.assemble.pack_coefficients(cpp_L._cpp_object)
consts = fem.assemble.pack_constants(cpp_L._cpp_object)
start = time.perf_counter()
fem.assemble_vector(b.array, cpp_L, constants=consts, coeffs=coeffs)
end = time.perf_counter()
print(f"timing: {end - start:.5e}")
```
dolfinx:nightly: 1.00991e+00
dolfinx:v0.7.2: 3.20099e-02
test-env with main branch(nanobind 1.7.0):  6.58801e-02
test-env with main branch(nanobind 1.8.0): 6.52372e-02
```
Note that when running the code in the nightly image, I also get tons of leakage warnings from nanobind, that I don't get from the version used with test-env

**Comment by francesco-ballarin** [comment]
I am afraid that this another side of the same coin of https://github.com/FEniCS/dolfinx/issues/2884

**Comment by jorgensd** [comment]
> I am afraid that this another side of the same coin of #2884

I can confirm that the regression was introduced with nanobind.
I tried the commit prior to nanobind  (8982eb7848959d1fb93df789154f63ea9b48348c), and the one with nanobind(0edd19f3cbed5d9acc911610aef4703410123dad):
https://gist.github.com/jorgensd/6ed3d206c572312ff756a22af8e43be2
where the runtime has gone from 6.18358e-01 to 1.16190e+00

**Comment by IgorBaratta** [comment]
Maybe it's a stupid question, but what has changed between `test-env` and `dolfinx:nightly`? (int python world)

**Comment by jorgensd** [comment]
> Maybe it's a stupid question, but what has changed between `test-env` and `dolfinx:nightly`? (int python world)

That is also a good point. I'm not sure what has changed.

But note that the runtime with the test-env is twice the time of the v0.7.2 release.

There are clearly multiple issues here,

1. How to make the nanobind wrappers as fast as pybind
2. What has changed in the nightly image compared to using the test-envs.

**Comment by francesco-ballarin** [comment]
> Maybe it's a stupid question, but what has changed between `test-env` and `dolfinx:nightly`? (int python world)

`test-env` gets updated in https://github.com/FEniCS/dolfinx/blob/main/.github/workflows/docker-dev-test-env.yml alongside `dev-env`. The way I read that file, the only difference between `test-env` and `dev-env` are some `-g` flags, but `dev-env` is more favorable (no debugging flags) than `test-env`.

Then, the `dev-env` image gets used to build the `nightly` one in https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile.end-user#L43

There are some minor differences between the `pip install` calls in https://github.com/FEniCS/dolfinx/blob/main/.github/workflows/ccpp.yml and https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile.end-user, but nothing major that in my opinion justifies such an astonishing difference in performance.

**Comment by jorgensd** [comment]
The issues now are just the bindings, as I get the timings:
```bash
8982eb7848959d1fb93df789154f63ea9b48348c: 3.56381e-01
0edd19f3cbed5d9acc911610aef4703410123dad: 6.66175e-01
```
with the same ffcx, ufl, basix setup and same build flags.

**Comment by jhale** [comment]
Does the assembly time scale with the number of degrees of freedom? i.e. is this a fixed or scaled overhead?

**Comment by garth-wells** [comment]
On my mac with `main` and code in https://github.com/FEniCS/dolfinx/issues/2891#issuecomment-1814775624: 0.029670500000065658

**Comment by jorgensd** [comment]
> On my mac with `main` and code in [#2891 (comment)](https://github.com/FEniCS/dolfinx/issues/2891#issuecomment-1814775624): 0.029670500000065658

And what if you run with pybindings? 
Your mac is probably faster than my computer;)

**Comment by IgorBaratta** [comment]
On my laptop I get:
- 8982eb7848959d1fb93df789154f63ea9b48348c pybind: 1.36079e+00 
- 0edd19f3cbed5d9acc911610aef4703410123dad nanobind: 3.66675e+00


Code and commits in Jørgen's gist: https://gist.github.com/jorgensd/6ed3d206c572312ff756a22af8e43be2

**Comment by chrisrichardson** [comment]
I tried with spack (which should provide consistent optimisation levels):
0.7.1: 4.10828e-01
main: 9.37570e-01

So, it seems like there is a fairly consistent factor of about 2, for this code snippet.

**Comment by chrisrichardson** [comment]
The solution is actually quite simple: we need to add `NOMINSIZE` to the `nanobind_add_module` CMake command. Currently, it is applying `-Os` which removes a lot of optimisations. Now I get:
2f53e74871f331b49bfc52af48be6629bd3b43ef: 3.84504e-01
So, actually faster than with pybind on 0.7.1 (cf above) - 0.7.1: 4.10828e-01

**Comment by jorgensd** [comment]
On my old laptop at home with the change @chrisrichardson  suggests
bash
```
10x10
0edd19f3cbed5d9acc911610aef4703410123dad: 1.82894e-04
8982eb7848959d1fb93df789154f63ea9b48348c: 2.54654e-04

100 x 100
0edd19f3cbed5d9acc911610aef4703410123dad: 6.99340e-03
8982eb7848959d1fb93df789154f63ea9b48348c: 6.97239e-03

1000 x 1000
0edd19f3cbed5d9acc911610aef4703410123dad: 5.76017e-01
8982eb7848959d1fb93df789154f63ea9b48348c: 6.55088e-01
```
which indeed is faster than the pybind code.
@chrisrichardson do you want to make a PR fixing the binding?
