### ISSUE TITLE
[BUG]: Pyvista nd Fenicsx issue

### ISSUE THREAD

**Issue by chams333** [FEniCS/dolfinx#2941]
### Summarize the issue

Pyvista crashes the kernel when running basic tutorial examples https://jsdokken.com/dolfinx-tutorial/chapter1/fundamentals_code.html. After several investigating the behaviour of pyvista with Fenicsx, I found that when I add the following code at the beginning, the kernel does not crash and the tutorial code runs correctly.
`import pyvista `
`from pyvista import demos `
`pyvista.start_xvfb()`
`demos.plot_wave()`

### How to reproduce the bug

I install fenicsx using the steps described below, then I run the tutorial from https://jsdokken.com/dolfinx-tutorial/chapter1/fundamentals_code.html

### Version

0.7.2

### Installation

install WSL
install Ubuntu
run the ubuntu app

- the file systemm seen from ubuntu app
cd /mnt/d/Python/Fenicsx

- download the Anaconda installer for linux from 
wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"

- verify the Anaconda install file integrity
shasum -a 256 "Miniconda3-latest-Linux-x86_64.sh"

- install Anaconda
bash Miniconda3-latest-Linux-x86_64.sh

cd /mnt/d/Python/Fenicsx
conda create -n fenicsx-env
conda activate fenicsx-env
conda config --append channels conda-forge
conda install -c conda-forge fenics-dolfinx mpich 

- install Jupyter
pip install jupyter
pip install pyvista[all]
pip install ipywidgets
pip install ipympl

- install gmsh
sudo apt-get install gmsh
pip install gmsh

- open a jupyter notebook
jupyter lab --NotebookApp.token='' --no-browser --port=8888  --notebook-dir=/mnt/d/Python/Fenicsx/code --preferred-dir=/mnt/d/Python/Fenicsx/code

**Comment by francesco-ballarin** [comment]
This is an installation support query, and https://github.com/FEniCS/dolfinx/issues/new/choose clearly states to use discourse for that. Closing.
