### ISSUE TITLE
[BUG]: Do not always strip debug symbols from python bindings

### ISSUE THREAD

**Issue by fmonteghetti** [FEniCS/dolfinx#2948]
### Summarize the issue

Step 3 of the build instructions in [README.md](https://github.com/FEniCS/dolfinx/tree/main/python/README.md) do not produce debug symbols in the python bindings. 

Similarly, even when `DOLFINX_CMAKE_BUILD_TYPE="Debug"` in [Dockerfile.end-user](https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile.end-user), the produced python bindings have no debug symbols.

This prevents from debugging both C++ and Python simultaneously (even when the C++ lib has debug symbols).

### How to reproduce the bug

Build [Dockerfile.end-user](https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile.end-user) with `DOLFINX_CMAKE_BUILD_TYPE="Debug"` using the main branch of dolfinx.
Run:
```
objdump -h /usr/local/lib/python3.10/dist-packages/dolfinx/cpp.cpython-310-x86_64-linux-gnu.so 
```
and notice that no debug symbols are present.

### Version

main branch

### Additional information

The provided [CMakeLists.txt](https://github.com/FEniCS/dolfinx/blob/main/python/CMakeLists.txt) can produce debug symbols, as can be seen by running 
```
cmake -S . -B build -DCMAKE_BUILD_TYPE="Debug" && cmake --build build
```

This issue is caused by the fact that [`scikit-build-core`](https://scikit-build-core.readthedocs.io/en/latest/configuration.html) strips binaries by default.

There are at two simple fixes:

1. Update `pyproject.toml` with
```
[tool.scikit-build]
install.strip = false 
```
2. Do not change `pyproject.toml` but update [README.md](https://github.com/FEniCS/dolfinx/tree/main/python/README.md) and [Dockerfile.end-user](https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile.end-user) to use the additional argument
```
pip install . [...] **--config-settings=install.strip=false**
```

If stripping release binaries provide some benefits to the project (smaller size perhaps?), then option 2 is the most flexible.

**Comment by jhale** [comment]
Thanks, good spot. Option 2. is best for the README. We need to look at any effect on binary performance and size before changing the Dockerfile.

**Comment by fmonteghetti** [comment]
Here is the size of `cpp.cpython-310-x86_64-linux-gnu.so` in kB for the possible values of `cmake.build-type` and `install.strip` [*]:

| build-type \ strip                  | false  | true  |
|---                |---            |---            |
| "Release"         | 4240            | 4240             |
| "RelWithDebInfo"  | 83424           | 3668              |
| "Debug"           | 65840             | 12264             |

I can also run a performance test. Is there a demo or a test that would be particularly relevant?

[*] This table was obtained by running the following commands (`Dockerfile.end-user`, `main` branch of dolfinx):
```
# cd /src/dolfinx/python
# pip uninstall fenics-dolfinx
# pip -v install --check-build-dependencies --config-settings=install.strip=false --config-settings=cmake.build-type="Release" --no-build-isolation .
# du /usr/local/lib/python3.10/dist-packages/dolfinx/cpp.cpython-310-x86_64-linux-gnu.so
```

**Comment by fmonteghetti** [comment]
> Here is the size of `cpp.cpython-310-x86_64-linux-gnu.so` in kB for the possible values of `cmake.build-type` and `install.strip` [*]:
> 

Under the same conditions as the ones described in the quoted post (in particular, the C++ lib is compiled with "RelWithDebInfo" with no symbol stripping), running
```
# multitime -q -n 10 python3 demo/demo_elasticity.py
```
gives the following average execution time (in seconds):

| build-type \ strip                  | false  | true  |
|---                |---            |---            |
| "Release"         | 15.226           | 15.215             |
| "RelWithDebInfo"  | 14.714           | 14.365              |
| "Debug"           | 23.704 (x)             | 22.960 (x)              |

In the cases marked "(x)", `nanobind` warns about leaked functions.

This simple test suggests that performance is not significantly impacted by stripping the Python bindings.

**Comment by francesco-ballarin** [comment]
> I can also run a performance test. Is there a demo or a test that would be particularly relevant?

Can you try with https://github.com/FEniCS/performance-test ?

**Comment by IgorBaratta** [comment]
> Can you try with https://github.com/FEniCS/performance-test ?

The performance tests are C++ only. Don't know if it's gonna be helpful here.

**Comment by francesco-ballarin** [comment]
> > Can you try with https://github.com/FEniCS/performance-test ?
> 
> The performance tests are C++ only. Don't know if it's gonna be helpful here.

Oops, sorry. I saw `Elasticity.py` and `Poisson.py` there and thought they were python demos, didn't realize that they were just for the ufl form definitions.
