### ISSUE TITLE
Simplify mesh creation interface (remove AdjacencyList for cells, use flat or 2D array)

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#2949]

**Comment by jorgensd** [comment]
Will this work for the future mixed element meshes?

**Comment by garth-wells** [comment]
> Will this work for the future mixed element meshes?

No, but the present interface doesn't either. It introduces complexity for no benefit. We need to follow our design principles and work form the bottom up and end with the right interface.
