### ISSUE TITLE
[BUG]: Is the Dirichlet boundary wrong in the description?

### ISSUE THREAD

**Issue by BillMaZengou** [FEniCS/dolfinx#2973]
### Summarize the issue

![Screenshot 2024-01-09 135409](https://github.com/FEniCS/dolfinx/assets/57754488/181f4693-cc79-4764-b49d-fe1f865fdb55)
According to the demo code, I think the Dirichlet boundary should be {(0, y) U (2, y)}, right?

### How to reproduce the bug

According to 
"""
facets = mesh.locate_entities_boundary(msh, dim=1,
                                       marker=lambda x: np.logical_or(np.isclose(x[0], 0.0),
                                                                      np.isclose(x[0], 2.0)))
"""

### Version

main branch

**Comment by francesco-ballarin** [comment]
Thanks @BillMaZengou, that does indeed need fixing.

Are you up for opening a pull request? You should, in this order: fork this repository, create a working branch, change the comment in `demo_poisson.py`, commit the change, push it to your fork, and then open the PR.

**Comment by BillMaZengou** [comment]
Sure, will do
