### ISSUE TITLE
Create a CG solver in C++ (with Python bindings)

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#2986]
### Describe new/missing feature

For many test cases, we just need a simple solver that works in parallel, without having to rely on PETSc.
We already have a demo with unpreconditioned CG and matrix-free.

* Make a built-in solver for use in test code

**Comment by chrisrichardson** [comment]
Simple Jacobi preconditioning would also be easy implement

**Comment by jhale** [comment]
This could be namespaced if we don't want to obviously expose it to users.

**Comment by chrisrichardson** [comment]
I guess it could go in the `la::` namespace?

**Comment by garth-wells** [comment]
I think we should leave CG in a demo(s). I don't see the value in having one very limited solver that in 99% of use cases is not helpful.

**Comment by chrisrichardson** [comment]
It would be helpful to remove PETSc from tests.

**Comment by garth-wells** [comment]
> It would be helpful to remove PETSc from tests.

That doesn't require putting a CG solver in the core. For tests it can be a test fixture.

**Comment by jhale** [comment]
Don't mind where it goes, as long as user's don't try and use it and think FEniCS is slow!

**Comment by chrisrichardson** [comment]
OK, let's add to tests - I guess that means it will be written in Python anyway.
