### ISSUE TITLE
Memory leak indicated when calling `dolfinx.io.distribute_entity_data`

### ISSUE THREAD

**Issue by anzil** [FEniCS/dolfinx#2997]
The following Python code produces the warning `[WARNING] yaksa: 1 leaked handle pool objects`:
```python3
from mpi4py import MPI
import dolfinx
import numpy

mesh = dolfinx.mesh.create_unit_cube(MPI.COMM_WORLD, 1, 1, 1)
tdim = mesh.topology.dim

cells = numpy.empty((0, 4), dtype=numpy.int64)
cell_values = numpy.empty((0, ), dtype=numpy.int32)

local_entities, local_values = dolfinx.io.distribute_entity_data(mesh, tdim, cells, cell_values)
```
which indicates a memory leak.

**Comment by chrisrichardson** [comment]
The Python wrappers use `nanobind` which reports a lot of memory leaks. Many of these are caused by Python itself, it is not really a cause for concern. The warnings should only appear in Debug mode.

**Comment by garth-wells** [comment]
@chrisrichardson This message comes from mpich rather than nanobind.
