### ISSUE TITLE
Use 3rd party logging library

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#3]
Replace home-baked logging with a library, e.g..

- https://github.com/gabime/spdlog
- https://github.com/SergiusTheBest/plog
- https://muflihun.github.io/easyloggingpp/

See also https://neutronsharc.blogspot.co.uk/2016/12/choose-c-logging-library-im-recently.html.

[Opinions of the Boost logging library online are not very positive - heavy weight and slow.]

**Comment by jhale** [comment]
I'd suggest using spdlog as it now has pybind11-based wrappers: https://github.com/bodgergely/spdlog-python

Would it be best to include the spdlog headers in the DOLFIN source tree or have it as (another) dependency like Eigen?

**Comment by garth-wells** [comment]
#311

**Comment by garth-wells** [comment]
Merged in PR #311.

**Comment by jhale** [comment]
spdlog turned out to be very slow at compile time. Other options?

**Comment by garth-wells** [comment]
Would need to check compile speed for each.

- Boost.Log v2 (https://www.boost.org/doc/libs/1_69_0/libs/log/doc/html/index.html)
  We already depend on Boost, so that makes it easy. But, with C++17 we might at some point want to remove the Boost dependency
- plog (https://github.com/SergiusTheBest/plog) 
- https://github.com/emilk/loguru
- https://github.com/KjellKod/g3log

**Comment by chrisrichardson** [comment]
Using loguru, as it is compatible with Google glog (as are many others), which should make it easy to replace should we need to.
