### ISSUE TITLE
[BUG]: NameError: name 'FunctionSpace' is not defined

### ISSUE THREAD

**Issue by rndhara** [FEniCS/dolfinx#3077]
### Summarize the issue

hi,
I want to test the simple [eigenvalue problem](https://fenicsproject.org/olddocs/dolfin/1.6.0/python/demo/documented/eigenvalue/python/documentation.html) but it is showing: `NameError: name 'FunctionSpace' is not defined'

### How to reproduce the bug

The name of the demofile is: [demo_eigenvalue.py](https://fenicsproject.org/olddocs/dolfin/1.6.0/python/_downloads/demo_eigenvalue.py).

### Version

main branch

**Comment by garth-wells** [comment]
This repository is for DOLFINx - the linked demo file is for legacy DOLFIN.
