### ISSUE TITLE
Fix assembly of elements that need orientation information

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#31]
Removing `mesh.order()` means that the alignment of dofs between cells is no longer given by the global vertex indices.
- [x] adjust code in `DofMapBuilder` for higher order (P3 and higher) elements
- [x] figure out how to support elements which need a global direction on facets (Hdiv, Hcurl)
* possibly by using global cell/vertex indices across boundary

**Comment by garth-wells** [comment]
See also https://github.com/FEniCS/ffcx/issues/56

**Comment by mscroggs** [comment]
This is done (for simplex meshes) in FEniCS/ffcx#224
