### ISSUE TITLE
[BUG]: `test_assemble_domains` segfaults on 6 processes

### ISSUE THREAD

**Issue by jpdean** [FEniCS/dolfinx#3117]
### Summarize the issue

`test_assemble_domains` fails with segfault on 6 processes

### How to reproduce the bug

`mpirun -n 6 python3 -m pytest test_assemble_domains.py`

### Version

main branch

**Comment by jorgensd** [comment]
Traceback is:
```bash
test_assemble_domains.py::test_assembly_dx_domains[meshtags-none] python3: /usr/local/dolfinx-real64/include/dolfinx/fem/DirichletBC.h:593: void dolfinx::fem::DirichletBC<T, U>::mark_dofs(std::span<signed char>) const [with T = double; U = double]: Assertion `_dofs0[i] < (std::int32_t)markers.size()' failed.
Fatal Python error: Aborted
```

**Comment by jorgensd** [comment]
This makes sense, as the test uses:
```python
    bc = dirichletbc(Function(V), np.arange(30))
```
which I guess is out of range on 6 processes.
How about using
`np.arange(V.dofmap.index_map.size_local // 2, dtype=np.int32)`?
