### ISSUE TITLE
[BUG]: dolfin / dolfinx /fenics / fenicsx not in debian testing repositories.

### ISSUE THREAD

**Issue by jmv2009** [FEniCS/dolfinx#3201]
### Summarize the issue

Currently dolfin and dolfinx do not appear in repositories for kali (debian-testing) when switching to 0.8.
ufl, basix, ffcx etc are in the repositories.
I earlier had problems with the current main branch.
https://github.com/FEniCS/dolfinx/commit/57da7d1705572893c4a6db590bd5c4e920cac0c5#r140396048

### How to reproduce the bug

Download and run the latest x64 kali live-iso. sudo apt update. sudo apt upgrade. sudo apt install fenicsx.

### Version

main branch

**Comment by francesco-ballarin** [comment]
We are working on it. Please be patient.

Note that this repository is for the development of dolfinx, not its packaging, so it's not the place where to report issues with debian packages.

**Comment by francesco-ballarin** [comment]
If you want to try out the `dolfinx` 0.8.0 package before it makes it into `testing`, you can add `unstable` to your repositories and try it from there.

**Comment by jmv2009** [comment]
Thanks. Is there also a reason legacy dolfin / fenics does not appear to be in the debian testing repositories?

**Comment by francesco-ballarin** [comment]
Keep an eye out in the unstable one, we will re-upload it there at some point in the future.

As I said, this is not the place for this sort of questions. I won't be replying any further, and I'll lock this down.
