### ISSUE TITLE
[BUG]: Visualization of one dimensional data with ParaView

### ISSUE THREAD

**Issue by schnellerhase** [FEniCS/dolfinx#3286]
### Summarize the issue

One dimensional data written in parallel produces wrong visualizations in Paraview's `Plot Data` filter.

### How to reproduce the bug

Run the provided code in a sequential manner (`np=1` ), load the `VTXWriter` output in Paraview (with the `ADIOS2VTXReader`) and apply the `Plot Data` filter. Deselect 'User Index for XAxis' and choose `Points_X` - this produces the first error: `No column X is set.`

So we stick to the visualization based on indices for now. This yields the following visualization
![image](https://github.com/FEniCS/dolfinx/assets/56360279/9e4c1c16-6a88-44de-9f4a-26aeae3baff6)

Rerunning in parallel yields for `np=2`
![image (1)](https://github.com/FEniCS/dolfinx/assets/56360279/59f6e062-4ec8-43a9-9ddc-4f660de453b1)

and for `np=4`
![image (2)](https://github.com/FEniCS/dolfinx/assets/56360279/5b5b4d8d-a9fb-4951-8ffc-6ca8759ece1e)

Note: the same behavior is also observed for the `VTKFile` based output. But in this setting the x-data is parsed correctly and the visualization breaks for the 'true' representation (np=1 and np=4):
![image](https://github.com/FEniCS/dolfinx/assets/56360279/50801b6d-c440-4ff0-b73b-bc3c7dfedaa6)
![image](https://github.com/FEniCS/dolfinx/assets/56360279/2dbb8e3f-9ebe-48e7-919a-ef1d996bb3b3)

### Minimal Example (Python)

```Python
from mpi4py import MPI

import numpy as np

from dolfinx import fem, io, mesh

msh = mesh.create_unit_interval(MPI.COMM_WORLD, 100)

V = fem.functionspace(msh, ("Lagrange", 1))

u = fem.Function(V)

u.interpolate(lambda x: np.sin(x[0] * np.pi))

with io.VTXWriter(msh.comm, "u.bp", u) as f:
    f.write(0.0)

with io.VTKFile(msh.comm, "u.pvd", "w") as f:
    f.write_function(u, 0)
```

### Output (Python)

```bash
[No output]
```

### Version

main branch

**Comment by jorgensd** [comment]
I think this is rather an issue with the Paraview filter `Plot Data`, than a bug in DOLFINx, as the `Plot over Line` filter works just fine.
![image](https://github.com/FEniCS/dolfinx/assets/8554300/db0f817c-2789-4921-a342-258674e4c469)

**Comment by jorgensd** [comment]
I am not sure what vtkGhostType really does.
At least the connectivities are right (You can inspect this with spreadsheet view):
![image](https://github.com/FEniCS/dolfinx/assets/8554300/ce2bd710-2243-4fc2-a8c9-0dea809f70aa)
When you run in parallel, several nodes have to be duplicated for visualization, as shown in:
![image](https://github.com/FEniCS/dolfinx/assets/8554300/a4d749ef-4482-4a12-b681-326a32a1da1c)
because each block inside the bp file has a local chunk of the mesh represented (in local indices, including ghost vertices).

**Comment by schnellerhase** [comment]
Ah I am using the `VTKFile` output, sorry that might be the difference.

**Comment by jorgensd** [comment]
I do not think this is a bug in DOLFINx, rather an issue with the how the different file-formats interact with Paraview's PlotData feature (as plot over line works just fine). I will close this issue, but please feel free to re-open it if you disagree.
I do not get the same `vtkOriginalPointIDs` with np2 and `n=4` with Paraview 5.13:
![image](https://github.com/user-attachments/assets/d12138a7-6d45-4088-9434-f52fdc00bfb5)
```python
from mpi4py import MPI

import numpy as np

from dolfinx import fem, io, mesh

msh = mesh.create_unit_interval(MPI.COMM_WORLD, 4)

V = fem.functionspace(msh, ("Lagrange", 1))

u = fem.Function(V)

u.interpolate(lambda x: np.sin(x[0] * np.pi))

with io.VTXWriter(msh.comm, "u.bp", u) as f:
    f.write(0.0)

with io.VTKFile(msh.comm, "u.pvd", "w") as f:
    f.write_function(u, 0)
```
Here we observe that the 7th duplicate node has the same original point index as the first node, which makes sense as they are written on different processes.
