### ISSUE TITLE
[BUG]: XDMFFile with ASCII encoding is broken in parallel

### ISSUE THREAD

**Issue by mleoni-pf** [FEniCS/dolfinx#3316]
### Summarize the issue

Writing to xdmf with ASCII encoding seems to write only the share of one of the processes, not the whole data set.

### How to reproduce the bug

```C++
  auto part = mesh::create_cell_partitioner(mesh::GhostMode::none);
  auto mesh = std::make_shared<mesh::Mesh<double>>(
      mesh::create_rectangle(MPI_COMM_WORLD, {{{0.0, 0.0}, {1.0, 1.0}}}, {3, 3},
                             mesh::CellType::triangle, part));

  io::XDMFFile file(mesh->comm(), mesh_file, "w", io::XDMFFile::Encoding::ASCII);
  file.write_mesh(*mesh);
```

### Version

main branch

**Comment by jorgensd** [comment]
I am not sure this is something we can fix easily, as it would involving gathering of all data on a single process in order, as `pugi::xml` does not have a notion of parallel writing.
@garth-wells @chrisrichardson should we simply add an error message if one tries to write to file in parallel with ascii encoding?
