### ISSUE TITLE
Check integrity of quadrilateral and hexahedral meshes

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#332]
The index order is important for quads/hexes, and it is possible to supply a mesh with incorrect ordering. This can be detected (e.g. for quad) by calculating the signed area of the triangles defined by points (0, 1, 2) and (1, 2, 3). For correct Z-ordering, these should be opposite sign.

**Comment by chrisrichardson** [comment]
This can also be extended to checking signed volume of tetrahedra.
Suggest an interface `bool validate(const Mesh& mesh);` perhaps in "mesh utils".

**Comment by jorgensd** [comment]
More tests on this in the dolfin-layer has been added in: https://github.com/FEniCS/dolfinx/pull/604 and https://github.com/FEniCS/dolfinx/pull/607 . Additional tests in FFCX has been added: https://github.com/FEniCS/ffcx/pull/173

**Comment by jorgensd** [comment]
@chrisrichardson , are there anything specific you think we should do to close this issue?
We have the pipline tests for quads and hexes: #607 . As we talked about earlier today, we could use unstructured meshes supplied from gmsh (through xdmf-xml) for the manufactured tests to ensure that everything is working as its supposed to. Additional tests for DG will be natural once @mscroggs has been able to permute the quadrature points.

**Comment by garth-wells** [comment]
@jorgensd I think we need to add some unstructured quad and hex meshes to the tests. We could then close this issue.

**Comment by jorgensd** [comment]
Can we close this one now, as #668 is merged?
