### ISSUE TITLE
[BUG]: dolfinx.io.gmshio.read_from_msh went wrong while using MPI

### ISSUE THREAD

**Issue by DHOPQ** [FEniCS/dolfinx#3327]
### Summarize the issue

I have a .msh file and want to use it in a fenicsx project as 
```python
from mpi4py import MPI
import dolfinx.fem as fem
from dolfinx.io import gmshio
mesh, _, _ = gmshio.read_from_msh("mesh/IAEA2d.msh", MPI.COMM_WORLD, gdim=2)
V = fem.functionspace(mesh,("Lagrange", 1))
``` 
the mesh file is built by freefem++, using movemesh23 to tranfer 2D mesh to 3D surface mesh. 
the running environment is built in docker.
here is the error log:
Info    : Reading 'mesh/IAEA2d.msh'...
Info    : 32818 nodes
Info    : 66334 elements
Info    : Done reading 'mesh/IAEA2d.msh'
Invalid rank, error stack:
internal_Issend(60788): MPI_Issend(buf=0x55e7cf6fdd91, count=1, MPI_BYTE, 1, 1, comm=0x84000005, request=0x55e7cf6fad54) failed
internal_Issend(60749): Invalid rank has value 1 but must be nonnegative and less than 1
Abort(205128454) on node 0 (rank 0 in comm 416): application called MPI_Abort(comm=0x84000005, 205128454) - process 0

when I change number of rank such as "mpirun -np 4 **",  still go wrong and the numbers in  2nd line become the same number as 4. 

### How to reproduce the bug

run the code I provide. 

### Minimal Example (Python)

```Python
from mpi4py import MPI
import dolfinx.fem as fem
from dolfinx.io import gmshio
mesh, _, _ = gmshio.read_from_msh("mesh/IAEA2d.msh", MPI.COMM_WORLD, gdim=3)
```

### Output (Python)

```bash
Info    : Reading 'mesh/IAEA2d.msh'...
Info    : 32818 nodes
Info    : 66334 elements
Info    : Done reading 'mesh/IAEA2d.msh'
Invalid rank, error stack:
internal_Issend(60788): MPI_Issend(buf=0x55e7cf6fdd91, count=1, MPI_BYTE, 1, 1, comm=0x84000005, request=0x55e7cf6fad54) failed
internal_Issend(60749): Invalid rank has value 1 but must be nonnegative and less than 1
Abort(205128454) on node 0 (rank 0 in comm 416): application called MPI_Abort(comm=0x84000005, 205128454) - process 0
```

### Version

main branch

### Installation

use docker based on ubuntu latest, then install fenicsx througe conda and the installing command is the one provided in fenicsx website

**Comment by jorgensd** [comment]
You would have to supply the mesh for anyone to be able to reproduce the issue.

**Comment by francesco-ballarin** [comment]
If I were to guess, the `msh` format that FreeFEM++ use is not the same as gmsh one, compare https://doc.freefem.org/documentation/developers.html#meshfiledatastructure to https://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format

Feel free to prove me wrong by uploading the file, but in the meantime I'll close the issue.

**Comment by Mustafaessou** [comment]
[import gmsh.txt](https://github.com/user-attachments/files/18025659/import.gmsh.txt)
Hey,
I'm encountering an issue when implementing fillets in my model. I've attached a simple code example for reference.

The problem only occurs when I use fillets; removing them makes everything work fine. I tested the same model using Circlearc, and it worked as expected. However, I’d prefer not to compute Circlearc for every corner, especially when dealing with non-perpendicular edges.

I'd appreciate any hints or advice on resolving this issue.

Thank you!

Best regards

**Comment by jorgensd** [comment]
@Mustafaessou 
If you call:
```python
boundary = gmsh.model.getBoundary([(2,1)], oriented=False)
print(boundary)
```
after
```python

bracket.addPlaneSurface(([1, 2]), 1)
bracket.synchronize()
```
you will see that the curve two is not in your new domain:
```bash
[(1, 1), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 102), (1, 103), (1, 104), (1, 105), (1, 106), (1, 107)]
```

Thus
```python
gmsh.model.addPhysicalGroup(1, [2], tag=1)  # Dirichlet boundary
```
is not sensible as a physical group.

As far as I can tell, curve 103 matches the one you want.
Debugged with:
```python
print(gmsh.model.occ.getCenterOfMass(1,2))
print([(bndry, gmsh.model.occ.getCenterOfMass(*bndry)) for bndry in boundary])
```
which you can also verify visually in GMSH

**Comment by Mustafaessou** [comment]
@jorgensd
Thank you very much—this is very helpful!
I actually suspected this might be the problem but didn’t know how to verify it.
Currently, I use the following code for visualization and debugging, but I couldn’t verify it with this approach:

```
if '-nopopup' not in sys.argv:
   gmsh.fltk.run()
```

Thanks again for your support!
