### ISSUE TITLE
[BUG]: Changing Mesh not exporting using VTXWriter

### ISSUE THREAD

**Issue by TimS-HSU** [FEniCS/dolfinx#3374]
### Summarize the issue

I need to change my mesh iteratively, however the export of this mesh does not work with VTXWriter. Inside the bp the mesh seems to remain constant even when saving a mesh after a movement (movement as in https://fenicsproject.discourse.group/t/changing-the-shape-in-the-surface-normal-directions/11013/6). mesh_policy should be "update", as this is the default.

### How to reproduce the bug

I ran the following script and looking at the results in Paraview 5.12.1, the mesh in mesh.bp does not change between "time steps" (i.e. before and after movement), while the XDMF File shows that the mesh has changed

### Minimal Example (Python)

```Python
from dolfinx.io import XDMFFile, VTXWriter
from dolfinx.mesh import create_unit_square
from dolfinx.fem import Expression, functionspace, Function
from ufl import SpatialCoordinate, as_vector

from mpi4py import MPI
world_comm = MPI.COMM_WORLD

mesh = create_unit_square(world_comm, 10, 10)
dimension = mesh.geometry.dim

x = SpatialCoordinate(mesh)
fnc = as_vector([x[0]**2, x[1]**2])

VTX_file = VTXWriter(world_comm, "mesh_test/mesh.bp", mesh)

VTX_file.write(0)
Space = functionspace(mesh, ("Lagrange", 1, (dimension,)))
fnc_expression = Expression(fnc, Space.element.interpolation_points())
fnc_fnc = Function(Space)
fnc_fnc.interpolate(fnc_expression)
mesh.geometry.x[:, :dimension] += fnc_fnc.x.array.reshape((-1, dimension))
mesh._cpp_object.geometry.x[:, :dimension] += fnc_fnc.x.array.reshape((-1, dimension))
VTX_file.write(1)
with XDMFFile(world_comm, "mesh_test/mesh.xdmf","w") as file:
    file.write_mesh(mesh)
```

### Version

0.8.0

**Comment by jorgensd** [comment]
This is a bug in Paraview, which has been fixed in Paraview 5.13.0-RC2.
Please update paraview.
