### ISSUE TITLE
Get Helmholtz demo working in real mode

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#339]
The Helmholtz demo is run only in complex mode. It would be good if it ran in both real and complex mode to pick any/most issues when running and testing in real mode.

**Comment by IgorBaratta** [comment]
The complex-valued solution comes from the incoming wave and the absorbing boundary condition. We could make a small change on them in real mode. 

If no one is already working on this issue, I'm willing to start right away.

**Comment by garth-wells** [comment]
@IgorBaratta would be great if you could take a look.

**Comment by garth-wells** [comment]
@IgorBaratta have you had a chance to look at this?

**Comment by michalhabera** [comment]
Seems resolved with https://github.com/FEniCS/dolfinx/pull/364
