### ISSUE TITLE
[BUG]: MatrixCSR indices and indptr arrays created as read-only

### ISSUE THREAD

**Issue by idoby** [FEniCS/dolfinx#3418]
### Summarize the issue

A la.MatrixCSR object now has its indices and indptr fields marked as non-writable for numpy, which breaks code that attempts to modify the matrix even after converting it to other sparse formats such as scipy (see reproduction details).

I believe this change was introduced (maybe unintentionally) by the switch to nanobind since version 0.7.3 lets me modify the sparsity pattern of the matrix after converting to scipy. Looks like it's due to the types of these arrays being communicated to nanobind as `const std::int32_t` and `const std::int64_t` respectively, which NB interprets as expressing non-writable NP arrays.

### How to reproduce the bug

This code is broken by the change introduced in 0.8.0:

```python
mat = assemble_matrix(lhs, bcs=[bc]).to_scipy()
mat.data[np.abs(mat.data) <= 1e-10] = 0.0
mat.eliminate_zeros()
```
The last line throws an error about WRITEBACKIFCOPY base being non-writable.
`eliminate_zeros` is a scipy function that modifies the sparsity of the matrix to remove data entries which exist in the description of the matrix, but are set to zero.

### Version

0.8.0

### Installation

conda-forge

**Comment by garth-wells** [comment]
DOLFINx sparse matrices have fixed sparsity. This offers performance benefits, plus CSR matrices are not suit to dynamic sparsity pattern changes. Changing the sparsity of CSR sparse matrix is effectively the same as creating a new matrix.

If you want to modify the sparsity of a SciPy sparse matrix that shares data with the DOLFINx CSR matrix, you should first copy the SciPy matrix.

**Comment by idoby** [comment]
Why are you deciding for me the kind of performance tradeoff I want to make?
SciPy supports these operations out of the box just fine, and their performance characteristics are good enough for my current needs.
I have many operations implemented directly on the SciPy CSR structure, and no, they do not always involve creating new arrays.
Why are you forcing me to copy the matrix and pay 2x the memory?

No other library works this way, all of the other libraries I use to create sparse matrices, e.g. networkx, just give me a standard SciPy CSR matrix.

I appreciate the work you've done on DolfinX and I realize you don't owe me anything, but is this prescriptivist approach really your final answer to this issue?

**Comment by jorgensd** [comment]
> Why are you deciding for me the kind of performance tradeoff I want to make? SciPy supports these operations out of the box just fine, and their performance characteristics are good enough for my current needs. I have many operations implemented directly on the SciPy CSR structure, and no, they do not always involve creating new arrays. Why are you forcing me to copy the matrix and pay 2x the memory?
> 
> No other library works this way, all of the other libraries I use to create sparse matrices, e.g. networkx, just give me a standard SciPy CSR matrix.
> 
> I appreciate the work you've done on DolfinX and I realize you don't owe me anything, but is this prescriptivist approach really your final answer to this issue?

It is very easy to make a wrapper that gives you the freedom to copy the data:
```python
from mpi4py import MPI
import numpy as np
import dolfinx
import ufl



def to_scipy(A, ghosted=False):
        """Convert to a SciPy CSR/BSR matrix. Data is not shared with MatrixCSR.

        Note:
            SciPy must be available.

        Args:
            ghosted: If ``True`` rows that are ghosted in parallel are
                included in the returned SciPy matrix, otherwise ghost
                rows are not included.

        Returns:
            SciPy compressed sparse row (both block sizes equal to one)
            or a SciPy block compressed sparse row matrix.
        """
        bs0, bs1 =A._cpp_object.bs
        ncols = A.index_map(1).size_local + A.index_map(1).num_ghosts
        if ghosted:
            nrows = A.index_map(0).size_local + A.index_map(0).num_ghosts
            data, indices, indptr = A.data, A.indices.copy(), A.indptr.copy()
        else:
            nrows = A.index_map(0).size_local
            nnzlocal = A.indptr[nrows]
            data, indices, indptr = (
                A.data[: (bs0 * bs1) * nnzlocal],
                A.indices[:nnzlocal].copy(),
                A.indptr[: nrows + 1].copy(),
            )

        if bs0 == 1 and bs1 == 1:
            from scipy.sparse import csr_matrix as _csr

            return _csr((data, indices, indptr), shape=(nrows, ncols))
        else:
            from scipy.sparse import bsr_matrix as _bsr

            return _bsr(
                (data.reshape(-1, bs0, bs1), indices, indptr), shape=(bs0 * nrows, bs1 * ncols)
            )


mesh = dolfinx.mesh.create_unit_square(MPI.COMM_WORLD, nx=5, ny=5)
V = dolfinx.fem.functionspace(mesh, ("Lagrange", 1))
u = ufl.TrialFunction(V)
v = ufl.TestFunction(V)

a = dolfinx.fem.form(ufl.inner(ufl.grad(u), ufl.grad(v))*ufl.dx)
A = dolfinx.fem.assemble_matrix(a)

A_scipy = to_scipy(A)
del A

print(A_scipy)
A_scipy.data[np.abs(A_scipy.data) <= 1e-10] = 0.0
A_scipy.eliminate_zeros()
print(A_scipy)
```
where the only memory copy is for the row and index pointers. 

As the `to_scipy()` matrix shares data with DOLFINx CSR matrix, it means that if the row and column ptrs are const in C++, they have to be const in Python.
