### ISSUE TITLE
[BUG]: module 'dolfinx' has no attribute 'has_petsc'

### ISSUE THREAD

**Issue by yoczhang** [FEniCS/dolfinx#3428]
### Summarize the issue

Hi, 

I'm trying to run the `demo_poisson.py`, but there has the error: `module 'dolfinx' has no attribute 'has_petsc'`

I tried searching online, but I couldn't find any relevant information. Has anyone encountered this situation?

### How to reproduce the bug

I'm trying to run the `demo_poisson.py`, but there has the error: `module 'dolfinx' has no attribute 'has_petsc'`, 

![image](https://github.com/user-attachments/assets/5d14dc73-d371-4a9d-b679-be763a8e3f59)

### Minimal Example (Python)

```Python
import importlib.util

if importlib.util.find_spec("petsc4py") is not None:
    import dolfinx

    if not dolfinx.has_petsc:
        print("This demo requires DOLFINx to be compiled with PETSc enabled.")
        exit(0)
    from petsc4py.PETSc import ScalarType  # type: ignore
else:
    print("This demo requires petsc4py.")
    exit(0)

from mpi4py import MPI

# +
import numpy as np

import ufl
from dolfinx import fem, io, mesh, plot
from dolfinx.fem.petsc import LinearProblem
from ufl import ds, dx, grad, inner
```

### Output (Python)

```bash
File "/demo_poisson/demo_poisson.py", line 72, in <module>
    if not dolfinx.has_petsc:
AttributeError: module 'dolfinx' has no attribute 'has_petsc'
```

### Version

0.8.0

### Installation

System info: `Windows-WSL2-Ubuntu-22.04`

**Comment by jorgensd** [comment]
If you are running v0.8.0, please consider the documentation for that version, as the main branch of the repository is the development branch.
https://github.com/FEniCS/dolfinx/tree/v0.8.0

https://docs.fenicsproject.org/dolfinx/v0.8.0/python/
