### ISSUE TITLE
Type inconsistency for MeshEntity indices

### ISSUE THREAD

**Issue by ageorgou** [FEniCS/dolfinx#344]
As far as I can tell, the index of a `MeshEntity` is mostly represented as a `size_t` (e.g in the `MeshEntity` constructor). However, there are cases where other types are used:
- `int32_t`, e.g. as the return type of `MeshEntity::index()`
- `uint32_t`, e.g. in one of the `MeshConnectivity::set` overloads: https://github.com/FEniCS/dolfinx/blob/cd30e7e5735452a35b6ca783b032b28d83e3db32/cpp/dolfin/mesh/MeshConnectivity.h#L117-L119
(the latter actually seems to use both `int32_t` and `uint32_t`)

Are there times where one type should be used over the other, or is there a trend to move towards one of them? I am asking because it would help us to know what to use when compiling against dolfinx.

Thanks in advance!

**Comment by garth-wells** [comment]
We are transitioning to signed integers, with `std::int32_t` for local (process) indices and `std::int64_t` for global indices.

**Comment by ageorgou** [comment]
Great, thanks for the quick answer! Happy to close this if there is nothing else to discuss.
