### ISSUE TITLE
Create demo in C++ that uses integration domains

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#3446]
Not currently tested in C++.

**Comment by garth-wells** [comment]
Do you mean demos that use `fem::compute_integration_domains`?

**Comment by jorgensd** [comment]
Used in: https://github.com/FEniCS/dolfinx/blob/617b35892e40a43d392954d81af7408aed641a1e/cpp/demo/codim_0_assembly/main.cpp#L112

**Comment by garth-wells** [comment]
Also in #3500.
