### ISSUE TITLE
UFC objects from C are allocated with malloc, but not correctly freed.

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#345]
In a few places, especially in `DofMapBuilder.cpp` and also in example C++ demos, there are lines like:

` std::make_shared<fem::FiniteElement>(std::shared_ptr<ufc_finite_element>(space->element()))`

which make `std::shared_ptr` or `std::unique_ptr` from a UFC object, which is allocated using `malloc` in generated code. In order to be correct, the `shared_ptr` or `unique_ptr` which takes ownership of the C pointer should also use `std::free` as the deleter, not the standard C++ deleter.

Failure to do this may be resulting in random code failure.

**Comment by garth-wells** [comment]
#356
