### ISSUE TITLE
Replace Boost Timer with `std::chrono`

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#3461]
We've observed accuracy issue with Boost Timer on some systems, plus removing it in favour of `std::chrono` (https://en.cppreference.com/w/cpp/header/chrono) is one less dependency.

**Comment by IgorBaratta** [comment]
I think there's also the issue that the timer is stored in seconds.
Maybe this conversion should be left to the end when we report timings.


https://github.com/FEniCS/dolfinx/blob/c5644696862635d02193d91b8dd147ea4e385c1d/cpp/dolfinx/common/Timer.cpp#L50

https://github.com/FEniCS/dolfinx/blob/c5644696862635d02193d91b8dd147ea4e385c1d/cpp/dolfinx/common/Timer.cpp#L43

**Comment by jpdean** [comment]
I checked the boost timer directly (`elapsed.wall`), and it doesn't seem to be the conversion that's causing the problem. The accuracy of the timer itself seems much worse than `std::chrono`, but maybe I'm missing something...

**Comment by IgorBaratta** [comment]
> I checked the boost timer directly (`elapsed.wall`), and it doesn't seem to be the conversion that's causing the problem. The accuracy of the timer itself seems much worse than `std::chrono`, but maybe I'm missing something...

I mean it more in general.  Rounding to seconds with floating-point numbers can lead to accumulated rounding errors when many time values are summed over time. Since we more often measure times in the order micro seconds than days.
