### ISSUE TITLE
Adding edge_tags and vertex_tags to gmshio

### ISSUE THREAD

**Issue by bayswiss** [FEniCS/dolfinx#3482]
### Describe new/missing feature

gmshio functions ```model_to_mesh``` and ```read_from_mesh``` return (only) the triplet ```(mesh, cell_tags, facet_tags)```, it would be very useful if it returned also ```edge_tags``` and ```vertex_tags```, like in the following: 

[https://github.com/ComputationalPhysiology/cardiac-geometriesx/blob/f7d304600972992299ef6d3938adeebd4c4e2af2/src/cardiac_geometries/utils.py#L47](url)

**Comment by jhale** [comment]
Seems like a good idea - in terms of implementation we should consider using a namedtuple as the number of return arguments is getting unwieldy.

**Comment by bayswiss** [comment]
The code in the link from Henrik Finsber returns indeed a named tuple: 
```python
class GMshModel(NamedTuple):
    mesh: dolfinx.mesh.Mesh
    cell_tags: dolfinx.mesh.MeshTags
    facet_tags: dolfinx.mesh.MeshTags
    edge_tags: dolfinx.mesh.MeshTags
    vertex_tags: dolfinx.mesh.MeshTags
```
After little modifications, this works flawlessly on my machine. I can try to adapt it for main dolfinx.
