### ISSUE TITLE
Python wrappers for `AdjacencyList` and `FiniteElement` missing

### ISSUE THREAD

**Issue by schnellerhase** [FEniCS/dolfinx#3483]
Both `AdjacencyList` and `FiniteElement` are exported for multiple data types and thus should be wrapped into a uniform python interface as done for other multi type exports.

**Comment by chrhansk** [comment]
I am experiencing a similar problem: I have so far been using version `0.7.1` of `fenics-dolfinx` using `anaconda`. This version has the class `FiniteElement` in the `ufl` module. 

However, when switching to `0.9.0`, the class is simply gone, breaking my code. Is there some workaround for the current version?

**Comment by jorgensd** [comment]
@chrhansk You are referring to `ufl.FiniteElement`, not `dolfinx.cpp.fem.FiniteElement`.
All finite elements from `ufl` has been removed (`ufl.FiniteElement`, `ufl.VectorElement`, `ufl.TensorElement`, and been replaced by the relevant `basix.ufl.element`. For an explanation about how to write these elements, see for instance: 
https://jsdokken.com/FEniCS-workshop/src/unified_form_language/ufl_elements.html#the-finite-element
or https://jsdokken.com/fenics22-tutorial/comparing_elements.html#piecewise-constant-pressure-spaces
and subsequent sections

**Comment by chrhansk** [comment]
@jorgensd: Thank you for the help and sorry for the noise.
