### ISSUE TITLE
Support uniform refinement of quadrilateral and hexahedral cell meshes

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#3489]
Presently, uniform and local refinement of simplex cell meshes is support. There is no support for refinement of quadrilateral or hexahedral cell meshes.

Uniform refinement of quadrilateral/hexahedral cell meshes should be reasonably straightforward.

**Comment by jorgensd** [comment]
Duplicate of: https://github.com/FEniCS/dolfinx/issues/3489

**Comment by jpdean** [comment]
This is https://github.com/FEniCS/dolfinx/issues/3489... Guessing you meant https://github.com/FEniCS/dolfinx/issues/3006 😛
