### ISSUE TITLE
[BUG]: test failed

### ISSUE THREAD

**Issue by medaminezghal** [FEniCS/dolfinx#3546]
### Summarize the issue

I'm trying to install dolfinx using PKGBUILD file
The build goes successfully and the check fail in the unittests
You can find the content of the file in this [url](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dolfinx)

### How to reproduce the bug

when you run the makepkg -si command the check fails:
```
Start 1: unittests
1/1 Test #1: unittests ........................***Exception: SegFault  3.44 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   3.44 sec

The following tests FAILED:
          1 - unittests (SEGFAULT)
Errors while running CTest
Output from these tests are in: ../dolfinx/src/build_test/Testing/Temporary/LastTest.log
```

Here is the output of the LastTest.log:
```
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x1a0)
==== backtrace (tid: 182322) ====
 0 0x000000000004c822 ucs_event_set_fd_get()  ???:0
 1 0x000000000004c9ed ucs_event_set_fd_get()  ???:0
 2 0x000000000003d1d0 __sigaction()  ???:0
 3 0x000000000014f0b9 std::basic_streambuf<char, std::char_traits<char> >::pubsync()  /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:278
 4 0x000000000014f0b9 std::ostream::flush()  /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:237
 5 0x00000000000c2c77 std::ios_base::Init::~Init()  /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++98/ios_init.cc:134
 6 0x000000000003f340 __cxa_finalize()  ???:0
 7 0x00000000000aa788 __do_global_dtors_aux()  crtstuff.c:0
=================================
<end of output>
```

### Version

0.9.0

### Installation

I'm using Arch Linux system and I'm trying to install it using the AUR repository.

**Comment by francesco-ballarin** [comment]
That's clearly an issue with the AUR packaging (since the test is running successfully on our CI), hence the issue must be opened there and not here.

**Comment by medaminezghal** [comment]
Could you send me the flags used in the build or the test process?
Or the default flags in the etc?makepkg.conf?
Maybe the problems come from those
