### ISSUE TITLE
[BUG]: undefined symbol: petscstack

### ISSUE THREAD

**Issue by KieranSQ** [FEniCS/dolfinx#3556]
### Summarize the issue

I am now getting this issue when I am trying to run FENICSx in complex mode - since real doesnt work either. I am using a WSL (Ubuntu) for this. 

`
from dolfinx.fem.petsc import LinearProblem
`
>>> undefined symbol: petscstack

Could you offer any advice on how to fix it?

### How to reproduce the bug

from dolfinx import fem
from dolfinx.fem.petsc import LinearProblem

### Version

main branch

**Comment by jorgensd** [comment]
What commands did you use to install DOLFINx?
Note that installation questions is more appropriate through our discourse: https://fenicsproject.discourse.group/

**Comment by francesco-ballarin** [comment]
As @jorgensd , post your question on https://fenicsproject.discourse.group/
