### ISSUE TITLE
[BUG]: interpolation nonmatching meshes with no overlap or partial overlap

### ISSUE THREAD

**Issue by mattfil** [FEniCS/dolfinx#3562]
### Summarize the issue

I am encountering an issue when performing interpolation between nonmatching meshes, where mesh1 serves as the source mesh and mesh2 as the destination mesh. The problem arises in scenarios where there is no overlap between the meshes, or when certain parts of mesh2 lie outside the domain of mesh1.

My expectation is that if I define a Function on the FunctionSpace associated with mesh2 and initialize it with specific values, for the regions of mesh2 that are outside of mesh1 these values should either remain unchanged after calling interpolate_nonmatching, or be replaced with a placeholder (e.g., NaN) to indicate regions where interpolation was not possible.

However, I observe that after calling interpolate_nonmatching, the values in the Function's .x array are replaced with zeros. This behavior makes it difficult to distinguish between regions where an actual zero value was interpolated from the source field and regions where no interpolation or extrapolation occurred.

Am I missing something?
Thank you,

Mattia

### How to reproduce the bug

Call broken() function below to reproduce the behaviour.

### Minimal Example (Python)

```Python
def broken() -> None:
    import dolfinx
    import numpy as np

    mesh1 = dolfinx.mesh.create_unit_square(MPI.COMM_WORLD, 10, 10)
    p0 = np.array([2.0, 2.0])  # Bottom-left corner
    p1 = np.array([3.0, 3.0])  # Top-right corner
    mesh2 = dolfinx.mesh.create_rectangle(MPI.COMM_WORLD, [p0, p1], [10, 10])

    funspace1 = dolfinx.fem.functionspace(mesh1, ("CG", 1))
    funspace2 = dolfinx.fem.functionspace(mesh2, ("CG", 1))
    uh = dolfinx.fem.Function(funspace1)
    uh.x.array.fill(-1.0)
    map_topology = funspace2.mesh.topology.index_map(funspace2.mesh.topology.dim)
    indicies_domains = np.arange(
        map_topology.size_local + map_topology.num_ghosts,
        dtype=np.int32,
    )
    nmmid = dolfinx.fem.create_interpolation_data(
        funspace2,
        funspace1,
        indicies_domains,
        1e-5,
    )
    q_func = dolfinx.fem.Function(funspace2)
    q_func.x.array.fill(np.nan)
    q_func.interpolate_nonmatching(uh, cells=indicies_domains, interpolation_data=nmmid)
    print(q_func.x.array)
```

### Output (Python)

```bash
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
```

### Version

0.9.0

### Installation

Windows 11 WSL, Ubuntu 24.04.1 LTS

**Comment by jorgensd** [comment]
> My expectation is that if I define a Function on the FunctionSpace associated with mesh2 and initialize it with specific values, for the regions of mesh2 that are outside of mesh1 these values should either remain unchanged after calling interpolate_nonmatching, or be replaced with a placeholder (e.g., NaN) to indicate regions where interpolation was not possible.
> 
> However, I observe that after calling interpolate_nonmatching, the values in the Function's .x array are replaced with zeros. This behavior makes it difficult to distinguish between regions where an actual zero value was interpolated from the source field and regions where no interpolation or extrapolation occurred.

That is not something that is easy to enforce for an arbitrary overlap.
Note that you can select what cells you want to interpolate onto, i.e. 
https://docs.fenicsproject.org/dolfinx/v0.9.0/python/generated/dolfinx.fem.html#dolfinx.fem.Function.interpolate_nonmatching
the cells input in this function can be restricted (and then has to be restricted in: https://docs.fenicsproject.org/dolfinx/v0.9.0/python/generated/dolfinx.fem.html#dolfinx.fem.create_interpolation_data `cells – Indices of the cells associated with V_to on which to interpolate into.

**Comment by mattfil** [comment]
Thank you for the reply. Yes, I know that I can restrict the interpolation to be done in portions of the destination domain, but extrapolations would still be done filling with zeros the function vector, which is something somehow unexpected. Since in the case of partial overlap, the nodes of the destination mesh in the overlapped area are interpolated correctly while the ones in the outer region get a zero value, wouldn't be possible to initialize the interpolation vector to some external value provided in the interpolate_nonmatching signature?

**Comment by jorgensd** [comment]
> Yes, I know that I can restrict the interpolation to be done in portions of the destination domain, but extrapolations would still be done filling with zeros the function vector, which is something somehow unexpected.

This is not true.
Consider for instance the following MWE:
```python
from mpi4py import MPI
import dolfinx
import numpy as np

mesh1 = dolfinx.mesh.create_rectangle(
    MPI.COMM_WORLD, [[0.0, 0.0], [1.0, 1.0]], [10, 10]
)
mesh2 = dolfinx.mesh.create_rectangle(
    MPI.COMM_WORLD, [[0.2, 0.5], [2.0, 2.0]], [20, 20]
)


V1 = dolfinx.fem.functionspace(mesh1, ("Lagrange", 1))
u1 = dolfinx.fem.Function(V1)
u1.interpolate(lambda x: x[0] + 2 * x[1])
V2 = dolfinx.fem.functionspace(mesh2, ("Lagrange", 1))
u2 = dolfinx.fem.Function(V2)
u2.interpolate(lambda x: 2 * np.sin(1.3 * x[0]))

num_cells_2 = (
    mesh2.topology.index_map(mesh2.topology.dim).size_local
    + mesh2.topology.index_map(mesh2.topology.dim).num_ghosts
)

bbox1 = dolfinx.geometry.bb_tree(mesh1, mesh1.topology.dim, padding=1e-6)
bbox2 = dolfinx.geometry.bb_tree(mesh2, mesh2.topology.dim, padding=1e-6)
global_b1_tree = bbox1.create_global_tree(mesh1.comm)
collisions = dolfinx.geometry.compute_collisions_trees(bbox2, global_b1_tree)
cells = np.unique(collisions[:, 0])

interpolation_data = dolfinx.fem.create_interpolation_data(V2, V1, cells, padding=1e-6)

u2.interpolate_nonmatching(u1, cells=cells, interpolation_data=interpolation_data)
u2.x.scatter_forward()

with dolfinx.io.XDMFFile(mesh2.comm, "u1.xdmf", "w") as xdmf:
    xdmf.write_mesh(mesh1)
    xdmf.write_function(u1)
with dolfinx.io.XDMFFile(mesh2.comm, "u2.xdmf", "w") as xdmf:
    xdmf.write_mesh(mesh2)
    xdmf.write_function(u2)
```
returning
![image](https://github.com/user-attachments/assets/252277ec-4d1e-4f07-a82b-7716743a33ef)

**Comment by mattfil** [comment]
Ah super! his completely resolves the issue. Apologies for not realizing this earlier.

Thank you,
Mattia
