### ISSUE TITLE
Support high-order meshes together with re-ordering

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#432]
See #431 for description of the issue.

**Comment by jorgensd** [comment]
Some work on this has been done in:
https://github.com/FEniCS/dolfinx/pull/586
where the need for reordering meshes of triangles and tetrahedrons has been made redundant for most Finite elements.

**Comment by garth-wells** [comment]
@jorgensd Could you summarise the status of this issue?

**Comment by jorgensd** [comment]
> @jorgensd Could you summarise the status of this issue?

The plan is to not re-order the meshes, but to permute the dofmap. 
This work is done by @mscroggs , and as far as I know, it should work for CG scalar function spaces on higher order meshes.
