### ISSUE TITLE
Lesser-used demo files no longer compile

### ISSUE THREAD

**Issue by ataber** [FEniCS/dolfinx#46]
I'm noticing a lot of the demo files are out of date now, many with namespace errors. I'm up to contribute fixes for some.

**Comment by garth-wells** [comment]
I would suggest compiling here a short list of demos for updating based on (i) functionality coverage and (ii) general value. I don't want many at this stage to avoid every small interface change leading to a large effort to updates demos.

We should also aim to remove demos that address functionally covered by other demos, and demos that would be better turned into tests. DOLFIN has too many demos with too much overlap.

**Comment by garth-wells** [comment]
Non-working demos have been removed for now.
