### ISSUE TITLE
Use LocalAssembler in Assembler

### ISSUE THREAD

**Issue by ataber** [FEniCS/dolfinx#47]
Looking at the signature of typical `LocalAssembler` methods, they look like they would fit right in with the assembly logic.

For example:
```
void LocalAssembler::assemble_cell(
    Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>& A,
    UFC& ufc, const Eigen::Ref<const EigenRowArrayXXd>& coordinate_dofs,
    const mesh::Cell& cell, const mesh::MeshFunction<std::size_t>* cell_domains)
```

Could replace a bit of [this logic](https://github.com/FEniCS/dolfinx/blob/master/cpp/dolfin/fem/Assembler.cpp#L337-L392), and DRY out the code a bit.

**Comment by michalhabera** [comment]
`LocalAssembler` was removed. For the custom assemblers we currently advocate use of numba assemblers - see the tests.
