### ISSUE TITLE
Add Constant class to hold data for constant coefficients

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#474]
When attaching a `Constant` to a UFL form, we need some storage for it, in advance of creating the `Form`. A simple `Eigen::Array` may suffice.
In addition, it should be modifiable from Python, e.g.:
```
c = Constant(0.5)
a = inner(c*grad(u), grad(v))*dx
c.value += 0.1
print(c.value)
```
or similar.
Also support vector and tensor constants.

**Comment by michalhabera** [comment]
Resolved with #501
