### ISSUE TITLE
XDMF and VTK function output incorrect in parallel

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#505]
When running in parallel, XDMF and VTK output of `dolfin::function::Function` is incorrect on the boundaries between processes.

![Screenshot from 2019-09-06 12-51-18](https://user-images.githubusercontent.com/4329467/64427712-c2565900-d0a9-11e9-8b7a-8b4fc5944194.png)

**Comment by chrisrichardson** [comment]
However, using `XDMF::write_checkpoint` works OK.

**Comment by garth-wells** [comment]
@chrisrichardson Try doing a forward scatter of the vector to update ghosts.

**Comment by chrisrichardson** [comment]
Yes, a line like:
`u.vector.ghostUpdate(addv=PETSc.InsertMode.INSERT, mode=PETSc.ScatterMode.FORWARD)`

fixes the problem. I'm not sure this should be inflicted on the user. Perhaps it can be called in `XDMFFile::write()`?

**Comment by garth-wells** [comment]
Let's leave it as-is for now. There are other places where a user needs to call it, e.g. on nonlinear solvers.
