### ISSUE TITLE
Revision of the "ghost" concept for meshes

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#506]
Currently, mesh ghosting has three options, `None`, `shared_facet` and `shared_vertex`. 

When a `Mesh` is created in `None` mode, there are no ghost cells, but there are shared vertices, shared edges (and faces in 3D). In order to be more consistent, shared entities would be better described as "ghost", except on one "owning" process (which could be the lowest rank process, for example).

Every entity would be either:

- "local" - not shared with another process.
- "shared" - shared with other process(es), but locally owned.
- "ghost" - shared with other process(es), and remotely owned.

It is probably worth moving the ghost entities to the end of the list of entities on each process, to keep them separate.

- [x] reorganise vertices on a `Mesh` with `GhostMode=none` so that "ghost" vertices are at the end of the list of vertices

- [x] create "ownership" arrays for all entity types (currently only for `Cells`), and fill them.

**Comment by garth-wells** [comment]
See #746.

**Comment by garth-wells** [comment]
@chrisrichardson can this be closed?
