### ISSUE TITLE
`jump` and `avg` not working for functions - "require bb_tree argument"

### ISSUE THREAD

**Issue by samuelpgroth** [FEniCS/dolfinx#512]
Currently, when implementing DG codes, the `jump` and `avg` commands only work when applied to the TrialFunction in the form. When applying them to, say the solution from a previous time step, an error is kicked up. Likely due to an unnecessary __call__() being invoked to evaluate the function, which requires a bb_tree.

**Comment by garth-wells** [comment]
See https://github.com/FEniCS/dolfinx/pull/511,

**Comment by garth-wells** [comment]
Fixed in #511 .
