### ISSUE TITLE
Change `Variable` to just take one string identifier

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#52]
`Variable` has two fields, `_name` and `_label` which are generally redundant. 

Many users end up writing code like:
```
u.rename('velocity', 'velocity')
```
which is confusing.

Suggest removing `_label`.

**Comment by nate-sime** [comment]
Underway in [nate/remove-variable-label](https://github.com/FEniCS/dolfinx/tree/nate/remove-variable-label)

**Comment by chrisrichardson** [comment]
Done
