### ISSUE TITLE
Fenics unable to read a correct XDMF file

### ISSUE THREAD

**Issue by arbolis** [FEniCS/dolfinx#526]
As discussed on the forum at https://fenicsproject.discourse.group/t/unable-to-read-the-mesh-with-meshio/1526, Fenics seems unable to read a proper XDMF file. Please see the link, as the MWE is gigantic to paste here.

**Comment by chrisrichardson** [comment]
@arbolis - can you post the XML part of the XDMF? Maybe that is not so large. It is not guaranteed that dolfin will read any XDMF file. For example, "Mixed" topology is not supported yet.

**Comment by arbolis** [comment]
@chrisrichardson  Here's the full mf.xdmf file:

```
<Xdmf Version="3.0">
  <Domain>
    <Grid Name="Grid">
      <Information Name="Information" Value="0"><![CDATA[<main/>]]></Information>
      <Geometry GeometryType="XYZ">
        <DataItem DataType="Float" Dimensions="1848 3" Format="HDF" Precision="8">mf.h5:/data0</DataItem>
      </Geometry>
      <Topology NumberOfElements="4042" TopologyType="Triangle">
        <DataItem DataType="Int" Dimensions="4042 3" Format="HDF" Precision="8">mf.h5:/data1</DataItem>
      </Topology>
      <Attribute AttributeType="Scalar" Center="Cell" Name="name_to_read">
        <DataItem DataType="Int" Dimensions="4042" Format="HDF" Precision="8">mf.h5:/data2</DataItem>
      </Attribute>
    </Grid>
  </Domain>
</Xdmf>
```

I didn't use anything fancy like Mixed topology, as far as I know.

**Comment by chrisrichardson** [comment]
Looking at example on discourse, it seems there may be a problem with the topology in the file.
