### ISSUE TITLE
Improved tests for higher order geometry meshes

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#54]
Need some unit tests for meshes of Tri-6 and Tet-10.

**Comment by nate-sime** [comment]
I'll have a go at getting some 3D tests working with a sphere using Tri-6 and Tet-10.

**Comment by kostyfisik** [comment]
Any documentation or links to the code for this issue? Just searching `Tri-6`  in the repository gives zero results.

**Comment by iitrabhi** [comment]
What I understand from the code is that Tri-6 is a quadratic triangular element and Tet-10 is a quadratic tetrahedral with 10 nodes. There are already tests present in test_mesh.py to check their degree and dimension. What kind of further tests are required?

**Comment by jorgensd** [comment]
One additional test for second order triangles is added in PR #532 . In a future PR I will probably consider Tet-10

**Comment by jorgensd** [comment]
More tests added in https://github.com/FEniCS/dolfinx/pull/579 and  https://github.com/FEniCS/dolfinx/pull/604

**Comment by jorgensd** [comment]
Are we happy we the tests that we have added?
Some improvements for the quad tests were added in #674

**Comment by jorgensd** [comment]
@garth-wells are we happy with the current coverage?

**Comment by garth-wells** [comment]
Quite a lot has changed around this issue. @mscroggs, @jorgensd do we have some test coverage now? (things have changed a bit since #674).
