### ISSUE TITLE
Compute cell volume using quadrature

### ISSUE THREAD

**Issue by nate-sime** [FEniCS/dolfinx#55]
With the advent of high order geometry representation, it will be useful (necessary?) to introduce `MeshEntity` volume computation with quadrature.

**Comment by blechta** [comment]
Alternatively one can rely on a form compiler rather than implementing it in DOLFIN.

**Comment by wence-** [comment]
FWIW, this approach (form compiler implements it) with quadrature is what tsfc does.

**Comment by garth-wells** [comment]
Moved: https://github.com/FEniCS/ffcx/issues/283.
