### ISSUE TITLE
Update the Stokes-Taylor-Hood demo to offer monolithic, block and nest assembly

### ISSUE THREAD

**Issue by nate-sime** [FEniCS/dolfinx#572]
Add monolithic, block and nest assembly options for the Stokes-Taylor-Hood demo. 

Inevitable polishing of the interface will be required as the updated demo takes shape.

**Comment by nate-sime** [comment]
Now that the interface for blocked system assembly is improved, I was hoping I could get a little advice on what should be shown in the improved demo.

Currently the Stokes Taylor-Hood demo solves a Couette-type flow problem with a dolphin shape in the centre of the domain.

The following modifications would be simple:
- Nest/Block-monolithic assembly
- Use pressure mass matrix preconditioner
- Use PETSc KSP & fieldsplit and appropriate solvers in the solve

Would anyone propose any further additions or modifications to demonstrate the new features of dolfin-x?

**Comment by garth-wells** [comment]
Sounds good. How about keeping it linear and doing 3D geometry with P2 boundary?

A nonlinear example with a block structure would make a good separate demo.

**Comment by garth-wells** [comment]
Fixed in #780.
