### ISSUE TITLE
Dolfin reading valid XDMF from mesh generators

### ISSUE THREAD

**Issue by nate-sime** [FEniCS/dolfinx#59]
gmsh output
```
<?xml version="1.0" ?>
<Xdmf Version="3.0">
  <Domain>
    <Grid Name="Grid">
      <Geometry Type="XYZ">
        <DataItem DataType="Float" Dimensions="13 3" Format="HDF" Precision="8">square_p2_0.h5:/data0</DataItem>
      </Geometry>
      <Topology NumberOfElements="4" Type="Triangle_6">
        <DataItem DataType="Int" Dimensions="4 6" Format="HDF" Precision="4">square_p2_0.h5:/data1</DataItem>
      </Topology>
    </Grid>
  </Domain>
</Xdmf>
```

dolfin required for input:

```
<?xml version="1.0" ?>
<Xdmf Version="3.0">
  <Domain>
    <Grid Name="Grid">
      <Geometry GeometryType="XYZ">
        <DataItem DataType="Float" Dimensions="13 3" Format="HDF" Precision="8">square_p2_0.h5:/data0</DataItem>
      </Geometry>
      <Topology NumberOfElements="4" TopologyType="Triangle_6">
        <DataItem DataType="Int" Dimensions="4 6" Format="HDF" Precision="4">square_p2_0.h5:/data1</DataItem>
      </Topology>
    </Grid>
  </Domain>
</Xdmf>
```

both are valid XDMF [http://www.xdmf.org/index.php/XDMF_Model_and_Format](http://www.xdmf.org/index.php/XDMF_Model_and_Format).

The difference is `<Geometry Type=...` and `<Geometry GeometryType=...` and `<Topology Type=...` and `<Topology TopologyType=...`

Need minor updates for dolfin to interpret both.

**Comment by garth-wells** [comment]
Can you clarify the message and text? Is something not working that should work?

**Comment by michalhabera** [comment]
@nate-sime The standard is defined here: https://gitlab.kitware.com/xdmf/xdmf/blob/master/Xdmf.dtd
I see there only `GeometryType` and `TopologyType`.

**Comment by michalhabera** [comment]
@nate-sime Is it also the `gmsh` producing wrong output? If it is just website I should have right to correct it.

**Comment by michalhabera** [comment]
@nate-sime I've corrected the XDMF wiki page.
