### ISSUE TITLE
Midpoint method for DirichletBC

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#622]
Currently, the only method for setting Dirichlet boundary conditions uses the vertices to determine which facets are on the boundary. This will be wrong for higher order function spaces on meshes consisting of simplices, as all vertices being on the boundary does not imply that all facets are on the boundary.

**Comment by garth-wells** [comment]
See #669.

**Comment by michalhabera** [comment]
Solved with #669 .
