### ISSUE TITLE
Add demo using pygmsh

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#624]
It would be helpful to have a demo showing how to use pygmsh to create DOLFIN meshes, including:
- In parallel
- With high-order geometry
- Different cell types

**Comment by jorgensd** [comment]
Initial step for this has been done by adding `build_distributed_mesh` to the python layer in PR #631 . With this merged, adding a pygmsh demo for parallel runs will become simpler.

**Comment by jorgensd** [comment]
An initial step would be to clean up:
https://github.com/FEniCS/dolfinx/blob/master/python/test/unit/mesh/test_mesh.py#L155-L218
as the ordering in this test is wrong and should be permuted.
We should also revise how to load meshes from pygmsh in parallel, as one right now has to call
`build_distributed_mesh`, as in:
https://github.com/FEniCS/dolfinx/blob/fa1f1905d6ab752e9e4bcaffc88a1e7eb699560f/python/test/unit/fem/test_dof_permuting.py#L56-L63

What do you think @garth-wells , should we sit down and revise this?

**Comment by IgorBaratta** [comment]
The issue of this approach, in my view,  is that it loses track of the mesh tags, cell data; in comparison to just writing and reading the mesh file.

**Comment by garth-wells** [comment]
See #1019, #1022 and #1020 .
