### ISSUE TITLE
Create paraview plugin for HDF5 dolfin files

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#644]
Due to the limitiations of XDMF for higher order geometries, and the poor parallel performance of VTK in parallel, we should create a HDF5 plugin for Paraview, which uses VTK to render higher order geometries.
This is a tedious task, which is not high on my list of priorities. 
https://kitware.github.io/paraview-docs/latest/cxx/PluginHowto.html
If anyone has experience with writing paraview plugins/readers I would be grateful for any help.

**Comment by chrisrichardson** [comment]
@js947 - maybe something you can help with?

**Comment by tianyikillua** [comment]
Maybe begin with a Python plugin like in [https://github.com/tianyikillua/paraview-meshio-reader/blob/master/meshioReader.py](https://github.com/tianyikillua/paraview-meshio-reader/blob/master/meshioReader.py)?

**Comment by tianyikillua** [comment]
You mean probably a plugin that is able to read the HDF5 generated by https://github.com/FEniCS/dolfinx/pull/632 for arbitrary order Lagrange elements? Do you have an example file?

**Comment by jorgensd** [comment]
> You mean probably a plugin that is able to read the HDF5 generated by #632 for arbitrary order Lagrange elements? Do you have an example file?
> 
> Another idea is to work upstream on a DOLFINX HDF5 reader on [meshio](https://github.com/nschloe/meshio). Then use a generic mesh plugin (https://github.com/tianyikillua/paraview-meshio-reader/blob/master/meshioReader.py) for ParaView visualization.

Yes, visualization of such meshes the one tested in #632 are those that i would like to visualize. You can use the test in that PR as an example of a HDF5 file in python/test/unit/io/test_gmsh_io.py.
Im working on an [example](https://github.com/FEniCS/dolfinx/blob/dokken/pygmshdemos/python/demo/mesh_IO/demo_mesh_io.py) for a for 1-3 order triangular and quarilateral meshes. It clearly exposes that we should make a better way to interact with meshio.

**Comment by tianyikillua** [comment]
You now have a simple Python plugin [paraview-dolfinx-reader](https://github.com/tianyikillua/paraview-dolfinx-reader) loadable in ParaView >= 5.6 (see the [release notes](https://blog.kitware.com/paraview-5-6-0-release-notes) indicating that Python plugins can now be used), for your HDF5 mesh files dedicated for arbitrary-order Lagrange elements.

Now loading a HDF5 file you may now select the `dolfinx` reader option.
<img width="559" src="https://user-images.githubusercontent.com/4027283/69007237-a689f180-093b-11ea-83d7-9fee9c2086b5.png">

Some examples with `"nonlinear subdivision level" = 4` to illustrate order effects, using `test_gmsh_io.py`

**First order tetrahedral elements**
<img width="398" src="https://user-images.githubusercontent.com/4027283/69007248-cc16fb00-093b-11ea-82ec-3b4503664773.png">

**Second order**
<img width="412" alt="Screenshot 2019-11-17 at 12 57 10" src="https://user-images.githubusercontent.com/4027283/69007264-126c5a00-093c-11ea-82f1-b727aae150e0.png">

The element type is indeed of "Lagrange" type.
<img width="1073" src="https://user-images.githubusercontent.com/4027283/69007275-2e6ffb80-093c-11ea-814a-e63ad305ad00.png">

**Third order** (by modifying your `test_gmsh_io.py` file)
<img width="586" src="https://user-images.githubusercontent.com/4027283/69007292-5b241300-093c-11ea-9222-7161f7eb13d7.png">

So it's no longer a unit ball but a unit orange. We do have 20 points per cell, but I suspect that cell ordering is not correct according to [https://blog.kitware.com/modeling-arbitrary-order-lagrange-finite-elements-in-the-visualization-toolkit](https://blog.kitware.com/modeling-arbitrary-order-lagrange-finite-elements-in-the-visualization-toolkit).

**Comment by tianyikillua** [comment]
With [3rd order triangle / quad elements] (https://github.com/FEniCS/dolfinx/blob/dokken/pygmshdemos/python/demo/mesh_IO/demo_mesh_io.py) and a `Calculator = (1 + coordsX + coordsY^3) * iHat + (0.1 * sin(coordsX) + coordsY) * jHat`.

Seems to work fine for cubic triangle elements (with arbitrary order Lagrange cell type)
<img width="600" src="https://user-images.githubusercontent.com/4027283/69007752-24e99200-0942-11ea-8870-ae42fb8a259b.png">

For quads, not so sure
<img width="600" src="https://user-images.githubusercontent.com/4027283/69007755-316dea80-0942-11ea-95fb-8ecc6b20c73e.png">

Again, cell points ordering?
<img width="600" src="https://user-images.githubusercontent.com/4027283/69007762-51051300-0942-11ea-90cc-fd8fda2bb7bc.png">

**Comment by jorgensd** [comment]
@tianyikillua thanks for the help. I will have a look at this tomorrow. For third order triangles, the output you get from pygmsh is ordered as msh and not vtk (as the visualization expects. I will add documented demos that shows the correct ordering for quads and triangles of order 1-3.

**Comment by garth-wells** [comment]
Preference is to use established formats supported by ParaView.
