### ISSUE TITLE
Should pybind11 casters be installed?

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#656]
Dear all,
while working on an external library (which relies on pybind11 for wrapping C++ code on the fly), I need to use MPI and PETSc casters present in `python/src`. Unfortunately, those casters do not get installed with the rest of dolfinx.
While I can easily workaround this by copying those casters in my library (as I am doing right now), I am opening this issue to inquire whether you think that they should get installed as part of the `python/setup.py`, so that external projects need not to duplicate them.

Thanks,
Francesco

(discussed today on this with @jhale)

**Comment by chrisrichardson** [comment]
Simple answer: yes. I tried to do this before, but not sure of best location for python-related .h files

**Comment by francesco-ballarin** [comment]
> Simple answer: yes. I tried to do this before, but not sure of best location for python-related .h files

I agree, the choice of the location is not clear to me either.

**Comment by jhale** [comment]
Seems like an open issue.

https://github.com/pypa/packaging-problems/issues/84

Could we get cmake to install them to e.g. dolfin/pybind11 or
dolfin-pybind11 under the standard include path?

**Comment by francesco-ballarin** [comment]
Hi,
I think I will be able to open a pull request on this during the next week.

I will install the two header files in `dolfin/pybind11`.
Furthermore, I will also separate the `MPICommWrapper.cpp` file from the rest of the pybind11 library, in a standalone library such as `libdolfin-pybind11.so`, otherwise the user would be force to link to `lib/python3.X/site-packages/fenics_dolfin-2019.2.0.dev0-py3.X-linux-x86_64.egg/dolfin/cpp.cpython-3Xm-x86_64-linux-gnu.so`, which is a complicated name that is not available anywhere in the pkgconfig.

In doing so, should I try to restore the pybind11 wrapping tests that were available in dolfin2019.1.0's `python/test/unit/jit/test_jit.py` (say, one which shows the wrapping of MPIComm and one with a PETSc object)? If so, in which folder of `python/test/unit` should I put them?

**Comment by garth-wells** [comment]
Could we make `MPICommWrapper` header-only? Nice to avoid the need to link to a library for something small.

Fine to add back some JIT tests, but they should be carefully chosen to do things that are not better done via NumPy, Numba or cffi.

**Comment by francesco-ballarin** [comment]
Would the dolfnx equivalent of the simple tests at lines 49 and 189 of
https://bitbucket.org/fenics-project/dolfin/src/ec57db53f2b13f1768214829e8b4f80fc32205cf/python/test/unit/jit/test_jit.py
be ok?

**Comment by jhale** [comment]
@garth-wells A test using `cppimport` and `pybind11` might be nice?
