### ISSUE TITLE
Proposal of interface change to SparsityPatternBuilder

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#657]
Dear all,
in the context of the multiphenics library, I have a custom `BlockDofMap`, for which the `cell_dofs()` method may only return a subset of dolfinx `DofMap::cell_dofs()`. In particular, I then use my custom `BlockDofMap` during the initialization of the sparsity pattern.

In the old dolfin, my `BlockDofMap` inherited from `GenericDofMap`, and since `GenericDofMap::cell_dofs()` was virtual, 
I could simply reuse the code in `SparsityPatternBuilder`.

In the current dolfinx, even if my `BlockDofMap` were to inherit from `DofMap` (it does not, at the moment), I cannot reuse the code in `cpp/dolfin/fem/SparsityPatternBuilder.cpp` because `DofMap::cell_dofs()` is not virtual anymore.

I understand that effort was put into removing all virtual methods. In order to allow the same code reuse that I had in the legacy version, would it be possible to change the last argument of
```
void SparsityPatternBuilder::*(
    la::SparsityPattern& pattern, const mesh::Mesh& mesh,
    const std::array<const fem::DofMap*, 2> dofmaps)
```
e.g. to a function pointer, where such a function is taking as input an index i (either 0 or 1) and an cell index c, and it is wrapping all the calls to `dofmaps[i]->cell_dofs(c)`?
The interface change will not hinder the overall functionality of dolfinx, and I would be able to to use my custom implementation of `cell_dofs()` without having to duplicate all the `SparsityPatternBuilder` code.

Thanks,
Francesco

(discussed this week with @michalhabera and @jhale)

**Comment by garth-wells** [comment]
I think passing a `std::function` rather than a `fem::DofMap` is a good idea and very much consistent with the new design approach.

**Comment by francesco-ballarin** [comment]
OK, great. Please assign me to this issue, and I will open a pull request on this.

**Comment by francesco-ballarin** [comment]
Closing, as associated PR #659 was not accepted.
