### ISSUE TITLE
Support evaluate_reference_basis in TensorProduct elements

### ISSUE THREAD

**Issue by nate-sime** [FEniCS/dolfinx#67]
Consider the following
```
from dolfin import *
mesh = UnitSquareMesh(MPI.comm_world, 3, 3, cell_type=CellType.Type.quadrilateral)
mesh.geometry.coord_mapping = fem.create_coordinate_map(mesh)
V = FunctionSpace(mesh, "CG", 1)
f = interpolate(Expression("x[0]", degree=1), V)
print(f.vector().get_local())
V.set_x(f.vector(), 1.0, 0)
print(f.vector().get_local())
```
which yields
```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

I've tried to track down the cause of the problem:

Many aspects of dolfinx require `ufc_coordinate_mapping::compute_physical_coordinates` which in turn requires `ufc_finite_element::evaluate_reference_basis_ffc_element`. These are populated by code automatically generated by FFC. However, in the case of tensor product elements:
```
ufc_finite_element::evaluate_reference_basis
ufc_finite_element::evaluate_reference_basis_derivatives
ufc_finite_element::transform_reference_basis_derivatives
```
are unsupported by `FIAT.tensor_product.TensorProductElement`(`.get_coeffs`) and therefore populated with 
```
  // evaluate_reference_basis_derivatives: Function is not supported/implemented.
return -1;
```
Currently, no error will be thrown in dolfinx with `return -1` as the result, and will unexpected yield incorrect answers.

**Comment by chrisrichardson** [comment]
Branch of ffcx `chris/quad-basis` now generates code for `evaluate_reference_basis()` for quad and hex elements. However, this relies on the coefficients being generated by FIAT, so there is also a FIAT branch of the same name.
Remaining issue:
* `evaluate_reference_basis_derivatives()` still needs work. At the moment, it is returning wrong values.
Either figure out how to generate the correct `dmats` array in FIAT, or disable the output.

**Comment by chrisrichardson** [comment]
Now dmats also works, I think.

**Comment by garth-wells** [comment]
@chrisrichardson Is the FIAT change necessary? Is it not just a tensor product of the 1D case?

**Comment by chrisrichardson** [comment]
I guess the tensor product is done in fiat, so that is the logical place for it, 
and it keeps the ffc code cleaner.

**Comment by jorgensd** [comment]
I guess this is fixed in master? Consider the following:
```
from dolfin import * 
from dolfin.cpp.mesh import CellType 
mesh = UnitSquareMesh(MPI.comm_world, 3, 3, cell_type=CellType.quadrilateral) 
mesh.geometry.coord_mapping = fem.create_coordinate_map(mesh) 
V = FunctionSpace(mesh, ("CG", 1)) 
f = Function(V) 
f.interpolate(lambda x: x[:,0]) 
print(f.vector.array) 
V.set_x(f.vector.array, 2.0, 0) 
print(f.vector.array)    
```
returning:
```
[-2.77555756e-17 -2.77555756e-17  3.33333333e-01  3.33333333e-01
 -2.77555756e-17  3.33333333e-01  6.66666667e-01  6.66666667e-01
  6.66666667e-01 -2.77555756e-17  3.33333333e-01  6.66666667e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
[-5.55111512e-17 -5.55111512e-17  6.66666667e-01  6.66666667e-01
 -5.55111512e-17  6.66666667e-01  1.33333333e+00  1.33333333e+00
  1.33333333e+00 -5.55111512e-17  6.66666667e-01  1.33333333e+00
  2.00000000e+00  2.00000000e+00  2.00000000e+00  2.00000000e+00]
```
