### ISSUE TITLE
Creating a DG/DGT MixedElement causes failure during assemble_matrix for certain terms in variational problem

### ISSUE THREAD

**Issue by jpdean** [FEniCS/dolfinx#684]
Minimum failing example:
```
from dolfin import FunctionSpace, MPI, UnitSquareMesh
from dolfin.fem import assemble_matrix
from ufl import (VectorElement, ds, inner, grad, dot, FacetNormal, MixedElement,
                 TrialFunctions, TestFunctions)

mesh = UnitSquareMesh(MPI.comm_world, 1, 1)

u_FE = VectorElement("DG", mesh.ufl_cell(), 1)
ubar_FE = VectorElement("DGT", mesh.ufl_cell(), 1)
Q_g = FunctionSpace(mesh, MixedElement([ubar_FE, u_FE]))

# Trial and test functions
(ubar, u) = TrialFunctions(Q_g)
(vbar, v) = TestFunctions(Q_g)

n = FacetNormal(mesh)
A = inner(u, dot(grad(v), n)) * ds
a = assemble_matrix(A)
```
Running the above gives "ValueError: too many values to unpack (expected 1)" from FIAT/hdiv_trace.py. Note that this problem does not occur if the variational form is replaced with `A = inner(u, v) * ds`, for example.

**Comment by chrisrichardson** [comment]
It seems likely to be a problem in `ffc` and/or `fiat`. I think the `grad(v)` probably triggers derivative formation for ffc's tables, and it will do this for the whole 'mixed' element. I suppose it can't form derivatives for the facet-restricted DGT FunctionSpace...
```
mesh = UnitSquareMesh(MPI.comm_world, 1, 1)

ubar_FE = VectorElement("DGT", mesh.ufl_cell(), 1)
Q_g = FunctionSpace(mesh, ubar_FE)

# Trial and test functions                                                                      
u = TrialFunction(Q_g)
v = TestFunction(Q_g)

A = inner(grad(u), grad(v))* ds
a = assemble_matrix(A)

```
will behave in much the same way.

**Comment by chrisrichardson** [comment]
I suppose line 204 of `hdiv_trace.py` in FIAT should be:
`nonzerovals, = element.tabulate(0, new_points).values()` 
i.e. order should be always zero. But this will still not fix the problem of mixed spaces.
