### ISSUE TITLE
Hide Menu Options in Jupyter notebook

### ISSUE THREAD

**Issue by mc-marcocheng** [FEniCS/dolfinx#699]
I am new to dolfin.
When I execute the command in Jupyter notebook:
`dolfin.RectangleMesh(dolfin.Point(0,0), dolfin.Point(1,1), 10, 10)`
A menu appears that blocks the view of succeeding cells:
![issue](https://user-images.githubusercontent.com/57459045/72715140-e626c100-3baa-11ea-9c90-2b1304f3606e.PNG)

Is it possible to hide the "Options" menu in the notebook? Thanks.

**Comment by francesco-ballarin** [comment]
This seems to be related to dolfin and not dolfinx. You may want to ask this as a question at https://fenicsproject.discourse.group/
