### ISSUE TITLE
cmake problem finding SLEPc: needs link to mpi

### ISSUE THREAD

**Issue by RizzerOnGitHub** [FEniCS/dolfinx#715]
My dolfinx build is not finding SLEPc.  dolfin 2019.2.0 (git head from dolfin-old) does successfully find SLEPc. I'm not sure if the problem is in my SLEPc installation or in dolfinx' FindSLEPc.cmake

I'm trying a preliminary build of dolfinx adapting the old [configuration scripts](https://salsa.debian.org/science-team/fenics/dolfinx/blob/master/debian/rules) from Debian.
cmake finds PETSc but rejects SLEPc:

    -- Check size of PetscInt
    -- Check size of PetscInt - done
    -- Looking for PETSC_USE_COMPLEX
    -- Looking for PETSC_USE_COMPLEX - not found
    -- Found PETSc: TRUE (found suitable version "3.12.3", minimum required is "3.10")
    ....
    -- Checking for one of the modules 'crayslepc_real;SLEPc'
    -- Test SLEPC_TEST_RUNS with shared library linking - Failed
    -- Test SLEPC_TETS_RUNS with static linking - Failed
    -- SLEPc could not be configured. (missing: SLEPC_TEST_RUNS) (found suitable version "3.12.2", minimum required is "3.10")

Running cmake with `--debug-trycompile` to inspect test code, I see it's just a simple matter of linking the test to libmpi.so. In the build dir at `obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_fd401.dir` where slepc_test_lib.cpp.o is located, the test is set to run

    $ /usr/bin/c++  -fpermissive   -Wl,-z,relro  ./slepc_test_lib.cpp.o  -o cmTC_fd401 -Wl,-rpath,/usr/lib/slepcdir/slepc3.12/x86_64-linux-gnu-real/lib:/usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/lib /usr/lib/slepcdir/slepc3.12/x86_64-linux-gnu-real/lib/libslepc_real.so /usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/lib/libpetsc_real.so
    /usr/bin/ld: ./slepc_test_lib.cpp.o: undefined reference to symbol 'ompi_mpi_comm_self'
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libmpi.so.40: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status

So a simple work around is to link with `c++ -lmpi`, or with `mpic++`.

But is this a problem which should be fixed in FindSLEPc.cmake ?  What has changed in FindSLEPc.cmake  from dolfin-old to give this problem?  Would it be related to the change in handling `LINK_LIBRARIES` near l.134 or l.167?

**Comment by RizzerOnGitHub** [comment]
I see FindPETSc.cmake in dolfinx has added `MPI_LINK_LIBRARIES`, so perhaps the same is needed in FindSLEPc.cmake.

**Comment by RizzerOnGitHub** [comment]
This patch gets it going: https://salsa.debian.org/science-team/fenics/dolfinx/blob/master/debian/patches/FindSLEPc_MPI.patch

**Comment by garth-wells** [comment]
Thanks @RizzerOnGitHub - could you create a PR against dolfinx?

**Comment by RizzerOnGitHub** [comment]
I don't seem to have push access,

    $ git push --set-upstream origin dparsons/FindSLEPc
ERROR: Permission to FEniCS/dolfinx.git denied to RizzerOnGitHub.
    fatal: Could not read from remote repository.

Should I be given write access to the repo to push a branch for PR?  Forking seems a bit over-the-top.

**Comment by RizzerOnGitHub** [comment]
Chris has added me now. Thanks @chrisrichardson

**Comment by garth-wells** [comment]
Fixed in #719.
