### ISSUE TITLE
Bug in dof permutations

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#728]
The following triggers an assertion in the function `triangle_rotation_and_reflection` in `dofs_permutation.cpp`.

```python
from dolfinx import MPI, FunctionSpace, UnitSquareMesh
from dolfinx.cpp.mesh import CellType

V = FunctionSpace(UnitSquareMesh(MPI.comm_world, 6, 6,
                                 CellType.triangle),  ('N1curl', 2))
```

**Comment by mscroggs** [comment]
I think this is fixed in the branch https://github.com/FEniCS/dolfinx/tree/mscroggs/dof_perm_bug. Once tests have run, I'll merge this into #702

**Comment by mscroggs** [comment]
The fix in that branch works for triangles, but does not yet work for tetrahedra. (quads and hexes as yet untested)
