### ISSUE TITLE
Make PETSc and petsc4py required dependencies

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/dolfinx#73]
Make PETSc and petsc4py both required dependencies in CMakeLists.txt

**Comment by jhale** [comment]
Fixed in #111

**Comment by chrisrichardson** [comment]
Actually, I think this was slightly wrong. petsc4py should not be a required dependency of the C++ build, only the Python build.

**Comment by jhale** [comment]
Looking at `master`, that is how it is.

**Comment by garth-wells** [comment]
The C++ build system should be fixed so it does not depend on petsc4py. All the necessary info is available via the PETSc headers.

**Comment by chrisrichardson** [comment]
```

**Comment by garth-wells** [comment]
We should get `generate-form-files.py` to take command lines arguments that are passed through to ffc.
