### ISSUE TITLE
Add dof permutations for spaces where the shape of the dof arrangement does not match the shape of the face

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/dolfinx#736]
For some spaces (eg `("N2E", tetrahedron, 3)`), the arrangement of dofs on the faces/interior does not match the shape of the face. For these spaces, the dof_permuter will either fail an assert or incorrectly permute the dofs. This was causing #728.

Picture of `("N2E", tetrahedron, 3)` from [femtable](http://femtable.org/):
![N2E](http://femtable.org/images/large/N2e3_tetrahedron.png)

There are also dofs of different types on a face, which could cause further complications.

**Comment by garth-wells** [comment]
@mscroggs Is this still an issue?

**Comment by mscroggs** [comment]
Yes, it's going to be a problem for some quad spaces, eg AAF
![AAF order 2](http://femtable.org/images/large/AAf2_hexahedron.png)
