### ISSUE TITLE
Saving to VTK renders unusable files with Paraview 5.8.0

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#785]
See [Paraview issue](https://gitlab.kitware.com/paraview/paraview/issues/19698)

**Comment by garth-wells** [comment]
Seems like an easy fix on our side - switch to signed int (which maybe have been done already). In any case the change would be consistent with our internal use of signed ints.

**Comment by jorgensd** [comment]
Seems like this has been fixed already. At least I cant find any vtk-files in the test suit using uint.
