### ISSUE TITLE
Be careful with std::vector<> (and Eigen types) as arguments in pybind wrappers (big data)

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#85]
There are two strong reasons why `std::vector<>` should not be an argument in pybind wrappers (at least for big arrays).

1. Any python object that has `__getitem__` and `__len__` method is casted element-by-element to `std::vector`. Since most of our python objects have these methods,  they can be used in places with completely different meaning and create big confusion for users in best case, hidden bugs in worst case.
2. We store big data in python as `numpy.ndarray`. Pybind wrapper that expects `std::vector` has to convert it and this conversion seems inefficient. On the other hand, pybind wrapper that expects numpy's `py::array_t` has to convert to `std::vector` inside the binding, this seems much faster (10x).

This relates to subscriptable behaviour of PETScVector and inefficiency of `PETScVector::set_local()` called in python on PETScVector.

Both effects are demonstrated by the following code
Note: there must be keyword `py::array::c_style`, otherwise passing sliced numpy array gives wrong results.

```python
import dolfin as d
import numpy
import time

base_code = '''
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/numpy.h>
namespace py = pybind11;

#include <vector>
#include <stdio.h>

void numpy_to_std(std::vector<double>& vals)
{
    std::cout << "numpy_to_std called " << std::endl;
    
}

void std_to_std(std::vector<double>& vals)
{
    std::cout << "std_to_std called " << std::endl;
}

PYBIND11_MODULE(SIGNATURE, m)
{
    m.def("numpy_to_std", [](py::array_t<double, py::array::c_style> vals){
        // Init std::vector based on pybind array
        std::vector<double> values(vals.data(), vals.data() + vals.size());
        numpy_to_std(values);
    });
    m.def("std_to_std", &std_to_std);
}
'''

compiled = d.compile_cpp_code(base_code)

# Create big numpy data array
N = 1E+8
vec = numpy.random.rand(int(N))

# This binding is efficient
# no implicit conversion left to pybind
t0 = time.time()
compiled.numpy_to_std(vec)
print(time.time() - t0)

# This binding is inefficient
t0 = time.time()
compiled.std_to_std(vec)
print(time.time() - t0)


class BadObject(object):
    def __getitem__(self, pos):
        return 1.0

    def __len__(self):
        return 1


bo = BadObject()
# No error here, very confusing
compiled.std_to_std(bo)

```
--->
```
numpy_to_std called 
0.29850053787231445
std_to_std called 
3.804774045944214
std_to_std called 
```

**Comment by garth-wells** [comment]
I don't think `std::vector` is the problem. The same happens with Eigen array. I'm not even sure if it's pybind11 or NumPy that drives the component-wise access.

**Comment by michalhabera** [comment]
Didn't mean to offend `std::vector` ;) My point is: keep bindings closest to the argument that it is called with, not to the cpp's arguments types.

**Comment by garth-wells** [comment]
It's not so simple. pybind11 maps Numpy <-> EIgen arrays, but the issue you observe still arises when passing a PETScVector to `set_local`. Removing `__len__` fixes the problem in the particular case considered.

I would say the 'fix' in this case is to not try to treat a PETScVector like a NumPy array.

**Comment by michalhabera** [comment]
Ok. Let us not draw any conclusion unless we completely understand what is going on in numpy <-> eigen <-> std::vector etc. conversion. But would be good to keep this issue here so wont be forgotten.

**Comment by garth-wells** [comment]
I think we can close this now - #297 addresses a number of the issues, and using pybind11/Eigen without type conversions give some safety.
