### ISSUE TITLE
build using generated code in build dir not source dir

### ISSUE THREAD

**Issue by RizzerOnGitHub** [FEniCS/dolfinx#888]
Currently the cpp CMakeLists.txt at [l.256](https://github.com/FEniCS/dolfinx/blob/de0c61e9ef549b5f2929b85dc967640a4f5bbfa9/cpp/CMakeLists.txt#L256) says "# FIXME: Generate files in Build directory instead, at least for demo" 

Indeed, this may prevent testing of a parallel build of real and complex versions of dolfinx.  The builds can be completed in distinct build dirs.  But if we build in order and then test, `cd $BUILDDIR_REAL; cmake ..; make`, `cd $BUILDDIR_COMPLEX; cmake ..; make`,  followed by `cd $BUILDDIR_REAL; make demos`, then building the demos (poisson) fails with

    /usr/bin/c++  -DDOLFINX_VERSION=\"2019.2.9.99\" -DEIGEN_MAX_ALIGN_BYTES=32 -DHAS_SLEPC -I/home/projects/fenics/dolfinx/cpp -I/home/projects/fenics/dolfinx/cpp/dolfinx -isystem /usr/lib/python3/dist-packages/ffcx/codegeneration -isystem /usr/include/eigen3 -isystem /usr/include/hdf5/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/include -isystem /usr/lib/slepcdir/slepc3.12/x86_64-linux-gnu-real/include  -fpermissive -O2 -g -DNDEBUG   -Wno-comment -pthread -std=c++17 -o CMakeFiles/demo_poisson.dir/main.cpp.o -c /home/projects/fenics/dolfinx/cpp/demo/poisson/main.cpp 
    In file included from /home/projects/fenics/dolfinx/cpp/dolfinx/common/dolfin_common.h:23,
                     from /home/projects/fenics/dolfinx/cpp/dolfinx/dolfinx.h:5,
                     from /home/projects/fenics/dolfinx/cpp/demo/poisson/main.cpp:92:
    /home/projects/fenics/dolfinx/cpp/dolfinx/common/types.h:17:7: error: conflicting declaration ‘using ufc_scalar_t = double’
       17 | using ufc_scalar_t = double;
          |       ^~~~~~~~~~~~
    In file included from /home/projects/fenics/dolfinx/cpp/demo/poisson/main.cpp:90:
    /home/projects/fenics/dolfinx/cpp/demo/poisson/poisson.h:20:32: note: previous declaration as ‘typedef struct std::complex<double> ufc_scalar_t’
       20 |  typedef std::complex<double > ufc_scalar_t;
          |                                ^~~~~~~~~~~~
    make[5]: *** [demo/poisson/CMakeFiles/demo_poisson.dir/build.make:79: demo/poisson/CMakeFiles/demo_poisson.dir/main.cpp.o] Error 1

Since the complex build was configured after the real build, cpp/demo/poisson/poisson.h gets generated in the source dir with ufc_scalar_t defined as std::complex<double > instead of double.

As the comment in l.256 says, these generated files like poisson.h should be generated under the builddir, specific to each build.

But there's something else going here.  The generated files *are* placed into the builddir, so l.17 in $BUILDDIR_REAL/cpp/demo/poisson/poisson.h does in fact have the correct real definition

    typedef double ufc_scalar_t;

The problem here is that `make demos` is invoking source from the source dir, not the builddir, even though the source has been copied to the builddir.

That is, the problem is that make is invoking `-c /home/projects/fenics/dolfinx/cpp/demo/poisson/main.cpp` (from the source dir) instead of `-c /home/projects/fenics/dolfinx/build-real/cpp/demo/poisson/main.cpp` (in the build dir, with BUILDDIR_REAL=/home/projects/fenics/dolfinx/build-real/)

main.cpp has `#include "poisson.h"` so it grabs poisson.h from its local directory, the source dir not the build dir.

Not sure how best to achieve it, but a simple outcome could have cmake configure the makefile to run the equivalent of `c++ -c $BUILDDIR_REAL/$source_path/*.cpp` instead of `c++ -c $SRCDIR/$source_path/*.cpp`, since the cpp file has been copied to the builddir.

**Comment by RizzerOnGitHub** [comment]
From discussion at https://stackoverflow.com/questions/60517842/generate-then-use-source-file-using-cmake-in-clion, one solution is something like

    set(SOURCE_FILES main.cpp ${CMAKE_CURRENT_BINARY_DIR}/poisson.h ${CMAKE_CURRENT_BINARY_DIR}/poisson.c)
in the CMakeLists.txt for the poisson dir.

But that's complicated by the point that CMakeLists.txt  itself is a generated file, generated by `cpp/cmake/scripts/generate-cmakefiles.py`, and doesn't know about `poisson.h` as such.

**Comment by garth-wells** [comment]
Fixed in #897.
