### ISSUE TITLE
complex poisson demo provides contradictory definition of ufc_scalar_t

### ISSUE THREAD

**Issue by RizzerOnGitHub** [FEniCS/dolfinx#893]
I've got parallel installations of dolfinx, both real and complex builds supported, selected at runtime via PETSC_DIR.

Trying to test the poisson demo against the complex build in this environment, PETSC_USE_COMPLEX is found by cmake.  But an error happens compiling main.cpp. This is related to the problem in #888 .  That bug addresses the problem happening at build time, here I'm addressing running the demo at runtime using an existing installation.

The error is

    [ 66%] Building C object poisson/CMakeFiles/demo_poisson.dir/poisson.c.o
    cd /home/projects/fenics/build/dolfinx/dolfinx-demo/poisson && /usr/bin/mpicc -DDOLFINX_VERSION=\"2019.2.9.99\" -DEIGEN_MAX_ALIGN_BYTES=32 -DHAS_SLEPC -isystem /usr/lib/python3/dist-packages/ffcx/codegeneration -isystem /usr/include/eigen3 -isystem /usr/include/hdf5/openmpi -isystem /usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-complex/include -isystem /usr/lib/slepcdir/slepc3.12/x86_64-linux-gnu-complex/include  -Wno-comment -pthread -o CMakeFiles/demo_poisson.dir/poisson.c.o   -c /home/projects/fenics/build/dolfinx/dolfinx-demo/poisson/poisson.c
    cd /home/projects/fenics/build/dolfinx/dolfinx-demo/poisson && /usr/bin/c++  -DDOLFINX_VERSION=\"2019.2.9.99\" -DEIGEN_MAX_ALIGN_BYTES=32 -DHAS_SLEPC -isystem /usr/lib/python3/dist-packages/ffcx/codegeneration -isystem /usr/include/eigen3 -isystem /usr/include/hdf5/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-complex/include -isystem /usr/lib/slepcdir/slepc3.12/x86_64-linux-gnu-complex/include  -Wno-comment -pthread -std=gnu++17 -o CMakeFiles/demo_poisson.dir/main.cpp.o -c /home/projects/fenics/build/dolfinx/dolfinx-demo/poisson/main.cpp
    In file included from /usr/include/dolfinx/common/dolfin_common.h:23,
                     from /usr/include/dolfinx.h:5,
                     from /home/projects/fenics/build/dolfinx/dolfinx-demo/poisson/main.cpp:92:
    /usr/include/dolfinx/common/types.h:15:7: error: conflicting declaration ‘using ufc_scalar_t = struct std::complex<double>’
       15 | using ufc_scalar_t = std::complex<double>;
          |       ^~~~~~~~~~~~
    In file included from /home/projects/fenics/build/dolfinx/dolfinx-demo/poisson/main.cpp:90:
    /home/projects/fenics/build/dolfinx/dolfinx-demo/poisson/poisson.h:17:16: note: previous declaration as ‘typedef double ufc_scalar_t’
       17 | typedef double ufc_scalar_t;
          |                ^~~~~~~~~~~~
    make[2]: *** [poisson/CMakeFiles/demo_poisson.dir/build.make:76: poisson/CMakeFiles/demo_poisson.dir/main.cpp.o] Error 1

There are a couple of angles to the problem here.

poisson.h was generated using cpp/cmake/scripts/generate-form-files.py.  PETSC_DIR has been set to petsc-complex and exported, so why has poisson.h been generated with

    typedef double ufc_scalar_t;

instead of

    typedef std::complex<double> ufc_scalar_t;

?

Possibly this is a problem with my configuration, since complex demo_poisson does run successfully at build time if I build from a clean source separate from a real configuration (#888 addresses trying to build both real and complex builds in separate builddirs using the same source dir).

But the problem raises a separate question, why is ufc_scalar_t being defined in poisson.h in the first place?  Why isn't poisson.h including it from the installed headers,
e.g. adding

    #include <dolfinx/common/types.h>

Is it a bug in ffcx when it processes poisson.ufl?

**Comment by francesco-ballarin** [comment]
Fixed by #897
