### ISSUE TITLE
dockerimage github workflow should not be carried out on forks

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#967]
The `Build and push Docker CI test image` schedule
https://github.com/fenics/dolfinx/blob/master/.github/workflows/dockerimage.yml
should not be carried out on forks, because 
1) it currently fails due to forks not having access to upstream secrets (see e.g.
https://github.com/francesco-ballarin/dolfinx/runs/581615290?check_suite_focus=true )
2) even if such access was granted, we would not want users of forks to be able to push to the official docker hub image.

A temporary workaround is for instance described at https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/m-p/42814#M5129

Please advise if you think that the workaround is acceptable, and I will open a PR

**Comment by garth-wells** [comment]
@francesco-ballarin the linked-to work-around seems a bit complicated. Is https://github.com/FEniCS/dolfinx/tree/garth/no-docker-build-forks enough?

**Comment by francesco-ballarin** [comment]
Yes, that is exactly what I had in mind (only the if statement).

Do you want me to try it on my fork? I guess I will have to temporarily change the schedule on my fork, in order not to wait till next Monday.

Before I try it, I cannot understand if that CI run is supposed to happen only on master. If not, what would happen if a branch had a different Dockerfile?

**Comment by garth-wells** [comment]
Yes, please try. The 'schedule' section should only run on `master` by default with Github Actions.

**Comment by francesco-ballarin** [comment]
I confirm it works, see e.g. https://github.com/francesco-ballarin/dolfinx/runs/582495289?check_suite_focus=true . I am opening the PR.
