### ISSUE TITLE
clean up docker repositories

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#970]
We currently have several docker repositories around:
* github actions pushes to https://hub.docker.com/u/fenicsproject
* circle CI pushes to https://hub.docker.com/u/dolfinx
* former tests in https://github.com/FEniCS/dolfinx/packages still shown in the packages sections on github.

This is fine for now I guess, but in future we might want to clean this up a bit (ideally only one source would suffice), in order not to confuse end users. I am available to help in this task, if granted 
 appropriate access.

**Comment by jhale** [comment]
The current plan is this:

-  We keep 'non-user' images at https://hub.docker.com/u/fenicsproject. We've identified the need for some images, e.g. CI testing images that users don't need to see (confusing) but are necessary for developers.
- The 'user facing' images will be kept at https://hub.docker.com/u/dolfinx. Some of the images we have now will be combined (hopefully, real and complex!), and some will be removed (notebook).
- Unfortunately, we cannot delete the unwanted github packages (has already been raised with GitHub support). A workaround is to take the repository private, then delete the packages. This will be done in a quieter period when it affects less people as it has consequences (all followers will be removed, for example).

**Comment by garth-wells** [comment]
Looks like https://github.com/FEniCS/dolfinx/packages is cleaned up. @jhale is there anything left to do or can this issue be closed?

**Comment by jhale** [comment]
This is quite nicely implemented now, I think.

**Comment by jhale** [comment]
Yep, I completely forgot, will do ;) Thanks for the reminder!
