### ISSUE TITLE
SCOTCH in docker images segfaults when partitioning/refining large meshes.

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#994]
The following example:
```
import dolfinx
import dolfinx.log
from dolfinx.mesh import refine
from mpi4py import MPI
dolfinx.log.set_log_level(dolfinx.log.LogLevel.INFO)

r_lvl = 4
N = 4
mesh = dolfinx.UnitCubeMesh(MPI.COMM_WORLD, N, N, N)
for i in range(r_lvl):
    mesh = refine(mesh, redistribute=True)
```
Causes the command `mpirun -n 15 python3 test.py` in `dolfinx/real` to throw:
```
pp:28    INFO| Elapsed wall, usr, sys time: 0.001417, 0.000000, 0.000000 (SCOTCH: call SCOTCH_dgraphBuild)

Loguru caught a signal: SIGBUS

...

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 3448 RUNNING AT 2c6df35acce8
=   EXIT CODE: 135
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Bus error (signal 7)
This typically refers to a problem with your applic
```
By changing partitioner to KaHIP by rewriting `mesh/Partitioning.cpp::partition_cells`, the code above runs.

**Comment by jorgensd** [comment]
Kahip makes it possible to use more processors, but fails with 24 processors. I think this indicates that there is something wrong in the input data we send to the graph partioners.

**Comment by chrisrichardson** [comment]
In SCOTCH, there is a graph checking routine, that can be turned on (in DEBUG mode?). Can you try with this?

**Comment by jorgensd** [comment]
The graph is consistent (it is not throwing runtime-errors).

**Comment by chrisrichardson** [comment]
Seems to be crashing with `SIGBUS`, and in different places each time. On further investigation, we found that the other docker image `fenicsproject/test-env` which uses OpenMPI does not crash.

**Comment by chrisrichardson** [comment]
Simpler example:
```
import dolfinx
import dolfinx.log
from dolfinx.mesh import refine
from mpi4py import MPI
dolfinx.log.set_log_level(dolfinx.log.LogLevel.INFO)

N = 60
mesh = dolfinx.UnitCubeMesh(MPI.COMM_WORLD, N, N, N)
```

**Comment by chrisrichardson** [comment]
Seems to be an issue with MPICH:

https://wiki.mpich.org/mpich/index.php/Frequently_Asked_Questions#Q:_Why_MPI_Put_raises_SIGBUS_error_inside_docker.

Solution is to use `--shm-size=512m` (for example) when launching a docker image.

**Comment by garth-wells** [comment]
See also https://github.com/Azure/batch-shipyard/issues/8.
