### ISSUE TITLE
python docs don't find demos

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/dolfinx#995]
When building python docs,  `cd python/doc; make html`, the docs no longer find the demos. So the demos are not linked in the demos.html page.

python/doc/source/demos.rst refers to rst files, demos/poisson/demo_poisson.py.rst etc.

But in dolfinx the demo dirs now contain the *.py files only, not *.py.rst, since PR #291.

python/demo/generate-demo-files.py should be generating the .rst. Does the path in demos.rst need to be updated? Or should generate-demo-files.py be invoked by python/doc/Makefile?

**Comment by RizzerOnGitHub** [comment]
generate-demo-files.py does work manually

    cd python/doc
    python3 ../demo/generate-demo-files.py
    make html

The generation step could be added to python/doc/Makefile. Would want a clean step added to remove the generated .py.rst files.  Perhaps generate-demo-files.py could be patched to place the generated files under a destination dir when specified (e.g. python/doc/build/source) to simplify clean up.

**Comment by garth-wells** [comment]
Doc structure has been changed.
